/* ADTR isolated prototype. Synthetic, memory-only data; no API or external network. */
(() => {
'use strict';
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const escape = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',connect:'M12 3v5 M5 16v-5h14v5 M3 16h4v5H3z M10 16h4v5h-4z M17 16h4v5h-4z M9 3h6v5H9z',asset:'M12 3l9 5v9l-9 5-9-5V8z M3 8l9 5 9-5 M12 13v9',detect:'M21 11a9 9 0 1 1-5-8 M21 3l-9 9 M16 3h5v5',threat:'M12 3L2 21h20L12 3z M12 9v5 M12 17v1',response:'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6',report:'M5 3h10l4 4v14H5z M15 3v5h4 M8 12h8 M8 16h5',work:'M4 6h16v15H4z M9 3h6v6H9z M8 13h8 M8 17h5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',search:'M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15 M16 16l5 5',chevron:'M9 5l7 7-7 7',down:'M5 9l7 7 7-7',arrow:'M4 12h16 M14 6l6 6-6 6',refresh:'M20 7v5h-5 M4 17v-5h5 M19 12a7 7 0 0 0-12-6 M5 12a7 7 0 0 0 12 6',plus:'M12 5v14 M5 12h14',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',bell:'M18 8a6 6 0 0 0-12 0v7l-2 3h16l-2-3z M10 21h4',user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M4 21v-3a8 8 0 0 1 16 0v3',server:'M3 3h18v7H3z M3 14h18v7H3z M6 6h1 M6 17h1 M11 6h7 M11 17h7',group:'M9 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M2 20v-3a7 7 0 0 1 14 0v3 M17 4a3 3 0 0 1 0 6 M19 14a5 5 0 0 1 3 5v1',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v6l4 2',check:'M5 12l4 4L19 6',close:'M6 6l12 12 M6 18L18 6',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 11v6 M12 7v1',globe:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M3 12h18 M12 3c-5 4-5 14 0 18 M12 3c5 4 5 14 0 18',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3',dots:'M5 12h1 M11 12h1 M17 12h1',menu:'M4 6h16 M4 12h16 M4 18h16',filter:'M3 4h18l-7 8v7l-4 2v-9z',layers:'M12 3L2 8l10 5 10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6',activity:'M2 12h5l3-8 4 16 3-8h5',mail:'M3 5h18v14H3z M3 5l9 8 9-8',key:'M8 4a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M12 12l9 9 M17 17l3-3',file:'M5 3h9l5 5v13H5z M14 3v5h5 M8 12h8 M8 16h6'};
const icon = name => `<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="${icons[name]||icons.file}"/></svg></span>`;
const tag=(text,tone='')=>`<span class="tag ${tone}">${escape(text)}</span>`;
const btn=(text,action,tone='',more='')=>`<button class="button ${tone}" data-action="${action}" ${more}>${text}</button>`;
const link=(text,path,cls='button subtle')=>`<a class="${cls}" href="#/${path}">${text}</a>`;
const NAV=[['overview','安全工作台','overview'],['connections','AD 接入','connect'],['assets','目录资产','asset'],['detection','检测与规则','detect'],['threats','告警与调查','threat'],['response','响应处置','response'],['reports','报告与导出','report'],['work','任务与消息','work'],['admin','平台管理','settings']];
const TITLES={overview:['SECURITY OVERVIEW','安全态势总览','从身份与目录出发，掌握风险、接入状态与正在发生的变化。'],connections:['AD CONNECTIVITY','AD 域接入','管理域连接与凭据用途，连接诊断和目录读取分别授权。'],assets:['IDENTITY & DIRECTORY','目录资产','在获授权的目录中，沿身份、设备与关系寻找证据。'],detection:['DETECTION & RULES','检测与规则','以明确的规则版本与目标范围，发起可追溯的检测。'],threats:['THREAT INVESTIGATION','威胁调查','还原事件上下文，让每一个判断都有可核查的证据。'],response:['CONTROLLED RESPONSE','响应处置','先核实范围与影响，再以独立任务跟踪处置和恢复。'],reports:['REPORTS & EXPORTS','报告与导出','把调查结论与运行证据整理为可追溯的报告和数据文件。'],work:['OPERATIONS WORKSPACE','任务与消息','追踪每一次提交、每一个结果，以及尚待核对的状态。'],admin:['PLATFORM ADMINISTRATION','平台管理','功能权限、域范围与凭据用途分别管理，默认拒绝。']};
const ROLES={newuser:{name:'新用户 · 待授权',initial:'NU',domains:[],write:false,admin:false},expireduser:{name:'恢复用户 · 待授权',initial:'RU',domains:[],write:false,admin:false},maintainer:{name:'平台运维员',initial:'OP',domains:[],write:true,admin:false},operator:{name:'安全负责人',initial:'SO',domains:['alpha','beta'],write:true,admin:true},viewer:{name:'只读调查员',initial:'RO',domains:['alpha'],write:false,admin:false},platform:{name:'平台管理员 · 无域授权',initial:'PA',domains:[],write:true,admin:true}};
const DOMAINS={alpha:'alpha.example.test',beta:'beta.example.test'};
const TEMPLATES={baseline:{id:'baseline',name:'安全基线',version:'1.4.2'},identity:{id:'identity',name:'身份异常复查',version:'1.4.2'},permissions:{id:'permissions',name:'目录权限评估',version:'1.4.2'}};
const ASSETS=[
{id:'a1',name:'demo.alex',type:'用户',domain:'alpha',desc:'身份风险调查对象',risk:87,level:'高风险',status:'启用',group:'DEMO-Tier0',mail:'demo.alex@example.test',seen:'2026-10-10 00:00:00 UTC',guid:'demo-guid-user-001',sid:'S-1-5-21-100-200-300-1001'},
{id:'a2',name:'DEMO-DC-01',type:'计算机',domain:'alpha',desc:'域控制器',risk:42,level:'中风险',status:'启用',group:'Domain Controllers',mail:null,seen:'2026-10-10 00:00:00 UTC',guid:'demo-guid-device-001',sid:'S-1-5-21-100-200-300-1101'},
{id:'a3',name:'DEMO-Tier0',type:'组',domain:'alpha',desc:'特权身份集合',risk:68,level:'高风险',status:'已观测',group:'Administrators',mail:null,seen:'2026-10-10 00:00:00 UTC',guid:'demo-guid-group-001',sid:'S-1-5-21-100-200-300-1201'},
{id:'a4',name:'demo.service',type:'用户',domain:'alpha',desc:'服务身份',risk:26,level:'低风险',status:'启用',group:'Service Accounts',mail:null,seen:'2026-10-09 23:58:20 UTC',guid:'demo-guid-user-002',sid:'S-1-5-21-100-200-300-1002'},
{id:'a5',name:'DEMO-WS-012',type:'计算机',domain:'alpha',desc:'工作站',risk:12,level:'低风险',status:'启用',group:'Workstations',mail:null,seen:null,guid:'demo-guid-device-002',sid:null},
{id:'a6',name:'demo.morgan',type:'用户',domain:'alpha',desc:'目录用户',risk:8,level:'低风险',status:'启用',group:'DEMO-Engineering',mail:'demo.morgan@example.test',seen:'2026-10-09 23:59:12 UTC',guid:'demo-guid-user-003',sid:'S-1-5-21-100-200-300-1003'},
{id:'a7',name:'demo.alex',type:'用户',domain:'beta',desc:'跨域同名对象 · 不同身份',risk:32,level:'中风险',status:'启用',group:'DEMO-Finance',mail:'demo.alex.beta@example.test',seen:'2026-10-09 23:57:45 UTC',guid:'demo-guid-beta-user-001',sid:'S-1-5-21-400-500-600-1001'},
{id:'a8',name:'DEMO-BETA-DC',type:'计算机',domain:'beta',desc:'域控制器',risk:15,level:'低风险',status:'启用',group:'Domain Controllers',mail:null,seen:'2026-10-09 23:59:30 UTC',guid:'demo-guid-beta-device-001',sid:'S-1-5-21-400-500-600-1101'}];
const EVENTS=[
{id:'e1',title:'特权身份出现异常目录访问',rule:'DEMO-IDENTITY-021',domain:'alpha',asset:'a1',level:'高危',type:'身份异常',time:'23:58:42',state:'待调查',evidence:'事件 4662：demo.alex 访问敏感目录对象。关联窗口 5 分钟；规则 v1.4.2。请结合授权记录核实访问目的。'},
{id:'e2',title:'服务身份从新设备发起认证',rule:'DEMO-AUTH-014',domain:'alpha',asset:'a4',level:'中危',type:'认证异常',time:'23:46:18',state:'调查中',evidence:'事件 4624：首次观察到服务身份与 DEMO-WS-012 的认证关系。缺少更早数据，需进一步核实。'},
{id:'e3',title:'敏感组成员关系发生变化',rule:'DEMO-GROUP-008',domain:'alpha',asset:'a3',level:'高危',type:'权限变更',time:'23:32:06',state:'待调查',evidence:'事件 4728：DEMO-Tier0 的成员快照出现变化。请核对前后成员列表与对应变更授权。'},
{id:'e4',title:'跨时间窗口的重复认证失败',rule:'DEMO-AUTH-003',domain:'beta',asset:'a7',level:'中危',type:'认证异常',time:'23:18:52',state:'待调查',evidence:'认证失败事件在 10 分钟窗口内达到阈值，随后出现登录成功。需核对来源设备与身份使用记录。'},
{id:'e5',title:'计算机账户属性变化',rule:'DEMO-ASSET-006',domain:'beta',asset:'a8',level:'低危',type:'资产变更',time:'22:54:31',state:'已关闭',evidence:'计算机账户属性与上次观测不同。事件已关闭，关联变更记录保留。'}];
const state={role:'operator',domain:'all',scenario:'normal',epoch:1,filters:{},tab:{},tasks:[],messagesRead:new Set(),events:structuredClone(EVENTS),domains:[{id:'alpha',diagnostic:'success'},{id:'beta',diagnostic:'stale'}],audits:[],sequence:1043,route:'overview',view:null,signedOut:false,drawer:null,mobile:false,roleGrant:{read:true,write:false},downloadRevoked:false,responseTarget:null,savedDomains:[]};
let pendingIntent=null,dialogReturnFocus=null,drawerReturnFocus=null,drawerReturnPath=null,toastTimer,routeEpoch=0;
const role=()=>{const base=ROLES[state.role],override=state.adminAccessOverrides?.[state.role];if(!override)return base;const ps=override.permissions||{};return {...base,domains:override.enabled===false?[]:override.domains,write:Object.entries(ps).some(([k,v])=>v&&/Run|Manage|Execute|Export|Operate/.test(k)),admin:!!ps.roleManage,permissions:ps};};
const permission=key=>{const ps=role().permissions;return ps?ps[key]===true:(ROLES[state.role].write||(/View$/.test(key)&&state.role==='viewer'));};
const domainAllowed=d=>!state.signedOut&&state.scenario!=='forbidden'&&(d==='platform'||(role().domains.includes(d)&&(state.domain==='all'||state.domain===d)));
const visibleAssets=()=>!permission('assetView')||['forbidden','empty'].includes(state.scenario)?[]:ASSETS.filter(a=>domainAllowed(a.domain));
const visibleEvents=()=>!permission('investigationView')||['forbidden','empty'].includes(state.scenario)?[]:state.events.filter(e=>domainAllowed(e.domain));
const canWrite=()=>!state.signedOut&&state.scenario!=='forbidden'&&role().write;
const canOperation=kind=>{if(!canWrite())return false;const required=({connection:['systemView','systemManage'],diagnostic:['systemView','systemManage'],directory:['systemView','systemManage'],detection:['detectionView','detectionRun','assetView'],response:['responseView','responseExecute','assetView'],investigation:['investigationView','responseExecute'],whitelist:['investigationView','ruleManage'],health:['systemView','taskManage'],task:['taskManage']})[kind]||[];return required.length>0&&required.every(permission);};
const selectedDomain=()=>state.domain==='all'?(role().domains[0]||null):state.domain;
const validScope=()=>!!selectedDomain()&&domainAllowed(selectedDomain());
const scopeLabel=()=>state.domain==='all'?'全部已授权域':DOMAINS[state.domain]||'无域授权';
function toast(text){clearTimeout(toastTimer);const el=$('#toast');el.textContent=text;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
function filterState(page){return state.filters[page]||(state.filters[page]={q:'',type:'all',level:'all'});}
function riskTag(v){return tag(v,(/高|失败|死信/.test(v)?'red':/中|待核对|陈旧/.test(v)?'amber':/低|成功|启用|已确认/.test(v)?'green':'blue'));}
function taskReadable(t){const key=t.kind==='response'||t.kind==='business-restore'?'responseView':t.kind==='export'?(t.exportType==='audit'?'auditView':t.exportType==='events'?'investigationView':'assetView'):/detect|recheck/.test(t.kind)?'detectionView':/sync|collect/.test(t.kind)?'assetView':/health|diagnostic|upgrade|deploy|install/.test(t.kind)?'systemView':null;return !key||permission(key);}
function visibleTasks(){return state.tasks.filter(t=>taskReadable(t)&&t.actor===state.role&&domainAllowed(t.domain)&&(state.showArchivedTasks||!t.archived));}
function audit(action,target,result='成功',scope=null){const task=state.tasks.find(t=>t.id===target),event=state.events.find(e=>e.id===target);const domain=scope||task?.domain||event?.domain||Object.keys(DOMAINS).find(d=>DOMAINS[d]===target)||'platform';state.audits.unshift({action,target,result,domain,actor:role().name,time:'2026-10-10 00:00:00 UTC'});}function visibleAudits(){if(!permission('auditView'))return [];return state.audits.filter(a=>domainAllowed(a.domain)&&(a.actor===role().name||role().admin));}
function pageHeader(page,actions=''){const t=TITLES[page];return `<div class="page-header"><div><div class="eyebrow">${t[0]}</div><h1 id="page-title" tabindex="-1">${t[1]}</h1><p class="subtitle">${t[2]}</p></div><div class="header-actions">${actions}</div></div>`;}
function metric(label,num,unit,foot,tone='',glyph='activity',spark=true){return `<article class="metric"><div class="metric-label">${icon(glyph)}${label}</div><div class="metric-number">${num}<span class="metric-unit">${unit}</span></div><div class="metric-foot"><span class="delta ${tone}">${foot}</span><span>当前范围</span></div>${spark?'<svg class="sparkline" viewBox="0 0 80 30" aria-hidden="true"><path d="M1 28L12 22 19 24 28 13 36 17 47 9 55 13 66 4 79 6" fill="none" stroke="#74a28c" stroke-width="1.5"/></svg>':''}</article>`;}
function assetDonut(items){const types=['用户','计算机','组'],colors=['#3a78ef','#84a7f5','#dddff4'];let offset=0;const circles=types.map((type,i)=>{const count=items.filter(a=>a.type===type).length;const amount=items.length?count/items.length*251.327:0;const out=`<circle cx="50" cy="50" r="40" fill="none" stroke="${colors[i]}" stroke-width="12" stroke-dasharray="${amount} 251.327" stroke-dashoffset="${-offset}" transform="rotate(-90 50 50)"/>`;offset+=amount;return out;}).join('');return `<div class="donut" role="img" aria-label="${types.map(t=>t+' '+items.filter(a=>a.type===t).length).join('，')}"><svg class="donut-ring" viewBox="0 0 100 100" aria-hidden="true">${circles}</svg><div class="donut-center"><strong>${items.length}</strong><span>可见资产</span></div></div>`;}
function note(text){return `<div class="note-strip">${icon('info')}<span>${text}</span></div>`;}
function empty(title,description,action='',glyph='search'){return `<div class="panel empty" data-testid="empty-state"><div class="empty-icon">${icon(glyph)}</div><h2>${title}</h2><p>${description}</p>${action}</div>`;}
function stateGuard(page){if(page==='admin'&&!state.view&&!role().admin)return empty('账户管理','查看并管理个人资料与登录保护。',link('个人资料','admin/profile','button primary'),'user');const perm=({connections:'systemView',assets:'assetView',detection:'detectionView',threats:'investigationView',response:'responseView',reports:'reportView'})[page];if(role().permissions&&perm&&!role().permissions[perm])return empty('当前角色没有此功能权限','请联系管理员核对功能授权。','','lock');if(state.scenario==='error')return empty('暂时无法读取数据','暂时无法完成请求，筛选条件已保留。请稍后重试。',btn('重新加载','retry-page','primary'),'refresh');if(state.scenario==='forbidden'||(!role().domains.length&&page!=='admin'&&page!=='work'))return empty('当前范围没有业务访问权限','平台管理身份不包含 AD 域访问权。列表、详情和导出均需显式域授权。',btn('查看权限说明','permission-info'),'lock');if(state.scenario==='empty'&&page!=='admin'&&page!=='response')return empty('当前范围暂无记录','这是当前授权范围内还没有记录。',btn('重新加载','retry-page','primary'),'layers');return '';}
function toolbar(page,{types=[],levels=[]}={}){const f=filterState(page);return `<div class="toolbar"><label class="search">${icon('search')}<input type="search" aria-label="搜索${TITLES[page][1]}" data-filter="q" data-page="${page}" placeholder="搜索名称、身份或关联 ID…" value="${escape(f.q)}"></label>${types.length?`<select class="filter" aria-label="对象类型" data-filter="type" data-page="${page}"><option value="all">全部类型</option>${types.map(t=>`<option ${f.type===t?'selected':''}>${t}</option>`).join('')}</select>`:''}${levels.length?`<select class="filter" aria-label="风险级别" data-filter="level" data-page="${page}"><option value="all">全部风险</option>${levels.map(t=>`<option ${f.level===t?'selected':''}>${t}</option>`).join('')}</select>`:''}${btn(icon('refresh')+'重置筛选','reset-filters','',`data-page="${page}"`)}<span class="toolbar-end">${icon('clock')} 观测窗口 · 2026-10-09 / UTC</span></div>`;}
function filterItems(items,page){const f=filterState(page);return items.filter(x=>(f.type==='all'||x.type===f.type)&&(f.level==='all'||x.level===f.level)&&(!f.q||Object.values(x).join(' ').toLowerCase().includes(f.q.toLowerCase())));}
function footer(count){return `<div class="table-footer"><span>共 ${count} 条记录 · 当前授权范围</span><div class="pagination"><button class="page-number" disabled aria-label="上一页">‹</button><button class="page-number current" aria-current="page" aria-label="第1页">1</button><button class="page-number" disabled aria-label="下一页">›</button></div></div>`;}
function eventTable(events){return `<div class="table-scroll" role="region" aria-label="威胁事件表" tabindex="0"><table><thead><tr><th>风险</th><th>事件名称 / 检测规则</th><th>关联身份</th><th>状态</th><th>发生时间 UTC</th><th></th></tr></thead><tbody>${events.map(e=>`<tr><td>${riskTag(e.level)}</td><td><button class="row-link" data-action="event-detail" data-id="${e.id}">${e.title}</button><span class="row-sub mono">${e.rule}</span></td><td>${escape(visibleAssets().find(a=>a.id===e.asset)?.name||'无资产读取权限')}<span class="row-sub">${DOMAINS[e.domain]}</span></td><td>${tag(e.state,e.state==='待调查'?'amber':e.state==='调查中'?'blue':'green')}</td><td class="mono">10-09 ${e.time}</td><td>${btn(icon('arrow'),'event-detail','subtle',`aria-label="查看事件 ${escape(e.title)}" data-id="${e.id}"`)}</td></tr>`).join('')}</tbody></table></div>`;}
function overview(){return soc.dashboard();}
function connections(){const ds=state.domains.filter(d=>domainAllowed(d.id)&&!d.archived);return pageHeader('connections',btn(icon('plus')+'添加域连接','add-domain','primary',canOperation('connection')?'':'disabled')+(state.domains.some(d=>domainAllowed(d.id)&&d.archived)?btn('恢复已移除连接','restore-domains','',canOperation('connection')?'':'disabled'):''))+`<div class="state-banner info">${icon('lock')}<span>连接诊断与目录读取使用不同用途授权。读取前请确认字段能力与操作账户用途。</span></div><div class="grid-equal">${ds.map(d=>`<section class="panel domain-card"><div class="domain-head"><div class="domain-glyph">${icon('connect')}</div><div><h2>${DOMAINS[d.id]}</h2><p class="panel-subtitle">域 · ${d.id==='alpha'?'主调查域':'对照域'}</p></div>${tag(d.diagnostic==='success'?'历史诊断通过':'观测已陈旧',d.diagnostic==='success'?'green':'amber')}</div><dl class="detail-grid"><div><dt>传输要求</dt><dd>${d.transport||'LDAPS'} · 严格证书校验</dd></div><div><dt>凭据来源</dt><dd>${d.account||'DEMO-OP-01'}</dd></div><div><dt>用途授权</dt><dd>单次连接诊断</dd></div><div><dt>目录能力</dt><dd>未启用</dd></div><div><dt>诊断时间</dt><dd>10-09 23:50 UTC</dd></div><div><dt>配置版本</dt><dd>v${d.version||3}</dd></div></dl><div class="domain-actions">${btn(icon('activity')+'连接诊断','diagnose','primary',`data-domain="${d.id}" ${canOperation('connection')?'':'disabled'}`)}${btn('目录用途授权','directory-auth','',`data-domain="${d.id}" ${canOperation('connection')?'':'disabled'}`)}${btn('编辑','edit-domain','',`data-domain="${d.id}" ${canOperation('connection')?'':'disabled'}`)}${btn('移除','delete-domain','',`data-domain="${d.id}" ${canOperation('connection')?'':'disabled'}`)}</div></section>`).join('')}</div>${state.savedDomains.filter(d=>d.actor===state.role).length?`<section class="panel"><div class="panel-head"><h2>已保存的域配置</h2>${tag('未获业务域授权','amber')}</div>${state.savedDomains.filter(d=>d.actor===state.role).map(d=>`<div class="coverage-row"><strong>${escape(d.name)}</strong><span class="muted">凭据未配置 · 不可诊断或读取</span>${tag('仅配置元数据','outline')}</div>`).join('')}</section><div class="page-note">保存配置不会自动授予业务域或凭据用途。</div>`:''}<section class="panel"><div class="panel-head"><h2>接入工作流程</h2></div><div class="pipeline"><a href="#/connections/accounts">登记操作账户</a><b>→</b><a href="#/connections/deployment">部署审计与采集器</a><b>→</b><a href="#/connections/collection">检查日志与流量</a><b>→</b><a href="#/assets/sync">同步目录资产</a></div></section>`;}
function assets(){const items=filterItems(visibleAssets(),'assets');return pageHeader('assets',`${btn(icon('download')+'导出资产','export-assets','',exportAllowed('assets')?'':'disabled')}${btn(icon('refresh')+'目录同步','sync-directory','primary',canOperation('detection')?'':'disabled')}`)+`<div class="tabs"><button class="tab active">资产目录</button><a class="tab" href="#/assets/permissions">权限关系</a><a class="tab" href="#/assets/trust">域信任</a></div><section class="panel"><div class="panel-head"><div><h2>已观测目录对象 <span class="tag outline">${visibleAssets().length}</span></h2><p class="panel-subtitle">观测批次 DEMO-BATCH-001 · 最后观测 2026-10-10 00:00 UTC</p></div>${tag('最新批次','blue')}</div>${toolbar('assets',{types:['用户','计算机','组'],levels:['高风险','中风险','低风险']})}${items.length?`<div class="table-scroll" role="region" aria-label="目录资产表" tabindex="0"><table><thead><tr><th>对象名称</th><th>类型</th><th>所属域</th><th>身份风险</th><th>状态</th><th>最后观测 UTC</th><th></th></tr></thead><tbody>${items.map(a=>`<tr><td><span class="type-icon">${icon(a.type==='用户'?'user':a.type==='组'?'group':'server')}</span><button class="row-link" data-action="asset-detail" data-id="${a.id}">${a.name}</button><span class="row-sub">${a.desc}</span></td><td>${a.type}</td><td>${DOMAINS[a.domain]}</td><td>${riskTag(a.level)} <span class="mono muted">${a.risk}</span></td><td>${tag(a.status,'green')}</td><td class="mono">${a.seen?a.seen.slice(5,16):'未观测'}</td><td>${btn(icon('chevron'),'asset-detail','subtle',`data-id="${a.id}" aria-label="查看资产 ${a.name}"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('没有符合筛选的资产','当前筛选没有匹配记录。你可以清除筛选，权限范围不会因此扩大。',btn('清除筛选','reset-filters','',`data-page="assets"`))}${footer(items.length)}</section>`;}
function detection(){return pageHeader('detection',btn(icon('plus')+'发起检测','new-detection','primary',canOperation('detection')?'':'disabled'))+`<div class="tabs"><button class="tab active">检测工作台</button><a class="tab" href="#/detection/rules">规则与版本</a><a class="tab" href="#/detection/templates">检测模板</a></div><div class="grid-3">${[['安全基线检测','账户策略、权限与审计配置','response','baseline'],['身份异常复查','围绕指定身份复查关联证据','user','identity'],['目录权限评估','观测关系及敏感组变更','layers','permissions']].map(([t,d,i,k])=>`<section class="panel template-card"><div class="type-icon">${icon(i)}</div><h2>${t}</h2><p>${d}。</p><div class="template-meta"><span>版本 v1.4.2</span><span>范围需确认</span></div>${tag('可按需执行','blue')}${btn('配置并开始 '+icon('arrow'),'new-detection','',`data-template="${k}" ${canOperation('detection')?'':'disabled'}`)}</section>`).join('')}</div><section class="panel"><div class="panel-head"><h2>最近检测结果</h2>${link('查看全部任务','work')}</div><div class="panel-body"><div class="result-links"><a href="#/detection/baseline"><strong>安全基线</strong><span>配置证据、检查结果与加固建议</span></a><a href="#/detection/vulnerabilities"><strong>漏洞与暴露面</strong><span>目标、检测依据与修复跟踪</span></a><a href="#/detection/passwords"><strong>凭据风险</strong><span>弱口令与泄露检查结果</span></a><a href="#/detection/behavior"><strong>行为检测</strong><span>身份会话与跨事件关联</span></a></div></div></section>`;}
function threats(){return soc.queuePage();}
function responseEffect(asset,target=state.responseTarget){return target?.effect||(asset?.type==='计算机'?'限制设备访问':asset?.type==='组'?'限制组权限变更':'限制账户访问');}
function response(){if(!permission('responseView')||!permission('assetView'))return empty('没有响应对象的读取权限','请联系管理员核对对象与响应访问范围。','','lock');const linked=state.responseTarget;const target=linked?visibleAssets().find(a=>a.id===linked.assetId):visibleAssets()[0];if(!target)return stateGuard('response')||empty('没有可响应的授权对象','请先确认当前角色具备所需域范围。','','lock');return pageHeader('response',`${btn(icon('response')+'发起响应确认','response-confirm','primary',canOperation('response')?'':'disabled')}`)+`<div class="response-layout"><section class="panel response-preview"><div class="inline"><div class="domain-glyph">${icon('response')}</div><div><h2>${responseEffect(target)}</h2><p class="panel-subtitle">${linked?.policyId?escape(linked.policyName)+' / '+linked.policyId+' / v'+linked.policyVersion:'人工响应 · 需逐次确认'}</p></div></div><div class="response-target"><div class="inline"><span class="type-icon">${icon('user')}</span><div><strong>${target.name}</strong><p class="panel-subtitle">${DOMAINS[target.domain]} · ${target.guid}</p></div>${riskTag(target.level)}</div></div><dl class="detail-grid"><div><dt>拟执行动作</dt><dd>${escape(responseEffect(target))}</dd></div><div><dt>目标数量</dt><dd>1 个明确对象</dd></div><div><dt>关联事件</dt><dd>${linked?.eventId?linked.eventId.toUpperCase():'独立响应（未关联事件）'}</dd></div><div><dt>目标版本</dt><dd>观测 v3</dd></div><div><dt>响应白名单</dt><dd>${business.isBlocked(target)?'命中保护名单':'未命中'}</dd></div></dl><div class="warning-box"><strong>影响与恢复边界</strong><br>该动作可能影响登录和服务访问。取消任务不会撤销已经发生的效果；结果未知时须核对，不能盲目重试。恢复需要独立授权与新任务。</div><div class="domain-actions">${btn('审阅影响并确认 '+icon('arrow'),'response-confirm','primary',canOperation('response')?'':'disabled')}${link('查看事件证据','threats')}</div></section><div class="stack"><section class="panel"><div class="panel-head"><h2>提交前核验</h2>${tag('执行前检查','blue')}</div><div class="panel-body"><div class="check-row"><span class="check-circle">✓</span><div>租户与域范围明确<br><small class="muted">demo-tenant-a / ${DOMAINS[target.domain]}</small></div></div><div class="check-row"><span class="check-circle">${canOperation('response')?'✓':'!'}</span><div>当前功能权限<br><small class="muted">${canOperation('response')?'允许响应':'只读角色，不允许提交'}</small></div></div><div class="check-row"><span class="check-circle">✓</span><div>目标版本已绑定<br><small class="muted">确认仅对本次目标与当前身份有效</small></div></div></div></section><section class="panel"><div class="panel-head"><h2>结果需要被核对</h2></div><div class="panel-body"><p class="subtitle">结果待核对时先查询原请求，不要重复发起动作。操作记录保留逐对象结果和恢复关联。</p>${link('打开任务中心 '+icon('arrow'),'work')}</div></section></div></div>`;}
function taskLabel(t){return ({queued:'排队中',running:'运行中',cancel_requested:'已请求取消',succeeded:'已完成',failed:'失败',unknown:'结果待核对',cancelled:'已取消',partial_failed:'部分失败'})[t.state]||t.state;}
function taskTone(t){return ({queued:'blue',running:'blue',cancel_requested:'amber',succeeded:'green',failed:'red',unknown:'amber',cancelled:'outline',partial_failed:'red'})[t.state]||'';}
function taskActions(t){let h=btn('详情','task-detail','subtle',`data-id="${t.id}"`);if(['queued','running'].includes(t.state)&&canOperation('task'))h+=btn('取消','cancel-task','subtle',`data-id="${t.id}"`);if(t.state==='unknown'&&t.epoch===state.epoch&&canOperation('task'))h+=btn('核对原结果','reconcile-task','subtle',`data-id="${t.id}"`);if(t.state==='failed'&&t.safeReplay&&canOperation('task'))h+=btn('新建恢复任务','recover-task','subtle',`data-id="${t.id}"`);if(['detection'].includes(t.kind)&&['succeeded','failed','cancelled','partial_failed'].includes(t.state)&&canOperation('task'))h+=btn(t.archived?'恢复记录':'归档记录','archive-task','subtle',`data-id="${t.id}"`);if(t.state==='succeeded'&&t.kind==='export')h+=btn(icon('download')+'下载','download-task','subtle',`data-id="${t.id}" ${exportAllowed(t.exportType)?'':'disabled'}`);return h;}
function taskTable(items){return items.length?`<div class="table-scroll" role="region" aria-label="演示任务表" tabindex="0"><table><thead><tr><th>任务 / 关联 ID</th><th>作用域</th><th>状态</th><th>进度</th><th>实际尝试</th><th>操作</th></tr></thead><tbody>${items.map(t=>`<tr data-task-id="${t.id}"><td><button class="row-link" data-action="task-detail" data-id="${t.id}">${t.title}</button><span class="row-sub mono">${t.id}${t.parent?' / 源 '+t.parent:''}</span></td><td>${DOMAINS[t.domain]||'平台范围'}</td><td>${tag(taskLabel(t),taskTone(t))}</td><td><span class="mono">${t.state==='unknown'?'未确认':t.progress+'%'}</span><progress aria-label="${escape(t.title)}进度" max="100" value="${t.progress}"></progress></td><td class="mono">${t.attempt} / ${t.safeReplay?3:1}</td><td>${taskActions(t)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚未提交任务','从域诊断、检测或导出发起任务，可在此跟踪进度与结果。',link('开始一次检测 '+icon('arrow'),'detection','button primary'),'work');}
function reports(){const exports=visibleTasks().filter(t=>t.kind==='export');return pageHeader('reports',btn(icon('plus')+'创建导出任务','export-assets','primary',exportAllowed('assets')?'':'disabled'))+`<div class="grid-3">${[['身份安全评估','资产、风险与当前调查范围','asset'],['威胁调查摘要','事件、证据和关联任务','threat'],['操作审计清单','平台操作记录','report']].map(([name,desc,i],idx)=>`<section class="panel template-card"><div class="type-icon">${icon(i)}</div><h2>${name}</h2><p>${desc}。</p><div class="template-meta"><span>CSV · 数据导出</span><span>当前权限</span></div>${btn('创建导出任务 '+icon('arrow'),['export-assets','export-events','export-audit'][idx],'',exportAllowed(['assets','events','audit'][idx])?'':'disabled')}</section>`).join('')}</div><section class="panel"><div class="panel-head"><div><h2>导出历史</h2><p class="panel-subtitle">任务成功与当前可下载条件分别核验</p></div>${btn('撤销当前下载授权','revoke-download','',exports.length?'':'disabled')}</div>${taskTable(exports)}</section>`;}
function work(){const tab=state.tab.work||'tasks';return pageHeader('work',btn(icon('plus')+'新建健康检查','health-task','primary',canOperation('health')?'':'disabled'))+`<div class="tabs"><button class="tab ${tab==='tasks'?'active':''}" data-action="work-tab" data-tab="tasks">后台任务 <span class="tag outline">${visibleTasks().length}</span></button><button class="tab ${tab==='messages'?'active':''}" data-action="work-tab" data-tab="messages">消息中心</button><a class="tab" href="#/work/schedules">周期计划</a></div>${tab==='tasks'?`<section class="panel"><div class="panel-head"><div><h2>后台任务</h2><p class="panel-subtitle">当前角色 ${role().name} · ${scopeLabel()}</p></div></div>${state.tasks.some(t=>t.archived&&t.actor===state.role)?btn(state.showArchivedTasks?'隐藏归档':'显示归档','show-archived-tasks','subtle'):''}<div id="task-table-region">${taskTable(visibleTasks())}</div>${note('取消等待与取消任务不同；单次诊断和响应没有通用恢复入口。切换身份不会显示其他身份的任务。')}</section>`:`<section class="panel"><div class="panel-head"><h2>运行与调查消息</h2>${tag(visibleEvents().filter(e=>!state.messagesRead.has(e.id)).length+' 条未读','blue')}</div>${visibleEvents().filter(e=>!state.archivedMessages?.has(e.id)).map(e=>`<div class="coverage-row"><div class="mini-bullet">${icon('bell')}</div><div><strong>${e.title}</strong><div class="coverage-description">${DOMAINS[e.domain]} · 已读不等于事件处理完成</div></div>${btn(state.messagesRead.has(e.id)?'已读':'设为已读','mark-read','subtle',`data-id="${e.id}" ${state.messagesRead.has(e.id)?'disabled':''}`)}${btn('定位','event-detail','subtle',`data-id="${e.id}"`)}</div>`).join('')}</section>`}`;}
function admin(){const tab=state.tab.admin||'access';return pageHeader('admin',`${tag('demo-tenant-a','outline')}`)+`<div class="tabs"><button class="tab ${tab==='access'?'active':''}" data-action="admin-tab" data-tab="access">角色与域权限</button><button class="tab ${tab==='audit'?'active':''}" data-action="admin-tab" data-tab="audit">操作审计</button><button class="tab ${tab==='system'?'active':''}" data-action="admin-tab" data-tab="system">平台健康</button></div>${tab==='audit'?`<section class="panel"><div class="panel-head"><h2>操作记录</h2></div>${visibleAudits().length?`<div class="table-scroll"><table><thead><tr><th>操作</th><th>对象</th><th>结果</th><th>操作角色</th></tr></thead><tbody>${visibleAudits().map(a=>`<tr><td>${escape(a.action)}</td><td>${escape(a.target)}</td><td>${tag(a.result,'blue')}</td><td>${escape(a.actor)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚无操作记录','提交任务、确认响应或修改权限后，会留下相应操作记录。','','report')}</section>`:tab==='system'?systemView():`<div class="grid-2"><section class="panel"><div class="role-summary"><div class="avatar">CR</div><div><h2>自定义响应角色</h2><p class="panel-subtitle">角色模板 · alpha 业务范围</p></div>${tag('显式授权','blue')}</div><div class="table-scroll"><table><thead><tr><th>功能范围</th><th>读取</th><th>写入</th><th>权限说明</th></tr></thead><tbody><tr><td>威胁事件</td><td>${tag('允许','green')}</td><td>${tag('默认拒绝','outline')}</td><td>调查与响应分权</td></tr><tr><td>响应处置</td><td><label class="switch"><input type="checkbox" id="grant-read" ${state.roleGrant.read?'checked':''} ${role().admin?'':'disabled'} aria-label="响应读取权限">读取</label></td><td><label class="switch"><input type="checkbox" id="grant-write" ${state.roleGrant.write?'checked':''} ${role().admin?'':'disabled'} aria-label="响应写入权限">写入</label></td><td>写权限依赖读权限</td></tr><tr><td>平台管理</td><td>${tag('默认拒绝','outline')}</td><td>${tag('默认拒绝','outline')}</td><td>禁止角色自我提权</td></tr></tbody></table></div><div class="panel-body"><div class="response-target"><strong>资源组 DEMO-Response</strong><p class="subtitle">显式域范围：alpha.example.test<br>没有通配授权；凭据用途需要另外登记。</p></div>${btn('审阅权限变更','save-grants','primary',role().admin?'':'disabled')}</div></section><section class="panel"><div class="panel-head"><h2>当前身份</h2></div><div class="panel-body"><dl class="detail-grid"><div><dt>工作角色</dt><dd>${role().name}</dd></div><div><dt>功能写入</dt><dd>${role().write?'允许':'只读'}</dd></div><div><dt>显式域数</dt><dd>${role().domains.length} 个</dd></div><div><dt>会话授权版本</dt><dd>${state.epoch}</dd></div></dl><div class="warning-box">功能权限与域范围分别管理。更改角色授权后，受影响的会话需要重新验证。</div></div></section></div>`}`;}
function systemView(){return business.renderPage(business.pages.find(p=>p.id==='admin/system'));}
function renderNavigation(page,activeCount){const item=key=>{const [id,title,glyph]=NAV.find(x=>x[0]===key);return `<a class="nav-link ${id===page?'active':''}" href="#/${id}" ${id===page?'aria-current="page"':''}>${icon(glyph)}<span>${title}</span>${id==='threats'&&visibleEvents().length?`<span class="nav-count">${visibleEvents().filter(e=>e.state!=='已关闭').length}</span>`:id==='work'&&activeCount?`<span class="nav-count">${activeCount}</span>`:''}</a>`;};return `<div class="nav-label">安全运营</div><nav>${['overview','threats','assets','response','work','reports'].map(item).join('')}</nav><details class="nav-management" ${['connections','detection','admin'].includes(page)?'open':''}><summary>${icon('settings')}<span>配置与管理</span>${icon('down')}</summary><nav>${['detection','connections','admin'].map(item).join('')}</nav></details>`;}
function render(){const savedFocus=captureFocus();const page=Object.hasOwn(TITLES,state.route)?state.route:'overview';const guard=state.signedOut?empty('工作空间已锁定','请完成账户验证后继续。',btn('返回登录','resume-session','primary'),'lock'):stateGuard(page);const subpage=business.current();const activeCount=visibleTasks().filter(t=>['queued','running','cancel_requested'].includes(t.state)).length;$('#app').innerHTML=`<div class="shell"><aside class="sidebar ${state.mobile?'open':''}" aria-label="产品导航"><a class="brand" href="#/overview"><span class="brandmark">A</span><span>${escape(state.systemName||'ADTR')}<small>IDENTITY SECURITY</small></span></a>${renderNavigation(page,activeCount)}<div class="sidebar-bottom"><div class="env-status"><strong><span class="status-dot"></span>演示环境</strong><br>数据仅用于演示</div><div class="version">ADTR / 2026.10</div></div></aside><div class="workspace"><header class="topbar"><div class="top-left"><button class="icon-button mobile-menu" data-action="mobile-menu" aria-label="切换导航菜单">${icon('menu')}</button><span class="breadcrumb">工作空间 <span class="muted">/</span> <b>${subpage?.title||TITLES[page][1]}</b></span><span class="demo-pill">合成演示数据</span></div><div class="top-right">${btn('演示环境','demo-settings','subtle')}<span class="separator"></span><label class="inline">${icon('globe')}<select class="toolbar-select" id="domain" aria-label="授权域范围"><option value="all">全部已授权域</option>${role().domains.map(d=>`<option value="${d}" ${state.domain===d?'selected':''}>${DOMAINS[d]}</option>`).join('')}</select></label><button class="icon-button" data-action="messages" aria-label="消息中心">${icon('bell')}</button><span class="separator"></span><span class="avatar">${escape(state.profileAvatars?.[state.role]?.initial||role().initial)}</span><span class="profile-label">${role().name}</span></div></header><main id="main" class="main ${['overview','threats'].includes(page)&&(!state.view||state.investigationId)?'soc-main':''}" tabindex="-1">${state.scenario==='stale'?`<div class="state-banner">${icon('clock')}当前为陈旧观测场景。最后确认时间：2026-10-09 20:00 UTC；不代表当前在线。</div>`:''}${state.signedOut||state.investigationId?'':business.subnav(page)}${guard?pageHeader(page)+guard:state.investigationId?soc.investigation():subpage?business.renderPage(subpage):({overview,connections,assets,detection,threats,response,reports,work,admin}[page])()}<footer class="bottom-footer"><span>ADTR · Identity Security</span><span>UTC · 2026-10-10</span></footer></main></div></div>`;if(state.drawer&&!guard)renderDrawer();updateTaskRegions();restoreFocus(savedFocus);}
function setRoute(path,replace=false){const hash='#/'+path;if(replace)history.replaceState(null,'',hash);else if(location.hash!==hash)history.pushState(null,'',hash);readRoute();}
function readRoute(){routeEpoch++;const parts=location.hash.replace(/^#\/?/,'').split('/');state.route=Object.hasOwn(TITLES,parts[0])?parts[0]:'overview';const entity=['asset','event','task'].includes(parts[1]);state.investigationId=parts[0]==='threats'&&parts[1]==='investigation'?(parts[2]||null):null;state.view=!entity&&parts[1]?parts[1]:null;state.drawer=entity&&parts.length>=3?{type:parts[1],id:parts[2]}:null;state.mobile=false;closeDialog();document.body.classList.remove('overlay-open');render();if(state.drawer){queueMicrotask(()=>$('.drawer-head h2')?.focus());}else{$('#page-title')?.focus({preventScroll:true});}}
function openDetail(type,id){drawerReturnFocus=document.activeElement;drawerReturnPath=state.investigationId?'threats/investigation/'+state.investigationId:[state.route,state.view].filter(Boolean).join('/');setRoute(`${state.route}/${type}/${id}`);}
function closeDrawer(){const prev=drawerReturnFocus;state.drawer=null;setRoute(drawerReturnPath||state.route,true);drawerReturnPath=null;if(prev?.dataset?.id){const next=$(`[data-id="${CSS.escape(prev.dataset.id)}"][data-action="${CSS.escape(prev.dataset.action)}"]`);next?.focus();}else $('#page-title')?.focus({preventScroll:true});}
function assetDetail(a){const es=visibleEvents().filter(e=>e.asset===a.id);return {title:a.name,eyebrow:'DIRECTORY OBJECT / '+a.type,body:`<div class="inline">${riskTag(a.level)}${tag(a.status,'green')}${tag('目录对象','outline')}</div><dl class="detail-grid"><div><dt>所属域</dt><dd>${DOMAINS[a.domain]}</dd></div><div><dt>对象类型</dt><dd>${a.type}</dd></div><div><dt>对象 GUID</dt><dd class="mono">${a.guid}</dd></div><div><dt>SID</dt><dd class="mono">${a.sid||'未观测'}</dd></div><div><dt>电子邮箱</dt><dd>${a.mail||'未采集 / 不适用'}</dd></div><div><dt>最后观测</dt><dd>${a.seen||'未观测'}</dd></div></dl><div class="drawer-section"><h3>身份与权限关系</h3><div class="relationship"><div class="relation-node">${icon('user')}${a.name}</div><div class="relation-line"></div><div class="relation-branches"><span class="relation-node">${icon('group')}${a.group}</span></div><small>当前关系：此对象属于 ${a.group}；</small></div></div><div class="drawer-section"><h3>关联调查证据</h3>${es.length?es.map(e=>`<div class="mini-row"><div class="mini-content"><button class="row-link" data-action="event-detail" data-id="${e.id}">${e.title}</button><span>${e.rule} · 10-09 ${e.time} UTC</span></div>${riskTag(e.level)}</div>`).join(''):'<p class="subtitle">当前观测窗口没有关联事件。</p>'}</div><div class="drawer-section"><h3>观测时间线</h3><div class="timeline"><div class="timeline-item"><small>2026-10-10 00:00 UTC</small><p>DEMO-BATCH-001 读取支持的字段，缺失值原样保留。</p></div><div class="timeline-item"><small>2026-10-09 23:58 UTC</small><p>更新关系快照和身份风险评分。</p></div></div></div>`,footer:link('查看威胁事件 '+icon('arrow'),'threats','button primary')};}
function eventDetail(e){return {title:e.title,eyebrow:'THREAT INVESTIGATION / '+e.id.toUpperCase(),body:`<div class="inline">${riskTag(e.level)}${tag(e.state,'blue')}${tag('事件证据','outline')}</div><dl class="detail-grid"><div><dt>所属域</dt><dd>${DOMAINS[e.domain]}</dd></div><div><dt>规则版本</dt><dd>${e.rule} / v1.4.2</dd></div><div><dt>关联身份</dt><dd><button class="row-link" data-action="asset-detail" data-id="${e.asset}">${visibleAssets().find(a=>a.id===e.asset)?.name||'无资产读取权限'}</button></dd></div><div><dt>发生时间</dt><dd>2026-10-09 ${e.time} UTC</dd></div></dl><div class="drawer-section"><h3>检测原因与证据</h3><p class="subtitle">${e.evidence}</p><div class="evidence">SOURCE: DEMO-BATCH-001\nEVENT: ${e.rule}\nDOMAIN: ${DOMAINS[e.domain]}\nOBSERVED: 2026-10-09T${e.time}Z</div></div><div class="warning-box">关联不代表因果。请核实目标、范围与证据后，再进入单独的响应确认。关闭事件不会自动执行阻断。</div>`,footer:`${btn('展开调查 '+icon('arrow'),'soc-open','primary',`data-id="${e.id}"`)}${btn('加入检测白名单','event-whitelist','',`data-id="${e.id}" ${canOperation('whitelist')?'':'disabled'}`)}${btn('标为调查中','event-investigate','',`data-id="${e.id}" ${canOperation('investigation')?'':'disabled'}`)}${btn('关闭事件','event-close','',`data-id="${e.id}" ${canOperation('investigation')?'':'disabled'}`)}${btn('查看响应方案 '+icon('arrow'),'event-response','primary',`data-id="${e.id}" ${canOperation('response')?'':'disabled'}`)}`};}
function taskDetail(t){return {title:t.title,eyebrow:'TASK / '+t.id,body:`<div class="inline">${tag(taskLabel(t),taskTone(t))}${tag('任务','outline')}</div><dl class="detail-grid"><div><dt>目标域</dt><dd>${DOMAINS[t.domain]||'平台范围'}</dd></div><div><dt>提交角色</dt><dd>${ROLES[t.actor].name}</dd></div>${t.template?`<div><dt>固定模板 ID / 版本</dt><dd>${t.template.id} / v${t.template.version}</dd></div>`:''}<div><dt>实际尝试 / 上限</dt><dd>${t.attempt} / ${t.safeReplay?3:1}</dd></div><div><dt>授权版本</dt><dd>v${t.epoch}</dd></div><div><dt>父任务</dt><dd>${t.parent||'无'}</dd></div>${t.target?`<div><dt>精确响应对象</dt><dd>${t.target.name} / ${t.target.assetId}</dd></div><div><dt>关联事件 / 对象版本</dt><dd>${t.target.eventId||'独立响应'} / v${t.target.version}</dd></div>${t.target.effect?`<div><dt>响应动作</dt><dd>${escape(t.target.effect)}</dd></div>`:''}${t.target.policyId?`<div><dt>策略与版本</dt><dd>${escape(t.target.policyName)} / ${t.target.policyId} / v${t.target.policyVersion}</dd></div>`:''}`:''}<div><dt>结果确认</dt><dd>${t.state==='unknown'?'未确认，禁止重放':t.state==='cancelled'?'执行结束已确认':'以状态时间线为准'}</dd></div></dl>${t.kind==='detection'&&t.state==='succeeded'?`<div class="drawer-section"><h3>检测结果</h3><div class="info-row"><span>固定模板</span><strong>${escape(t.template?`${t.template.name} / ${t.template.id} / v${t.template.version}`:'未指定模板')}</strong></div><div class="info-row"><span>目录权限配置</span>${tag('需复核','amber')}</div><div class="info-row"><span>审计配置示例</span>${tag('通过','green')}</div><div class="info-row"><span>未支持的源字段</span>${tag('未检查','outline')}</div><p class="subtitle">检查结果对应本次冻结的范围和版本；修复后可发起复查。</p>${link('查看相关事件','threats')}</div>`:''}<div class="drawer-section"><h3>执行时间线</h3><div class="timeline">${t.events.map(v=>`<div class="timeline-item"><small>${v.time}</small><p>${escape(v.text)}</p></div>`).join('')}</div></div>${t.state==='partial_failed'?`<div class="response-target"><strong>逐对象结果</strong><p class="subtitle">${(t.objectResults||[]).map(o=>`${escape(o.name)} / ${o.id}：${escape(o.state)}`).join('<br>')}</p></div><div class="warning-box">部分对象已完成，不能整批重试。请先核对每个失败或未知对象。</div>`:''}${t.state==='failed'&&!t.safeReplay?'<div class="warning-box">此操作仅尝试一次。请修复原因后从对应业务入口重新核对目标。</div>':''}${t.error?`<div class="state-banner red">${escape(t.error)}</div>`:''}`,footer:taskActions(t)};}
function renderDrawer(){const d=state.drawer;let content;if(d.type==='asset'){const a=visibleAssets().find(a=>a.id===d.id);if(a)content=assetDetail(a);}if(d.type==='event'){const e=visibleEvents().find(e=>e.id===d.id);if(e)content=eventDetail(e);}if(d.type==='task'){const t=visibleTasks().find(t=>t.id===d.id);if(t)content=taskDetail(t);}if(!content)content={title:'内容不可用或无访问权限',eyebrow:'ACCESS RESTRICTED',body:'<p class="subtitle">当前身份无法读取此对象。未显示任何旧内容、名称或其他私有信息。</p>',footer:''};const el=document.createElement('div');el.className='drawer-overlay';el.innerHTML=`<section class="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><header class="drawer-head"><div><div class="eyebrow">${content.eyebrow}</div><h2 id="drawer-title" tabindex="-1">${content.title}</h2></div><button class="icon-button" data-action="close-drawer" aria-label="关闭详情">${icon('close')}</button></header><div class="drawer-body">${content.body}</div><footer class="drawer-footer">${btn(drawerReturnPath?.includes('/investigation/')?'返回调查':'返回列表','close-drawer')}${content.footer}</footer></section>`;$('#app').append(el);const shell=$('.shell');if(shell)shell.inert=true;document.body.classList.add('overlay-open');}
function openDialog(title,body,footer='',onConfirm=null){closeDialog();dialogReturnFocus=document.activeElement;const d=$('#dialog');d.innerHTML=`<header class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="close-dialog" aria-label="关闭弹窗">${icon('close')}</button></header><div class="dialog-body">${body}</div><footer class="dialog-footer">${btn('取消','close-dialog')}${footer}</footer>`;d._confirm=onConfirm;d.showModal();queueMicrotask(()=>{if(!d.open)return;$('.dialog-head [data-action="close-dialog"]',d)?.focus({preventScroll:true});d.scrollTop=0;const content=$('.dialog-body',d);if(content)content.scrollTop=0;});}
function closeDialog(){const d=$('#dialog');if(d.open)d.close();d._confirm=null;pendingIntent=null;}
$('#dialog').addEventListener('close',()=>{const el=dialogReturnFocus;if(el?.isConnected)el.focus();else $('#page-title')?.focus({preventScroll:true});pendingIntent=null;});
function pendingResponse(target){return state.tasks.find(t=>t.kind==='response'&&t.actor===state.role&&t.domain===target.domain&&t.target&&['queued','running','cancel_requested','unknown'].includes(t.state)&&(t.target.guid&&target.guid?t.target.guid===target.guid:t.target.assetId===target.assetId)&&t.target.effect===target.effect);}
function showPendingResponse(t){openDialog('已有响应需要核对',`<p>同一对象的相同响应已有未结束或未确认的请求。请先查看原任务，不要重复提交。</p><div class="response-target"><div class="info-row"><span>原任务</span><strong>${escape(t.id)}</strong></div><div class="info-row"><span>目标对象</span><strong>${escape(t.target.name)} / ${escape(t.target.assetId)}</strong></div><div class="info-row"><span>响应动作</span><strong>${escape(t.target.effect)}</strong></div><div class="info-row"><span>当前状态</span><strong>${taskLabel(t)}</strong></div></div>`,btn('查看原任务','task-detail','primary',`data-id="${t.id}"`));}
function confirmation(kind,title,extra='',templateId='baseline'){const key=({response:'responseExecute',detection:'detectionRun',diagnostic:'systemManage',health:'taskManage'})[kind];if(!canOperation(kind)){toast('当前角色没有此操作权限。');return;}if(!canOperation(kind)||!validScope()&&kind!=='health'){toast('当前角色或域范围不允许提交。');return;}const targetDomain=kind==='health'?'platform':selectedDomain();const responseAsset=kind==='response'?(state.responseTarget?visibleAssets().find(a=>a.id===state.responseTarget.assetId):visibleAssets()[0]):null;if(kind==='response'&&!responseAsset){toast('原响应目标已不可见，请重新从事件选择。');return;}if(kind==='response'&&!business.policyValid({...state.responseTarget,domain:responseAsset.domain})){toast('响应策略已变化或停用，请重新选择。');return;}if(kind==='response'&&business.isBlocked(responseAsset)){toast('目标命中阻断白名单，请先核对例外保护。');return;}if(kind==='response'){const pending=pendingResponse({assetId:responseAsset.id,guid:responseAsset.guid,domain:responseAsset.domain,effect:responseEffect(responseAsset)});if(pending){showPendingResponse(pending);return;}}const intent={kind,domain:responseAsset?.domain||targetDomain,epoch:state.epoch,role:state.role,scenario:state.scenario,returnTo:kind==='response'&&state.investigationId?'threats/investigation/'+state.investigationId:null,id:'intent-'+(++state.sequence),used:false,target:responseAsset?Object.freeze({assetId:responseAsset.id,name:responseAsset.name,guid:responseAsset.guid,domain:responseAsset.domain,version:3,eventId:state.responseTarget?.eventId||null,effect:responseEffect(responseAsset),policyId:state.responseTarget?.policyId||null,policyName:state.responseTarget?.policyName||null,policyVersion:state.responseTarget?.policyVersion||null}):null};const label=DOMAINS[intent.domain]||'平台范围';let body=`<p>请核对以下范围、目标与执行选项。</p><div class="response-target"><div class="info-row"><span>目标范围</span><strong>${label}</strong></div><div class="info-row"><span>操作角色</span><strong>${role().name}</strong></div><div class="info-row"><span>授权版本</span><strong>${state.epoch}</strong></div>${extra}${intent.target?`<div class="info-row"><span>精确对象</span><strong>${intent.target.name} / ${intent.target.assetId}</strong></div><div class="info-row"><span>对象 GUID / 版本</span><strong>${intent.target.guid} / v${intent.target.version}</strong></div><div class="info-row"><span>关联事件</span><strong>${intent.target.eventId||'独立响应'}</strong></div><div class="info-row"><span>响应动作</span><strong>${escape(intent.target.effect)}</strong></div>${intent.target.policyId?`<div class="info-row"><span>策略 / 版本</span><strong>${escape(intent.target.policyName)} / ${intent.target.policyId} / v${intent.target.policyVersion}</strong></div>`:''}`:''}</div>`;
if(kind==='response')body+=`<div class="warning-box">此动作可能影响登录与服务。取消不能撤销已发生的效果；未知结果不得盲目重试。</div><label class="check-label"><input type="checkbox" id="confirm-impact">我已核实目标、影响与恢复限制</label><label class="check-label"><input type="checkbox" id="confirm-demo">已确认本次操作身份</label>`;
if(kind==='detection')body+=`<label class="form-field"><span>检测模板</span><select id="detect-template">${Object.values(TEMPLATES).map(t=>`<option value="${t.id}" ${t.id===templateId?'selected':''}>${t.name} · v${t.version}</option>`).join('')}</select></label>`;
body+='<div id="confirm-error" class="error-inline" role="alert"></div>';
openDialog(title,body,btn('确认提交任务','confirm-intent',kind==='response'?'danger':'primary'),()=>{if(intent.used)return;if(intent.epoch!==state.epoch||intent.role!==state.role||!canOperation(kind)||!domainAllowed(intent.domain)){closeDialog();toast('授权或目标范围已变化，请重新核验。');return;}if(kind==='response'&&(!$('#confirm-impact')?.checked||!$('#confirm-demo')?.checked)){$('#confirm-error').textContent='请先核实影响，并确认本次操作身份。';$('#confirm-impact').focus();return;}if(intent.target&&!visibleAssets().some(a=>a.id===intent.target.assetId&&a.guid===intent.target.guid&&a.domain===intent.target.domain&&domainAllowed(a.domain))){closeDialog();toast('目标快照已不可用，原确认失效。');return;}if(kind==='response'&&!business.policyValid(intent.target)){closeDialog();toast('策略已变化或停用，确认已失效。');return;}if(kind==='response'&&business.isBlocked(responseAsset)){closeDialog();toast('目标现已命中阻断白名单，提交已拒绝。');return;}if(kind==='response'){const pending=pendingResponse(intent.target);if(pending){showPendingResponse(pending);return;}}if(kind==='detection'){const selected=TEMPLATES[$('#detect-template')?.value];if(!selected){toast('未知检测模板，拒绝提交。');return;}intent.template=Object.freeze({...selected});intent.targets=Object.freeze(visibleAssets().filter(a=>a.domain===intent.domain).slice(0,3).map(a=>Object.freeze({id:a.id,name:a.name,guid:a.guid,domain:a.domain})));}intent.used=true;createTask(intent,kind==='detection'?intent.template.name+' v'+intent.template.version+' 检测':kind==='response'?intent.target.effect+' · '+intent.target.name:title);closeDialog();setRoute(intent.returnTo||'work');toast(intent.returnTo?'响应已提交，执行结果将显示在活动与响应中。':'已创建一条任务，可在任务中心查看。');});pendingIntent=intent;}
function createTask(intent,title,parent=null){const existing=state.tasks.find(t=>t.intentId===intent.id);if(existing)return existing;const kind=intent.kind;const task={id:'DEMO-TASK-'+(++state.sequence),intentId:intent.id,kind,title:title.replace(/确认|提交/g,''),domain:intent.domain,actor:intent.role,epoch:intent.epoch,state:'queued',progress:0,attempt:0,safeReplay:['detection','export','health'].includes(kind),target:intent.target||null,template:intent.template||null,targets:intent.targets||null,exportType:intent.exportType||intent.dataSnapshot?.type||null,parent,scenario:intent.scenario,created:Date.now(),events:[{time:'00:00:00 UTC',text:'请求已记录，等待执行。'}],error:null,data:kind==='export'?structuredClone(intent.dataSnapshot||snapshotExport(intent.exportType||'assets',intent.domain)):null};state.tasks.unshift(task);audit('创建任务',task.id);return task;}
function snapshotExport(type,domain){if(type==='events')return {type,rows:visibleEvents().filter(e=>e.domain===domain).map(e=>['SYNTHETIC',e.id,e.title,DOMAINS[e.domain],e.state]),headers:['classification','id','event','domain','state']};if(type==='audit')return {type,rows:visibleAudits().filter(a=>a.domain===domain).map(a=>['SYNTHETIC',a.action,a.target,a.result]),headers:['classification','action','target','result']};return {type,rows:visibleAssets().filter(a=>a.domain===domain).map(a=>['SYNTHETIC',a.id,a.name,a.type,DOMAINS[a.domain],a.sid||'未观测']),headers:['classification','id','name','type','domain','sid']};}
function exportAllowed(type){return !state.signedOut&&state.scenario!=='forbidden'&&(type==='audit'?permission('auditView')&&permission('auditExport'):type==='events'?permission('investigationView')&&permission('reportExport'):permission('assetView')&&permission('assetExport'));}
function exportDialog(type){if(!exportAllowed(type)||!validScope()){toast('当前身份没有此范围的导出权限。');return;}const domain=selectedDomain();const data=snapshotExport(type,domain);const intent={id:'intent-'+(++state.sequence),kind:'export',exportType:type,dataSnapshot:structuredClone(data),domain,role:state.role,epoch:state.epoch,scenario:state.scenario,used:false};openDialog('创建导出',`<p>导出包含下列范围和字段，生成 CSV 文件。</p><div class="response-target"><div class="info-row"><span>导出域</span><strong>${DOMAINS[domain]}</strong></div><div class="info-row"><span>当前行数</span><strong>${data.rows.length}</strong></div><div class="info-row"><span>字段白名单</span><strong>${data.headers.join(', ')}</strong></div></div><p>下载时重新核验当前角色、授权版本与域范围；离开页面可从导出历史找回。</p>`,btn('创建导出任务','confirm-intent','primary'),()=>{if(intent.used)return;if(intent.epoch!==state.epoch||intent.role!==state.role||!domainAllowed(domain)||!exportAllowed(type)){closeDialog();toast('权限变化，原确认已失效。');return;}intent.used=true;createTask(intent,'合成 '+(type==='events'?'事件证据':type==='audit'?'操作审计':'目录资产')+'导出');closeDialog();setRoute('reports');toast('导出任务已记录，完成后可下载 CSV。');});pendingIntent=intent;}
function addDomain(){if(!canOperation('connection'))return;const epoch=state.epoch;openDialog('添加域连接配置',`<p>添加域后，请配置账户引用并执行连接诊断。使用保留域 example.test 演示配置。</p><label class="form-field"><span>域名称</span><input id="demo-domain-name" value="sandbox.example.test" maxlength="80" required><small>使用 .example.test 后缀的演示域。</small></label><label class="form-field"><span>凭据来源</span><select><option>未配置 · 稍后单独授权用途</option></select></label><label class="form-field"><span>传输</span><select><option>LDAPS · 验证证书</option></select></label><div id="domain-error" class="error-inline" role="alert"></div>`,btn('保存配置','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!canOperation('connection')){closeDialog();toast('权限变化，配置未保存。');return;}const val=$('#demo-domain-name').value.trim().toLowerCase();if(!/^[a-z][a-z0-9-]{0,30}\.example\.test$/.test(val)){$('#domain-error').textContent='请使用 label.example.test 形式的保留合成域。';$('#demo-domain-name').focus();return;}if(state.savedDomains.some(d=>d.name===val&&d.actor===state.role)){$('#domain-error').textContent='当前角色已保存同名配置。';return;}state.savedDomains.push({name:val,actor:state.role});audit('保存域配置',val);closeDialog();render();toast('配置已保存。请继续配置账户引用与用途授权。');});}
function editDomain(id){const d=state.domains.find(d=>d.id===id&&domainAllowed(id));if(!d||!canOperation('connection'))return;const epoch=state.epoch;openDialog('编辑域连接',`<div class="response-target">${DOMAINS[id]}</div><label class="form-field"><span>传输</span><select id="domain-transport"><option>LDAPS</option></select></label><label class="form-field"><span>账户引用</span><select id="domain-account"><option>DEMO-OP-01</option><option>DEMO-OP-02</option></select></label><p>证书校验保持开启，账户用途需另行授权。</p>`,btn('保存连接配置','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!domainAllowed(id)||!canOperation('connection')){closeDialog();return;}d.transport=$('#domain-transport').value;d.account=$('#domain-account').value;d.version=(d.version||3)+1;audit('编辑域连接',DOMAINS[id]);closeDialog();render();});}
function removeDomain(id){const d=state.domains.find(d=>d.id===id&&domainAllowed(id));if(!d||!canOperation('connection'))return;const epoch=state.epoch;openDialog('移除域连接',`<div class="response-target">${DOMAINS[id]}</div><p>连接将移入归档，已有观测与审计保留。可从连接页恢复。</p>`,btn('确认移除','confirm-intent','danger'),()=>{if(epoch!==state.epoch||!domainAllowed(id)||!canOperation('connection')){closeDialog();return;}d.archived=true;audit('归档域连接',DOMAINS[id]);closeDialog();render();});}
function directoryAuth(domain){if(!canOperation('directory')||!domainAllowed(domain))return;const epoch=state.epoch;openDialog('目录读取授权',`<p>读取目录前，需要确认读取范围、字段能力和操作账户用途。连接诊断授权不会自动授予读取权限。</p><div class="response-target">${DOMAINS[domain]} · DEMO-OP-01 · 仅显示引用</div><label class="check-label"><input id="directory-master" type="checkbox">允许目录读取</label><label class="check-label"><input id="directory-v2" type="checkbox">启用扩展目录字段</label><label class="check-label"><input id="directory-grant" type="checkbox">当前角色具备扩展读取授权与账户用途</label><div id="directory-error" class="error-inline" role="alert"></div>`,btn('读取目录','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!domainAllowed(domain)||!canOperation('directory')){closeDialog();toast('权限或范围已变化。');return;}if(!['directory-master','directory-v2','directory-grant'].every(id=>$('#'+id).checked)){$('#directory-error').textContent='三个条件必须全部满足；旧用途不会自动升级。';return;}audit('目录用途核验',DOMAINS[domain]);closeDialog();state.domain=domain;setRoute('assets');toast('目录观测已就绪。');});}
function cancelTask(id){const t=visibleTasks().find(t=>t.id===id);if(!t||!canOperation('task')||!['queued','running'].includes(t.state))return;if(t.state==='queued'){t.state='cancelled';t.events.push({time:'00:00:01 UTC',text:'尚未开始执行，排队任务取消已确认。'});audit('取消排队任务',t.id);}else{t.state='cancel_requested';t.cancelAt=Date.now();t.events.push({time:'00:00:03 UTC',text:'已记录取消请求，等待执行结束确认。'});audit('请求取消任务',t.id,'待确认');}render();toast(t.state==='cancelled'?'排队任务已取消，实际尝试仍为 0。':'已请求取消；停止等待不代表执行已经停止。');}
function recoverTask(id){const t=visibleTasks().find(t=>t.id===id);if(!t||t.state!=='failed'||!t.safeReplay||!canOperation('task')||(t.kind==='export'&&!exportAllowed(t.exportType)))return;const epoch=state.epoch;openDialog('以新任务恢复',`<p>恢复保留旧任务历史，重新核验当前授权并创建关联父任务的新任务。不重置原记录。</p><div class="response-target">原任务：${t.id}<br>类型：${t.title}</div>`,btn('确认新建恢复任务','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!domainAllowed(t.domain)||!canOperation('task')||(t.kind==='export'&&!exportAllowed(t.exportType))){closeDialog();toast('权限变化，恢复确认失效。');return;}const child=createTask({id:'recovery-'+t.id+'-'+state.epoch,kind:t.kind,domain:t.domain,role:state.role,epoch:state.epoch,scenario:'normal',template:t.template,targets:t.targets,exportType:t.exportType,dataSnapshot:t.data},t.title,t.id);closeDialog();setRoute('work');toast('恢复子任务 '+child.id+' 已创建。');});}
function reconcile(id){const t=visibleTasks().find(t=>t.id===id);if(!t||t.state!=='unknown'||!canOperation('task'))return;if(t.epoch!==state.epoch){toast('旧授权版本已失效，不能核对或复活原任务。');return;}t.state='succeeded';t.progress=100;t.events.push({time:'00:00:08 UTC',text:'已核对原请求的完成记录；没有重新执行。'});audit('核对原任务结果',t.id);render();toast('原任务结果已核对；没有重放写入。');}
function download(id){const t=visibleTasks().find(t=>t.id===id);if(!t||t.kind!=='export'||t.state!=='succeeded'||t.epoch!==state.epoch||!exportAllowed(t.exportType)||state.downloadRevoked){toast('当前下载权限已失效或文件不可用。历史任务不构成下载授权。');return;}const csv=t.data.headers.join(',')+'\r\n'+t.data.rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ADTR_SYNTHETIC_'+t.id+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);audit('下载文件',t.id);toast('CSV 文件已生成。');}
function captureFocus(){
  const el=document.activeElement;if(!el||el===document.body)return null;
  const keys=['action','id','page','verb','intent','bizFilter','bizSelect','filter','tab','key','value','socFilter'];
  const data=Object.fromEntries(keys.filter(k=>el.dataset?.[k]!==undefined).map(k=>[k,el.dataset[k]]));
  return {id:el.id||null,data,href:el.getAttribute?.('href')||null,drawer:!!el.closest('.drawer'),scroll:$('.drawer')?.scrollTop||0,selectionStart:el.selectionStart??null,selectionEnd:el.selectionEnd??null};
}
function restoreFocus(saved){
  if(!saved)return;const root=saved.drawer?$('.drawer'):document;if(!root)return;
  const dataSelector=Object.entries(saved.data||{}).map(([key,value])=>'[data-'+key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+'="'+CSS.escape(value)+'"]').join('');
  let el=saved.id?$('#'+CSS.escape(saved.id),root):dataSelector?$(dataSelector,root):saved.href?$('[href="'+CSS.escape(saved.href)+'"]',root):null;
  if(!el&&saved.data?.id)el=$('[data-action="task-detail"][data-id="'+CSS.escape(saved.data.id)+'"]',root);
  el?.focus({preventScroll:true});if(el?.setSelectionRange&&saved.selectionStart!==null&&['text','search','textarea'].includes(el.type))el.setSelectionRange(saved.selectionStart,saved.selectionEnd);
  if(saved.drawer&&$('.drawer'))$('.drawer').scrollTop=saved.scroll;
}
function updateTaskRegions(){const el=$('#task-table-region');if(el){const f=captureFocus();el.innerHTML=taskTable(visibleTasks());restoreFocus(f);}}
function tick(){let changed=false;const now=Date.now();for(const t of state.tasks){if(!['queued','running','cancel_requested'].includes(t.state))continue;if(t.actor!==state.role||t.epoch!==state.epoch){t.state='failed';t.error='原授权已失效，任务已停止。重新获得权限后需要单独确认新任务。';t.events.push({time:'00:00:02 UTC',text:'会话或授权版本变化，任务已停止。'});changed=true;continue;}if(t.state==='queued'&&now-t.created>=1800){t.state='running';t.attempt=1;t.events.push({time:'00:00:02 UTC',text:'开始执行，已记录本次尝试。'});changed=true;}else if(t.state==='cancel_requested'&&now-t.cancelAt>=1400){if(t.scenario==='cancel-race'){t.state='succeeded';t.progress=100;t.events.push({time:'00:00:04 UTC',text:'任务在取消请求生效前已完成，保留实际完成结果。'});}else if(t.scenario==='cancel-lost'){t.state='failed';t.error='执行停止尚未确认，请先核对原任务结果。';t.events.push({time:'00:00:04 UTC',text:'未收到执行端确认，停止状态仍待核对。'});}else{t.state='cancelled';t.events.push({time:'00:00:04 UTC',text:'已收到执行结束确认，取消完成。'});}changed=true;}else if(t.state==='running'){t.progress=Math.min(95,Math.floor((now-t.created-1800)/55));changed=true;if(now-t.created>=7000){if(t.scenario==='unknown'){t.state='unknown';t.events.push({time:'00:00:07 UTC',text:'提交结果未确认，保留原意图；等待只读核对，不自动重放。'});}else if(t.scenario==='failed'){t.state='failed';t.error=t.safeReplay?'发生可恢复的暂时性错误。重新核对授权后，可创建关联恢复任务。':'输入检查未通过。请修正配置后重新核对目标并提交。';t.events.push({time:'00:00:07 UTC',text:'任务失败，详细原因已记录。'});}else if(t.scenario==='partial'&&t.kind==='detection'){t.state='partial_failed';t.objectResults=(t.targets||[]).map((o,i)=>({...o,state:['成功','失败','结果不确定'][i%3]}));t.events.push({time:'00:00:07 UTC',text:'已保留逐对象的成功、失败与待核对结果；请分别处理。'});}else if(t.scenario==='partial'){t.state='failed';t.error='当前目标执行失败。仅报告已确认对象的结果，请查看关联证据后处理。';t.events.push({time:'00:00:07 UTC',text:t.target?`已确认目标 ${t.target.name} / ${t.target.assetId} 执行失败。`:'本任务执行失败，请查看目标与输入信息。'});}else{t.state='succeeded';t.progress=100;t.events.push({time:'00:00:07 UTC',text:'任务已完成，结果已记录。'});}audit('任务终态',t.id,taskLabel(t));}}}business.tick();if(changed){if(state.drawer?.type==='task'&&!stateGuard(state.route)){const f=captureFocus();$('.drawer-overlay')?.remove();renderDrawer();restoreFocus(f);}updateTaskRegions();if((state.route==='reports'||state.investigationId)&&!state.drawer&&!$('#dialog').open)render();}}
function switchContext(kind,value){const path=state.investigationId?(kind==='scenario'?'threats/investigation/'+state.investigationId:'threats'):[state.route,state.view].filter(Boolean).join('/');business.clearContext();closeDialog();state.drawer=null;if(kind==='role'||kind==='domain')state.responseTarget=null;state.filters={};if(kind!=='scenario')soc.clearContext();if(kind==='role'){state.role=value;state.domain='all';state.epoch++;state.messagesRead.clear();}else if(kind==='domain'){state.domain=value;}else{state.scenario=value;}document.body.classList.remove('overlay-open');setRoute(path,true);toast('工作空间已切换。');}

function saveGrants(){if(!permission('roleManage')){toast('当前角色不能管理权限。');return;}const read=$('#grant-read').checked,write=$('#grant-write').checked;if(write&&!read){toast('写入依赖读取权限；请先启用读取。');$('#grant-read').focus();return;}const epoch=state.epoch;openDialog('确认权限变更',`<p>目标是另一自定义角色。不会修改当前操作者、真实用户或服务器权限。</p><div class="response-target"><div class="info-row"><span>响应读取</span><strong>${read?'允许':'拒绝'}</strong></div><div class="info-row"><span>响应写入</span><strong>${write?'允许':'拒绝'}</strong></div><div class="info-row"><span>显式资源组</span><strong>alpha.example.test</strong></div></div><label class="check-label"><input id="grant-proof" type="checkbox">已确认操作身份，理解受影响会话将失效</label><div id="grant-error" class="error-inline" role="alert"></div>`,btn('保存变更','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!role().admin){closeDialog();toast('权限变更确认失效。');return;}if(!$('#grant-proof').checked){$('#grant-error').textContent='请确认操作身份与会话影响。';return;}state.roleGrant={read,write};audit('修改角色权限','DEMO-Response');closeDialog();render();toast('角色权限已保存。');});}
const actions={
'mobile-menu':()=>{state.mobile=!state.mobile;$('.sidebar').classList.toggle('open',state.mobile);},
'close-drawer':closeDrawer,'close-dialog':closeDialog,
'confirm-intent':()=>{const fn=$('#dialog')._confirm;if(fn)fn();},
'asset-detail':el=>openDetail('asset',el.dataset.id),'event-detail':el=>openDetail('event',el.dataset.id),'task-detail':el=>openDetail('task',el.dataset.id),
'reset-filters':el=>{state.filters[el.dataset.page]={q:'',type:'all',level:'all'};render();},'retry-page':()=>{state.scenario='normal';render();},
'add-domain':addDomain,'edit-domain':el=>editDomain(el.dataset.domain),'delete-domain':el=>removeDomain(el.dataset.domain),'restore-domains':()=>{if(!canOperation('connection'))return;state.domains.filter(d=>domainAllowed(d.id)).forEach(d=>d.archived=false);render();},'directory-auth':el=>directoryAuth(el.dataset.domain),'diagnose':el=>{if(!domainAllowed(el.dataset.domain)||!canOperation('diagnostic'))return;state.domain=el.dataset.domain;confirmation('diagnostic','单次连接诊断','<div class="info-row"><span>尝试上限</span><strong>1 · 无通用恢复</strong></div>');},
'sync-directory':()=>{if(canOperation('detection'))setRoute('assets/sync');},'new-detection':el=>confirmation('detection','检测任务','',el.dataset.template||'baseline'),
'response-confirm':()=>confirmation('response','账户访问限制','<div class="info-row"><span>目标</span><strong>当前域的明确目录对象 · 1 项</strong></div><div class="info-row"><span>目标版本</span><strong>v3</strong></div>'),
'export-assets':()=>exportDialog('assets'),'export-events':()=>exportDialog('events'),'export-audit':()=>exportDialog('audit'),'export-overview':()=>exportDialog('assets'),
'health-task':()=>confirmation('health','基础设施健康检查'),
'show-archived-tasks':()=>{state.showArchivedTasks=!state.showArchivedTasks;render();},
'archive-task':el=>{const t=visibleTasks().find(t=>t.id===el.dataset.id);if(!t||!canOperation('task'))return;const epoch=state.epoch;openDialog(t.archived?'恢复检测记录':'归档检测记录','<p>保留检测证据和操作历史，仅改变列表可见性。</p>',btn('确认','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!domainAllowed(t.domain)||!canOperation('task')){closeDialog();return;}t.archived=!t.archived;audit(t.archived?'归档检测记录':'恢复检测记录',t.id);closeDialog();render();});},
'cancel-task':el=>cancelTask(el.dataset.id),'recover-task':el=>recoverTask(el.dataset.id),'reconcile-task':el=>reconcile(el.dataset.id),'download-task':el=>download(el.dataset.id),
'revoke-download':()=>{state.downloadRevoked=true;toast('当前下载授权已撤销。');},
'event-whitelist':el=>{const e=visibleEvents().find(e=>e.id===el.dataset.id);if(e&&canOperation('whitelist'))business.fromEvent(e);},
'event-investigate':el=>{const e=visibleEvents().find(e=>e.id===el.dataset.id);if(e&&canOperation('investigation')){e.state='调查中';soc.addActivity(e,'开始调查','已将事件标为调查中');audit('标记事件',e.id);render();toast('事件已标为调查中。');}},
'event-close':el=>{const e=visibleEvents().find(e=>e.id===el.dataset.id);if(!e||!canOperation('investigation'))return;const epoch=state.epoch;openDialog('关闭事件',`<p>${e.title}</p><p>关闭改变事件处理状态，证据与响应记录仍保留。当前目标：${DOMAINS[e.domain]} / ${e.id}。</p><label class="form-field"><span>调查结论</span><select id="close-classification"><option value="">选择结论</option><option>已确认威胁</option><option>已授权业务活动</option><option>误报</option></select></label><label class="form-field"><span>结案说明</span><textarea id="close-reason" rows="3" maxlength="400" placeholder="记录证据与判断依据"></textarea></label><div id="close-error" class="error-inline" role="alert"></div>`,btn('确认关闭事件','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!domainAllowed(e.domain)||!canOperation('investigation')){closeDialog();toast('范围已变化。');return;}const classification=$('#close-classification').value,reason=$('#close-reason').value.trim();if(!classification||!reason){$('#close-error').textContent='请选择调查结论并填写判断依据。';return;}e.state='已关闭';e.conclusion={classification,reason};soc.addActivity(e,'关闭事件 · '+classification,reason);audit('关闭事件',e.id);closeDialog();render();});},
'event-response':el=>{const e=visibleEvents().find(e=>e.id===el.dataset.id);if(!e||!canOperation('response'))return;state.domain=e.domain;state.responseTarget=Object.freeze({eventId:e.id,assetId:e.asset,version:3});setRoute('response');},
'work-tab':el=>{state.tab.work=el.dataset.tab;render();},'admin-tab':el=>{state.tab.admin=el.dataset.tab;render();},
'messages':()=>{state.tab.work='messages';setRoute('work');},'mark-read':el=>{if(visibleEvents().some(e=>e.id===el.dataset.id)){state.messagesRead.add(el.dataset.id);render();}},

'save-grants':saveGrants,
'permission-info':()=>openDialog('显式授权说明','<p>角色只决定功能动作。AD 数据还必须通过租户、域范围及凭据用途核验。平台管理员没有默认域通行证。</p><p>功能权限与数据范围需要同时满足。</p>'),

};
const business=window.ADTR_WORKBENCH({state,escape,icon,tag,btn,link,toast,role,permission,canWrite,domainAllowed,selectedDomain,openDialog,closeDialog,render,audit,empty,footer,titles:TITLES,domains:DOMAINS,visibleAssets,visibleEvents,createTask,setRoute,taskLabel,reconcile,
responseTarget:(assetId,domain,policy={})=>{state.domain=domain;state.responseTarget=Object.freeze({assetId,eventId:null,version:3,...policy});setRoute('response');},
logout:()=>{state.signedOut=true;state.epoch++;state.drawer=null;state.responseTarget=null;state.filters={};business.clearContext();soc.clearContext();closeDialog();setRoute('admin/accounts',true);},
login:(account)=>{const next=({ 'demo.operator':'operator','demo.viewer':'viewer','demo.platform':'platform','demo.maintainer':'maintainer','demo.new':'newuser','demo.expired':'expireduser'})[account]||state.role;state.role=next;state.signedOut=false;state.domain='all';state.drawer=null;state.responseTarget=null;state.filters={};state.epoch++;business.clearContext();soc.clearContext();closeDialog();setRoute('overview',true);}});
const soc=window.ADTR_SOC({state,escape,icon,tag,btn,link,role,permission,domainAllowed,visibleAssets,visibleEvents,visibleTasks,render,setRoute,toast,audit,empty,domains:DOMAINS,canOperation,taskLabel,exportAllowed,
recentDetection:()=>business.overviewData(),
previewAsset:id=>{const a=visibleAssets().find(a=>a.id===id);if(!a)return;drawerReturnFocus=document.activeElement;drawerReturnPath='threats/investigation/'+state.investigationId;state.drawer={type:'asset',id:a.id};render();queueMicrotask(()=>$('.drawer-head h2')?.focus({preventScroll:true}));},
beginResponse:e=>{const current=visibleEvents().find(x=>x.id===e.id),a=current&&visibleAssets().find(x=>x.id===current.asset);if(!current||!a||!canOperation('response'))return;state.responseTarget=Object.freeze({eventId:current.id,assetId:a.id,version:3});confirmation('response',responseEffect(a));}
});
Object.assign(actions,business.actions,soc.actions,{
'demo-settings':()=>openDialog('演示环境',`<p>当前数据和操作均在本地模拟，刷新后重置。</p><label class="form-field"><span>工作角色</span><select id="role" aria-label="演示角色">${Object.entries(ROLES).map(([id,r])=>`<option value="${id}" ${state.role===id?'selected':''}>${r.name}</option>`).join('')}</select></label><label class="form-field"><span>场景</span><select id="scenario" aria-label="演示场景">${[['normal','正常'],['empty','空数据'],['error','读取失败'],['forbidden','无权限'],['stale','陈旧观测'],['failed','任务失败'],['unknown','结果未知'],['partial','部分失败'],['cancel-race','取消竞争'],['cancel-lost','停止未确认']].map(([v,t])=>`<option value="${v}" ${state.scenario===v?'selected':''}>${t}</option>`).join('')}</select></label>`),
'resume-session':()=>business.resumeSession()
});
document.addEventListener('click',e=>{if(e.target.closest('.skip-link')){e.preventDefault();$('#main')?.focus();return;}const el=e.target.closest('[data-action]');if(!el||el.disabled)return;actions[el.dataset.action]?.(el);});
document.addEventListener('change',e=>{if(soc.onChange(e.target)||business.onChange(e.target))return;if(e.target.id==='role')switchContext('role',e.target.value);else if(e.target.id==='domain')switchContext('domain',e.target.value);else if(e.target.id==='scenario')switchContext('scenario',e.target.value);else if(e.target.dataset.filter&&e.target.dataset.filter!=='q'){filterState(e.target.dataset.page)[e.target.dataset.filter]=e.target.value;render();}else if(['confirm-impact','confirm-demo'].includes(e.target.id)&&$('#confirm-impact')?.checked&&$('#confirm-demo')?.checked){const error=$('#confirm-error');if(error)error.textContent='';}});
document.addEventListener('input',e=>{if(soc.onInput(e.target)||business.onInput(e.target))return;if(e.target.dataset.filter==='q'){const page=e.target.dataset.page;const pos=e.target.selectionStart;filterState(page).q=e.target.value;render();const next=$(`[data-filter="q"][data-page="${page}"]`);next.focus();if(['text','search'].includes(next.type)&&pos!==null)next.setSelectionRange(pos,pos);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.drawer&&!$('#dialog').open){e.preventDefault();closeDrawer();return;}if(e.key==='Tab'&&state.drawer&&!$('#dialog').open){const drawer=$('.drawer');if(!drawer)return;const focusables=$$('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),[tabindex="0"]',drawer);if(!focusables.length)return;const first=focusables[0],last=focusables.at(-1);if(!drawer.contains(document.activeElement)||(!e.shiftKey&&document.activeElement.id==='drawer-title')){e.preventDefault();(e.shiftKey?last:first).focus();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement.id==='drawer-title')){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',readRoute);
window.addEventListener('popstate',()=>{if($('#dialog').open)closeDialog();});
// Cross-tab synthetic session reset carries no identity data, credentials or authority.
let channel;try{channel=new BroadcastChannel('adtr-isolated-prototype');channel.addEventListener('message',e=>{if(e.data==='reset-view'){closeDialog();state.drawer=null;state.filters={};soc.clearContext();state.epoch++;setRoute(state.route,true);toast('会话需要重新核验，旧视图已清理。');}});}catch{/* File origins may not support BroadcastChannel. No security claim is made. */}
window.addEventListener('beforeunload',()=>{clearInterval(timer);channel?.close();});
const timer=setInterval(tick,400);
readRoute();
})();
