/* Domain workspaces: all records are synthetic and memory-only. */
window.ADTR_BUSINESS_PAGES = (() => {
  const cols = text => text.split('|').map(x => { const [key,label]=x.split(':'); return {key,label}; });
  const fields = (text) => text.split('|').map(x => { const [key,label,choices]=x.split(':'); return {key,label,type:choices?'select':'text',...(choices?{options:choices.split(',')}:{required:true})}; });
  const act = (label,verb,confirm=false) => ({label,verb,confirm});
  const row = (id,name,values={}) => ({id,name,domain:'alpha',status:'启用',version:1,...values});
  const page = (id,title,subtitle,columns,form,rows,actions=[],extra={}) => ({id,section:id.split('/')[0],title,subtitle,scope:'domain',columns:cols(columns),fields:fields(form),rows,rowActions:actions,primary:{label:'新增'+title,verb:'create'},...extra});
  return [
    page('connections/sources','域控与数据源','选择目录、日志和流量的数据来源，查看每台域控的观测时间。','name:域控制器|site:站点|address:地址|source:数据源|status:采集状态|seen:最近观测','name:名称|site:站点|address:保留地址|source:数据源:目录与安全日志,仅目录,仅安全日志',[
      row('dc1','DEMO-DC-01',{site:'总部 / HQ',address:'192.0.2.10',source:'目录与安全日志',seen:'10-10 00:00 UTC'}),row('dc2','DEMO-BETA-DC',{domain:'beta',site:'分部 / Branch',address:'198.51.100.10',source:'仅目录',status:'待配置',seen:'10-09 23:59 UTC'})
    ],[act('设为首选','select'),act('配置数据源','edit')],{primary:null,help:'首选域控用于新的读取任务；现有任务保留原数据源。'}),
    page('connections/accounts','操作账户','将账户引用与具体用途关联，分别管理连接诊断、目录读取和采集部署。','name:账户引用|identity:身份|purpose:授权用途|expiry:到期时间|status:状态','name:引用名称|identity:合成身份|purpose:授权用途:连接诊断,目录读取,采集部署|expiry:到期日期',[
      row('op1','DEMO-OP-01',{identity:'DEMO\\svc_directory',purpose:'目录读取',expiry:'2026-12-31'}),row('op2','DEMO-OP-02',{domain:'beta',identity:'DEMO\\svc_collect',purpose:'连接诊断',expiry:'2026-10-31'})
    ],[act('编辑用途','edit'),act('删除引用','delete',true)],{primary:{label:'登记账户引用',verb:'create'},help:'仅选择预置的演示账户引用。请勿输入真实密码或密钥。'}),
    page('connections/deployment','接入与采集器部署','按域控准备审计策略、对象审计和采集组件，逐步检查安装结果。','name:部署方案|system:目标系统|policy:域审计策略|objectAudit:对象审计|package:安装包|status:状态','name:方案名称|system:系统:Windows Server 2022,Windows Server 2019|policy:域审计策略:推荐安全审计,只检查不修改|objectAudit:对象审计:敏感目录对象,全部授权对象|package:采集器版本:2.4.1 x64,2.3.8 x64',[
      row('deploy1','总部域控接入',{system:'Windows Server 2022',policy:'推荐安全审计',objectAudit:'敏感目录对象',package:'2.4.1 x64',status:'待预检'}),row('deploy2','分部域控接入',{domain:'beta',system:'Windows Server 2019',policy:'只检查不修改',objectAudit:'全部授权对象',package:'2.3.8 x64',status:'预检告警'})
    ],[act('环境预检','test'),act('初始化接入','initialize',true),act('部署审计策略','deploy-policy',true),act('部署对象审计','deploy-object',true),act('安装采集器','install',true),act('下载安装清单','download')],{kind:'deployment',primary:{label:'新建部署方案',verb:'create'},help:'变更前检查目标域控、维护窗口和回退计划。安装流程不会接收真实凭据。'}),
    page('connections/collectors','采集器管理','管理注册实例、采集版本和心跳，集中处理运行异常。','name:实例名称|host:所属域控|agentVersion:版本|heartbeat:最近心跳|cpu:CPU|status:运行状态','name:实例名称|host:域控|agentVersion:版本:2.4.1,2.3.8|channel:通道:LDAPS + 事件转发,仅事件转发|alert:异常提醒:启用,忽略',[
      row('collector1','总部采集器',{host:'DEMO-DC-01',agentVersion:'2.4.1',heartbeat:'30 秒前',cpu:'12%',memory:'218 MB',channel:'LDAPS + 事件转发',alert:'启用',status:'在线'}),row('collector2','分部采集器',{domain:'beta',host:'DEMO-BETA-DC',agentVersion:'2.3.8',heartbeat:'17 分钟前',cpu:'未观测',memory:'未观测',channel:'仅事件转发',alert:'启用',status:'心跳异常'})
    ],[act('编辑配置','edit'),act('升级','upgrade',true),act('忽略 / 恢复提醒','alert'),act('移除实例','delete',true)],{primary:{label:'注册采集器',verb:'create'},batch:[act('批量升级','upgrade',true)],kind:'telemetry'}),
    page('connections/collection','日志与网络流量','分别配置安全事件和网络协议采集，检查吞吐量、积压与采集时间。','name:采集源|type:采集类型|protocol:事件 / 协议|rate:每分钟记录|lag:延迟|status:开关','name:采集源|type:类型:安全日志,网络流量|protocol:事件或协议|retention:保留天数',[
      row('stream1','DEMO-DC-01 / Security',{type:'安全日志',protocol:'4624, 4625, 4662, 4728',rate:'1,248',lag:'4 秒',retention:'90'}),row('stream2','DEMO-DC-01 / Network',{type:'网络流量',protocol:'Kerberos, LDAP, DNS',rate:'386',lag:'6 秒',retention:'30'}),row('stream3','DEMO-BETA-DC / Security',{domain:'beta',type:'安全日志',protocol:'4624, 4625',rate:'未观测',lag:'未观测',retention:'90',status:'停用'})
    ],[act('配置采集','edit'),act('启用 / 停用','toggle',true),act('运行详情','inspect')],{primary:null,kind:'telemetry'}),
    page('connections/protection','运行保护','限制采集进程资源，出现超限时降速或暂停，并保留恢复记录。','name:进程|cpuLimit:CPU上限|memoryLimit:内存上限|protection:保护动作|status:状态','name:进程|cpuLimit:CPU上限（%）|memoryLimit:内存上限（MB）|protection:保护动作:降速采集,暂停采集|autoRecover:恢复方式:人工确认,低于阈值后恢复',[
      row('process1','Security Event Collector',{cpuLimit:'40',memoryLimit:'512',protection:'降速采集',autoRecover:'低于阈值后恢复',status:'运行中'}),row('process2','Network Collector',{domain:'beta',cpuLimit:'30',memoryLimit:'384',protection:'暂停采集',autoRecover:'人工确认',status:'保护已触发'})
    ],[act('调整保护策略','edit'),act('暂停 / 恢复进程','toggle',true),act('异常恢复','restore',true)],{primary:null,kind:'protection',help:'恢复前确认资源已经低于阈值；不清除原异常记录。'}),
    page('connections/remote','远程管理','查看受控操作及管理通道。执行前确认对象、范围和维护窗口。','name:操作名称|target:目标|channel:管理通道|window:维护窗口|status:结果','name:操作名称|target:目标域控|channel:管理通道:Windows 管理通道,采集器通道|window:维护窗口',[
      row('remote1','检查审计策略',{target:'DEMO-DC-01',channel:'Windows 管理通道',window:'02:00–03:00 UTC',status:'待执行'}),row('remote2','读取采集服务状态',{domain:'beta',target:'DEMO-BETA-DC',channel:'采集器通道',window:'01:00–02:00 UTC',status:'通道关闭'})
    ],[act('执行操作','execute',true),act('打开 / 关闭通道','toggle',true),act('查看结果','inspect')],{primary:null,help:'只能执行已列出的受控操作；不接受脚本、命令或任意远程地址。'}),
    page('connections/sync','配置同步与代理','跟踪域控变化，将采集配置同步到受授权实例，并检查代理链路。','name:同步配置|controllers:域控集合|proxy:代理|lastChange:最近变化|status:同步状态','name:配置名称|controllers:域控集合|proxy:代理:直连,DEMO-PROXY-01|syncMode:同步策略:审核后同步,自动同步已授权域控',[
      row('config1','总部采集配置',{controllers:'DEMO-DC-01',proxy:'直连',syncMode:'审核后同步',lastChange:'新增安全事件 4728',status:'待同步'}),row('config2','分部代理配置',{domain:'beta',controllers:'DEMO-BETA-DC',proxy:'DEMO-PROXY-01',syncMode:'审核后同步',lastChange:'代理地址更新',status:'已同步'})
    ],[act('编辑配置','edit'),act('检测代理','test'),act('同步配置','sync',true)],{primary:null}),
    page('assets/sync','目录同步','比较目录批次，分别执行全量、增量和设备标识同步。','name:同步计划|mode:同步方式|objects:对象数|cursor:变更游标|updated:最近同步|status:状态','name:计划名称|mode:同步方式:全量目录,增量目录,设备名称与地址|source:来源域控',[
      row('sync1','总部目录全量',{mode:'全量目录',source:'DEMO-DC-01',objects:'6',cursor:'batch-001',updated:'00:00 UTC',status:'已完成'}),row('sync2','总部目录增量',{mode:'增量目录',source:'DEMO-DC-01',objects:'2',cursor:'change-032',updated:'00:05 UTC',status:'待执行'}),row('sync3','分部设备标识',{domain:'beta',mode:'设备名称与地址',source:'DEMO-BETA-DC',objects:'1',cursor:'change-014',updated:'23:59 UTC',status:'已完成'})
    ],[act('开始同步','sync',true),act('批次差异','inspect')],{primary:{label:'配置同步计划',verb:'create'},kind:'sync'}),
    page('assets/permissions','权限关系与变更','查看成员关系、对象访问控制和前后快照，区分直接授权与继承。','name:目录对象|principal:被授权身份|permission:权限|inheritance:来源|change:最近变更|status:评估','name:同步名称|mode:同步方式:全量权限,权限变更|source:来源域控',[
      row('acl1','DEMO-Tier0',{principal:'demo.alex',permission:'成员 / WriteMembers',inheritance:'直接授权',change:'新增成员',before:'DEMO-Engineering',after:'DEMO-Tier0',status:'需复核'}),row('acl2','OU=Workstations',{principal:'DEMO-Helpdesk',permission:'ResetPassword',inheritance:'从父容器继承',change:'无变化',before:'ResetPassword',after:'ResetPassword',status:'已确认'}),row('acl3','DEMO-Finance',{domain:'beta',principal:'demo.alex',permission:'读取',inheritance:'直接授权',change:'移除写权限',before:'读取 + 写入',after:'读取',status:'已确认'})
    ],[act('关系与快照','inspect'),act('同步权限变化','sync',true)],{primary:{label:'全量同步权限',verb:'sync'},kind:'relationships'}),
    page('assets/sensitive','敏感资产','按业务重要性标记身份和设备，跟踪敏感对象变更。','name:资产|category:类别|label:敏感标签|reason:识别依据|alert:变更告警|status:状态','name:资产|category:类别:用户,计算机,组|label:敏感标签:核心身份,关键服务,特权组|reason:标记原因|alert:变更告警:启用,停用',[
      row('tag1','demo.alex',{category:'用户',label:'核心身份',reason:'属于 DEMO-Tier0',alert:'启用',status:'已标记'}),row('tag2','DEMO-Tier0',{category:'组',label:'特权组',reason:'具备目录管理权限',alert:'启用',status:'成员已变化'}),row('tag3','DEMO-BETA-DC',{domain:'beta',category:'计算机',label:'关键服务',reason:'域控制器',alert:'启用',status:'已标记'})
    ],[act('编辑标签','edit'),act('告警开关','alert'),act('移除标记','delete',true)],{primary:{label:'标记敏感资产',verb:'create'}}),
    page('assets/relations','身份与访问关系','从身份、设备和服务追踪登录会话及访问行为。','name:身份|device:设备|service:服务|relation:关系|time:最后访问|status:可信状态','name:身份|device:设备|service:服务',[
      row('rel1','demo.alex',{device:'DEMO-WS-012',service:'LDAP / DEMO-DC-01',relation:'登录 → 目录访问',time:'23:58:42 UTC',status:'需调查'}),row('rel2','demo.service',{device:'DEMO-WS-012',service:'Kerberos / DEMO-DC-01',relation:'首次认证',time:'23:46:18 UTC',status:'新关系'}),row('rel3','demo.alex',{domain:'beta',device:'DEMO-BETA-DC',service:'SMB / Finance',relation:'服务访问',time:'23:18:52 UTC',status:'已确认'})
    ],[act('查看行为序列','inspect')],{primary:null,kind:'relationships',related:[['行为检索','threats/search'],['认证活动','threats/behavior']]}),
    page('assets/risk','身份风险','分析风险事件分布和评分变化，保留每次更新的原因与来源。','name:身份|score:当前评分|previous:上次评分|reason:变化原因|eventCount:关联事件|status:状态','name:身份|reason:重置原因',[
      row('risk1','demo.alex',{score:'87',previous:'62',reason:'敏感目录异常访问 +25',eventCount:'2',status:'高风险'}),row('risk2','demo.service',{score:'26',previous:'12',reason:'新设备认证 +14',eventCount:'1',status:'关注'}),row('risk3','demo.alex',{domain:'beta',score:'32',previous:'32',reason:'本次检测无变化',eventCount:'1',status:'中风险'})
    ],[act('评分记录','inspect'),act('重新评估','evaluate',true),act('重置评分','reset',true)],{primary:null,kind:'risk',help:'重置需填写原因，历史评分和证据仍会保留。'}),
    page('assets/trust','域信任','查看信任方向、传递性和跨域身份关联。','name:信任关系|direction:方向|trustType:类型|transitive:传递性|verified:最近核对|status:状态','name:信任关系|direction:方向:双向,单向传入,单向传出',[
      row('trust1','alpha → beta',{direction:'单向传出',trustType:'外部信任',transitive:'不传递',verified:'10-09 23:55 UTC',status:'待复核'}),row('trust2','beta → alpha',{domain:'beta',direction:'单向传入',trustType:'外部信任',transitive:'不传递',verified:'10-09 23:55 UTC',status:'已观测'})
    ],[act('关联身份','inspect')],{primary:null}),
    page('detection/baseline','安全基线','按检查项查看配置证据、风险与加固建议，支持单项复查。','name:检查项|category:类别|severity:风险|observed:观测值|expected:建议值|status:检查结果','name:检查项|category:类别:账户策略,目录权限,审计策略',[
      row('base1','特权组成员最小化',{category:'目录权限',severity:'高',observed:'包含常规运营身份',expected:'专用管理身份',status:'未通过'}),row('base2','账户锁定阈值',{category:'账户策略',severity:'中',observed:'5 次',expected:'不高于 10 次',status:'通过'}),row('base3','对象访问审计',{domain:'beta',category:'审计策略',severity:'中',observed:'未采集',expected:'成功与失败',status:'未检查'})
    ],[act('检查证据','inspect'),act('单项复查','recheck',true)],{primary:{label:'开始基线检测',verb:'detect'},export:true,kind:'findings'}),
    page('detection/vulnerabilities','漏洞检测','以身份与目录配置为依据定位暴露面，并追踪复查结果。','name:风险项|asset:目标|severity:严重性|evidence:检测依据|remediation:修复建议|status:结果','name:风险项|asset:目标|severity:严重性:高,中,低',[
      row('vuln1','证书模板权限过宽',{asset:'DEMO-Template-01',severity:'高',evidence:'普通身份具有注册权限',remediation:'收紧模板授权',status:'待修复'}),row('vuln2','服务账户不必要委派',{asset:'demo.service',severity:'中',evidence:'委派属性快照',remediation:'核对业务必要性',status:'需确认'}),row('vuln3','目录签名要求',{domain:'beta',asset:'DEMO-BETA-DC',severity:'中',evidence:'配置字段未观测',remediation:'补充配置采集',status:'未检查'})
    ],[act('证据与修复','inspect'),act('复查','recheck',true)],{primary:{label:'发起漏洞检测',verb:'detect'},export:true,kind:'findings'}),
    page('detection/behavior','行为关联检测','将登录会话与跨事件时间窗口关联，保留触发阈值和命中证据。','name:检测配置|window:关联窗口|threshold:阈值|identity:会话身份|hits:命中数|status:状态','name:配置名称|window:窗口:5 分钟,10 分钟,30 分钟|threshold:事件阈值|identity:身份范围|eventTypes:事件类型',[
      row('corr1','短时认证失败后成功',{window:'10 分钟',threshold:'5',identity:'demo.alex',eventTypes:'4625 → 4624',hits:'1'}),row('corr2','服务身份首次使用设备',{window:'30 分钟',threshold:'1',identity:'demo.service',eventTypes:'4624 + 4769',hits:'1'}),row('corr3','跨域权限变化关联',{domain:'beta',window:'5 分钟',threshold:'2',identity:'DEMO-Finance',eventTypes:'4728 + 4662',hits:'0',status:'停用'})
    ],[act('编辑关联条件','edit'),act('会话与命中','inspect'),act('启用 / 停用','toggle')],{primary:{label:'新建关联检测',verb:'create'},kind:'correlation'}),
    page('detection/passwords','凭据风险检测','检查弱口令与泄露风险，按检测类型分别查看结果与数据采集时间。','name:检查对象|checkType:检测类型|collected:数据采集|evidence:结果依据|status:结果','name:检查名称|checkType:检测类型:弱口令,密码泄露,邮箱泄露|scope:对象范围',[
      row('pwd1','demo.alex',{checkType:'弱口令',collected:'10-09 23:30 UTC',evidence:'仅风险标记，不显示密码',scope:'授权身份',status:'需重置'}),row('pwd2','demo.morgan@example.test',{checkType:'邮箱泄露',collected:'10-09 23:30 UTC',evidence:'无匹配记录',scope:'授权身份',status:'未命中'}),row('pwd3','demo.alex.beta@example.test',{domain:'beta',checkType:'密码泄露',collected:'未采集',evidence:'缺少检查数据',scope:'授权身份',status:'待采集'})
    ],[act('采集检测数据','collect',true),act('开始检查','detect',true),act('结果详情','inspect')],{primary:null,export:true,kind:'passwords',secondary:[act('下载检查模板','template')],help:'使用合成身份与风险结果；不会接收、显示或向外部提交真实密码。'}),
    page('detection/rules','规则库','编辑条件、测试样本并发布版本。已发布版本保持只读，修改会生成新草稿。','name:规则名称|category:类型|ruleVersion:版本|condition:条件|testResult:测试|status:状态','name:规则名称|category:类型:告警规则,行为规则,攻击路径规则|field:事件字段:event_id,account_name,source_device|operator:关系:等于,包含,不等于|value:匹配值|window:时间窗口:5 分钟,10 分钟,30 分钟|threshold:触发次数',[
      row('rule1','特权身份异常目录访问',{category:'告警规则',ruleVersion:'1.4.2',field:'event_id',operator:'等于',value:'4662',window:'5 分钟',threshold:'3',condition:'event_id = 4662 AND privileged',testResult:'2 / 2 通过',status:'已发布'}),row('rule2','服务身份新设备认证',{category:'行为规则',ruleVersion:'1.0.0-draft',field:'event_id',operator:'等于',value:'4624',window:'10 分钟',threshold:'1',condition:'event_id = 4624 AND new_device',testResult:'待测试',status:'草稿'}),row('rule3','目录权限路径异常',{domain:'beta',category:'攻击路径规则',ruleVersion:'1.1.0',field:'account_name',operator:'包含',value:'demo.',window:'30 分钟',threshold:'1',condition:'WriteMembers → PrivilegedGroup',testResult:'1 / 1 通过',status:'已发布'})
    ],[act('编辑规则','edit'),act('条件测试','test'),act('发布 / 激活','activate',true),act('启用 / 停用','toggle'),act('导出规则','download'),act('删除配置','delete',true)],{primary:{label:'新建规则',verb:'create'},kind:'rules',help:'发布前需要配置检查和样本测试通过。历史检测始终引用当时的规则版本。'}),
    page('detection/learning','学习型检测','设置学习窗口、基准人群和偏离阈值，检查样本质量后启用。','name:学习配置|subject:学习对象|period:窗口|samples:样本量|threshold:偏离阈值|status:状态','name:配置名称|subject:学习对象:身份登录,设备访问,服务使用|period:学习窗口:7 天,14 天,30 天|threshold:偏离阈值:中,高|minimum:最小样本量',[
      row('learn1','日常身份登录基线',{subject:'身份登录',period:'14 天',samples:'1,284',threshold:'高',minimum:'500',status:'已启用'}),row('learn2','服务使用基线',{domain:'beta',subject:'服务使用',period:'7 天',samples:'182',threshold:'中',minimum:'300',status:'样本不足'})
    ],[act('编辑学习配置','edit'),act('检查样本','test'),act('启用 / 停用','toggle',true),act('重新学习','reset',true)],{primary:{label:'新建学习配置',verb:'create'},kind:'learning'}),
    page('detection/templates','检测模板','组合检测项目、目标与调度方式，管理可复用的检查方案。','name:模板名称|checks:检测项目|targets:目标范围|schedule:运行计划|duration:预计耗时|status:状态','name:模板名称|checks:检测项目:安全基线与权限,漏洞与凭据风险,行为与身份异常|targets:目标范围|schedule:运行计划:手动,每日 02:00 UTC,每周一 03:00 UTC',[
      row('tpl1','安全基线',{checks:'安全基线与权限',targets:'已授权目录对象',schedule:'手动',duration:'约 5 分钟'}),row('tpl2','周度全面评估',{checks:'漏洞与凭据风险',targets:'敏感身份与域控',schedule:'每周一 03:00 UTC',duration:'约 30 分钟'}),row('tpl3','分部身份巡检',{domain:'beta',checks:'行为与身份异常',targets:'分部身份',schedule:'每日 02:00 UTC',duration:'约 10 分钟',status:'暂停'})
    ],[act('编辑模板','edit'),act('开始检测','detect',true),act('启用 / 暂停计划','toggle'),act('删除模板','delete',true)],{primary:{label:'新增检测模板',verb:'create'},related:[['周期计划','work/schedules']]}),
    page('detection/allowlists','检测白名单','管理规则级和全局例外，明确匹配条件、到期时间及创建来源。','name:白名单名称|scope:应用范围|match:匹配条件|source:来源|expiry:到期时间|status:状态','name:名称|scope:应用范围:指定规则,全局|rule:关联规则|match:匹配条件|expiry:到期日期|reason:例外原因',[
      row('allow1','备份服务目录读取',{scope:'指定规则',rule:'特权身份异常目录访问',match:'demo.backup / DEMO-BACKUP-01',source:'人工审核',expiry:'2026-11-01',reason:'夜间备份窗口'}),row('allow2','维护窗口测试身份',{domain:'beta',scope:'全局',rule:'全部行为规则',match:'demo.maintenance',source:'变更工单 CHG-DEMO-018',expiry:'2026-10-15',reason:'维护演练',status:'即将到期'})
    ],[act('编辑','edit'),act('删除','delete',true)],{primary:{label:'新增白名单',verb:'create'},export:true,secondary:[act('导入示例白名单','import')],help:'全局例外影响多条规则，应设置短有效期并记录审批依据。'}),
    page('threats/paths','攻击路径','关联目录权限与行为证据，识别从普通身份到关键资产的可达路径。','name:路径|source:起点|target:目标|steps:跳数|rule:关联规则|status:调查状态','name:路径名称|source:起点|target:目标',[
      row('path1','身份到特权组的访问路径',{source:'demo.alex',target:'DEMO-Tier0',steps:'3',rule:'目录授权链 / v1.1.0',status:'待复核'}),row('path2','分部设备到关键服务',{domain:'beta',source:'demo.alex',target:'DEMO-BETA-DC',steps:'2',rule:'服务访问链 / v1.2.1',status:'调查中'})
    ],[act('路径与证据','inspect'),act('导出路径','download')],{primary:null,kind:'paths',export:true}),
    page('threats/behavior','行为事件','按身份、设备和认证方式检索事件，核对原始字段与关联会话。','name:行为|identity:身份|device:设备|eventId:事件ID|auth:认证方式|time:发生时间','name:行为名称|identity:身份|device:设备',[
      row('beh1','目录对象访问',{identity:'demo.alex',device:'DEMO-DC-01',eventId:'4662',auth:'Kerberos',time:'23:58:42 UTC',status:'已关联'}),row('beh2','新设备登录成功',{identity:'demo.service',device:'DEMO-WS-012',eventId:'4624',auth:'Kerberos',time:'23:46:18 UTC',status:'待调查'}),row('beh0','历史目录对象访问',{identity:'demo.alex',device:'DEMO-DC-01',eventId:'4662',auth:'Kerberos',time:'10-06 18:00 UTC',observedAt:'2026-10-06T18:00:00Z',status:'已关联'}),row('beh3','认证失败',{domain:'beta',identity:'demo.alex',device:'DEMO-BETA-DC',eventId:'4625',auth:'NTLM',time:'23:18:52 UTC',status:'已关联'})
    ],[act('事件与设备认证','inspect')],{primary:null,export:true,kind:'behavior'}),
    page('threats/search','高级检索','组合字段、时间窗口与查询模板，按授权范围检索行为证据。','name:查询模板|query:查询条件|window:时间范围|retention:数据保留|status:状态','name:模板名称|query:查询条件|window:时间范围:最近 24 小时,最近 7 天,最近 30 天',[
      row('query1','特权目录访问',{query:'event_id = 4662',window:'最近 24 小时',retention:'90 天',status:'可用'}),row('query2','服务身份登录',{query:'account_name = demo.service',window:'最近 7 天',retention:'90 天',status:'可用'}),row('query3','分部认证失败',{domain:'beta',query:'event_id = 4625',window:'最近 24 小时',retention:'30 天',status:'可用'})
    ],[act('运行查询','query'),act('编辑模板','edit'),act('删除模板','delete',true)],{primary:{label:'保存查询模板',verb:'create'},kind:'search',help:'支持 event_id、account_name 和 device 字段，查询范围不超过当前可用保留期。'}),
    page('threats/honeypots','蜜罐与特权账户','配置诱捕身份与重点监控账户，检查可用性和属性变更。','name:账户|type:监控类型|device:关联设备|serviceName:服务属性|status:可用性','name:合成账户|type:监控类型:蜜罐账户,特权账户|device:关联设备|serviceName:服务属性|description:描述',[
      row('honey1','demo.honey.finance',{type:'蜜罐账户',device:'DEMO-WS-012',serviceName:'DEMO-REPORTS',description:'财务服务诱捕身份',status:'可用'}),row('honey2','demo.tier0.admin',{domain:'beta',type:'特权账户',device:'DEMO-BETA-DC',serviceName:'未设置',description:'分部特权身份监控',status:'待检查'})
    ],[act('账户属性','edit'),act('可用性检查','test'),act('删除配置','delete',true)],{primary:{label:'添加监控账户',verb:'create'}}),
    page('response/policies','阻断策略','定义触发条件、响应动作与恢复要求，执行前再次核对目标。','name:策略名称|trigger:触发条件|effect:响应动作|approval:确认方式|status:状态','name:策略名称|trigger:触发条件:人工确认,高危身份事件,蜜罐触发|effect:响应动作:限制账户访问,限制设备访问|approval:确认方式:每次确认|target:目标对象',[
      row('policy1','高风险身份访问限制',{trigger:'人工确认',effect:'限制账户访问',approval:'每次确认',target:'demo.alex',assetId:'a1',status:'启用'}),row('policy2','分部关键设备防护',{domain:'beta',trigger:'高危身份事件',effect:'限制设备访问',approval:'每次确认',target:'DEMO-BETA-DC',assetId:'a8',status:'停用'})
    ],[act('编辑策略','edit'),act('立即响应','respond',true),act('启用 / 停用','toggle'),act('删除策略','delete',true)],{primary:{label:'新增阻断策略',verb:'create'},help:'响应可能中断登录或业务访问；每次执行都需核对目标及例外名单。'}),
    page('response/allowlist','阻断白名单','防止关键业务身份或设备被误处置，记录例外理由与有效期。','name:对象|type:对象类型|reason:业务原因|owner:负责人|expiry:到期时间|status:状态','name:合成对象|type:对象类型:用户,计算机|reason:业务原因|owner:负责人|expiry:到期日期',[
      row('blockallow1','demo.backup',{type:'用户',reason:'备份恢复专用身份',owner:'DEMO-Infra',expiry:'2026-11-01'}),row('blockallow2','DEMO-BETA-DC',{domain:'beta',type:'计算机',reason:'关键域控维护保护',owner:'DEMO-Branch',expiry:'2026-10-15'})
    ],[act('编辑例外','edit'),act('删除例外','delete',true)],{primary:{label:'新增阻断白名单',verb:'create'}}),
    page('response/history','执行与恢复记录','逐对象核对限制结果，恢复采用独立确认并保留原记录。','name:对象|effect:动作|policy:来源策略|time:执行时间|status:结果','name:对象|reason:恢复原因',[
      row('resp1','demo.alex',{assetId:'a1',effect:'账户访问限制',policy:'高风险身份访问限制',time:'10-09 22:00 UTC',status:'限制已确认'}),row('resp2','DEMO-BETA-DC',{domain:'beta',assetId:'a8',effect:'设备访问限制',policy:'分部关键设备防护',time:'10-09 21:30 UTC',status:'待核对'})
    ],[act('核对原结果','reconcile'),act('恢复用户 / 设备','restore',true)],{primary:null,help:'结果未知时先核对原请求。恢复不会删除原执行记录。'}),
    page('reports/templates','报告模板','选择安全评估、加固、事件调查和巡检章节，保存可复用的版式。','name:模板名称|category:报告类型|sections:报告章节|period:默认周期|status:状态','name:模板名称|category:报告类型:安全评估,加固建议,事件调查,日常巡检|sections:章节:概览、资产、风险、建议,事件、证据、处置、结论,接入、采集、任务、健康|period:默认周期:最近 24 小时,最近 7 天,最近 30 天',[
      row('rpttpl1','身份安全评估',{category:'安全评估',sections:'概览、资产、风险、建议',period:'最近 7 天'}),row('rpttpl2','威胁事件复盘',{category:'事件调查',sections:'事件、证据、处置、结论',period:'最近 24 小时'}),row('rpttpl3','平台日常巡检',{domain:'beta',category:'日常巡检',sections:'接入、采集、任务、健康',period:'最近 24 小时'})
    ],[act('编辑章节','edit'),act('预览版式','inspect'),act('生成报告','generate',true)],{primary:{label:'新增报告模板',verb:'create'},kind:'report-templates'}),
    page('reports/library','报告库','查看已生成的报告、调查结论和加固建议，保留范围与时间快照。','name:报告名称|category:报告类型|period:统计周期|generated:生成时间|author:创建人|status:状态','name:报告名称|category:报告类型:安全评估,加固建议,事件调查,日常巡检|period:统计周期',[
      row('report1','总部身份安全周报',{category:'安全评估',period:'10-03 至 10-09',generated:'10-10 00:10 UTC',author:'安全运营员',status:'已生成'}),row('report2','分部巡检摘要',{domain:'beta',category:'日常巡检',period:'10-09',generated:'10-10 00:05 UTC',author:'安全运营员',status:'已生成'})
    ],[act('阅读报告','inspect'),act('下载报告','download')],{primary:null,kind:'reports'}),
    page('work/schedules','周期计划','管理检测、同步和健康计划。暂停或归档不抹去运行历史。','name:计划名称|type:任务类型|interval:执行周期|next:下次执行 UTC|overlap:重叠策略|status:状态','name:计划名称|type:任务类型:健康检查,目录同步,安全检测|interval:执行周期:每 15 分钟,每小时,每日 02:00 UTC|overlap:重叠策略:跳过重叠|retention:历史保留天数',[
      row('sched1','基础设施健康巡检',{type:'健康检查',interval:'每 15 分钟',next:'00:15',overlap:'跳过重叠',retention:'30',status:'暂停'}),row('sched2','每日目录增量同步',{type:'目录同步',interval:'每日 02:00 UTC',next:'02:00',overlap:'跳过重叠',retention:'90',status:'启用'}),row('sched3','分部基线复查',{domain:'beta',type:'安全检测',interval:'每小时',next:'01:00',overlap:'跳过重叠',retention:'90',status:'暂停'})
    ],[act('启用 / 暂停','toggle'),act('变更为新计划','clone'),act('归档计划','archive',true)],{primary:{label:'新增周期计划',verb:'create'},secondary:[act('清理过期消息','cleanup',true)],help:'计划创建后先暂停。修改执行定义会创建新计划，原计划和执行历史保留。'}),
    page('work/notifications','通知配置','按检测模板和事件等级配置通知规则、接收人及发送时间。','name:通知规则|channel:通道|template:关联模板|recipients:接收组|delivery:发送方式|status:状态','name:规则名称|channel:通道:邮件,站内消息|template:关联模板:安全基线,身份异常,全部高危事件|recipients:接收组:安全运营,平台运维|delivery:发送方式:立即发送,延迟 5 分钟,每日 09:00 UTC',[
      row('notif1','高危身份事件提醒',{channel:'站内消息',template:'全部高危事件',recipients:'安全运营',delivery:'立即发送'}),row('notif2','每日基线摘要',{domain:'beta',channel:'邮件',template:'安全基线',recipients:'平台运维',delivery:'每日 09:00 UTC',status:'停用'})
    ],[act('编辑通知','edit'),act('发送测试','test'),act('启用 / 停用','toggle'),act('删除配置','delete',true)],{primary:{label:'新增通知规则',verb:'create'},help:'测试结果仅在站内显示，不向真实邮箱或手机号发送消息。'}),
    page('work/recipients','通知接收人','管理接收分组、联系引用和通知偏好。','name:接收人|team:接收组|address:演示地址|preference:通知偏好|status:状态','name:接收人|team:接收组:安全运营,平台运维|address:演示邮箱|preference:通知偏好:仅高危,全部相关通知',[
      row('recipient1','Alex / 演示',{team:'安全运营',address:'alex@example.test',preference:'仅高危'}),row('recipient2','Morgan / 演示',{domain:'beta',team:'平台运维',address:'morgan@example.test',preference:'全部相关通知'})
    ],[act('编辑','edit'),act('删除','delete',true)],{primary:{label:'新增接收人',verb:'create'},help:'仅接受 example.test 演示邮箱。'}),
    page('work/health','运行健康','关联域连接、采集器、检测和同步异常，按观测时间核对恢复。','name:监控对象|type:类型|observed:最近观测|message:诊断摘要|status:健康状态','name:监控对象|type:类型:域连接,采集器,检测任务,目录同步',[
      row('health1','alpha.example.test',{type:'域连接',observed:'10-10 00:00 UTC',message:'连接与证书检查通过',status:'正常'}),row('health2','总部目录同步',{type:'目录同步',observed:'10-10 00:05 UTC',message:'最新批次已完成',status:'正常'}),row('health3','分部采集器',{domain:'beta',type:'采集器',observed:'10-09 23:43 UTC',message:'心跳超过 15 分钟未更新',status:'异常'})
    ],[act('关联异常','inspect'),act('重新检查','test'),act('提醒开关','alert')],{primary:null,kind:'health'})
  ];
})();
