'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const cp=require('node:child_process');
const root=__dirname;let passed=0;
function test(name,fn){fn();console.log('PASS',name);passed++;}
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const coverageContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'coverage.js'),'utf8'),coverageContext);
const coverage=coverageContext.window.ADTR_COVERAGE;
test('JavaScript syntax',()=>{for(const file of ['app.js','coverage.js','test-browser.cjs'])cp.execFileSync(process.execPath,['--check',path.join(root,file)]);});
test('Complete 209 requirement and 57 group scope',()=>{assert.equal(coverage.features.length,209);assert.equal(new Set(coverage.features.map(f=>f.id)).size,209);assert.equal(coverage.groups.length,57);assert.equal(new Set(coverage.groups.map(g=>g.id)).size,57);assert.equal(coverage.productAccepted,0);const seen=coverage.groups.flatMap(g=>g.featureIds);assert.equal(seen.length,209);assert.equal(new Set(seen).size,209);});
test('No runtime packages, modules or network APIs',()=>{assert(!/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource)\s*\(/.test(source));assert(!/\bimport\s*(?:\(|["'{])/.test(source));assert(!/<script[^>]+type=["']module/.test(html));for(const [,url]of html.matchAll(/(?:src|href)=["']([^"']+)/g))assert(!/^(https?:)?\/\//.test(url),url);});
test('CSP prevents business connections and unsafe form submission',()=>{assert(html.includes("connect-src 'none'"));assert(html.includes("form-action 'none'"));assert(html.includes("object-src 'none'"));});
test('Classic script assets exist for double-click delivery',()=>{for(const [,file]of html.matchAll(/(?:src|href)=["']([^"']+)/g)){if(file.startsWith('#'))continue;assert(fs.existsSync(path.join(root,file)),file);}});
const elements={};function el(id){return elements[id]||(elements[id]={id:id.replace('#',''),innerHTML:'',textContent:'',open:false,checked:false,value:'',dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},focus(){},closest(){return null;},showModal(){this.open=true;},close(){this.open=false;},append(){}});}
const context={console,structuredClone,Blob,URL,Date,Set,Map,Object,JSON,Math,String,Number,Array,CSS:{escape:s=>s},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},queueMicrotask(){},location:{hash:'#/overview'},history:{replaceState(_a,_b,url){context.location.hash=url;},pushState(_a,_b,url){context.location.hash=url;}},document:{activeElement:null,body:{classList:{add(){},remove(){}}},querySelector(q){if(['#app','#dialog','#toast'].includes(q))return el(q);return null;},querySelectorAll(){return[];},addEventListener(){},createElement(){return el('temp');}},window:{ADTR_COVERAGE:coverage,addEventListener(){}}};
let instrumented=source.replace('const timer=setInterval(tick,400);\nreadRoute();',`const timer=0;globalThis.probe={state,ROLES,ASSETS,EVENTS,domainAllowed,visibleAssets,visibleEvents,visibleTasks,visibleAudits,audit,snapshotExport,reconcile,response,confirmation,createTask,taskActions,actions,tick,switchContext};`);
assert(instrumented!==source,'Test-only instrumentation must find the entry point');vm.runInNewContext(instrumented,context);const p=context.probe;
function reset(){p.state.role='operator';p.state.domain='all';p.state.scenario='normal';p.state.epoch=1;p.state.tasks=[];p.state.audits=[];p.state.events=structuredClone(p.EVENTS);p.state.drawer=null;p.state.responseTarget=null;p.state.messagesRead.clear();p.state.downloadRevoked=false;}
test('No implicit admin domain access',()=>{reset();p.state.role='platform';assert.equal(p.visibleAssets().length,0);assert.equal(p.visibleEvents().length,0);assert(p.domainAllowed('platform'));assert(!p.domainAllowed('alpha'));});
test('Forbidden policy denies objects, task counts and audit even on background selectors',()=>{reset();p.state.tasks.push({id:'t',actor:'operator',domain:'alpha'});p.audit('test','t');p.state.scenario='forbidden';assert.equal(p.visibleAssets().length,0);assert.equal(p.visibleEvents().length,0);assert.equal(p.visibleTasks().length,0);assert.equal(p.visibleAudits().length,0);assert(!p.domainAllowed('platform'));});
test('Event e2 carries exact service response target',()=>{reset();p.actions['event-response']({dataset:{id:'e2'}});assert.equal(p.state.responseTarget.assetId,'a4');assert.equal(p.state.responseTarget.eventId,'e2');const rendered=p.response();assert(rendered.includes('demo.service'));assert(rendered.includes('demo-guid-user-002'));assert(rendered.includes('E2'));});
test('Event e3 carries exact group response target',()=>{reset();p.actions['event-response']({dataset:{id:'e3'}});assert.equal(p.state.responseTarget.assetId,'a3');assert(p.response().includes('DEMO-Tier0'));assert(p.response().includes('E3'));});
test('Task intent deduplicates and preserves immutable object snapshot',()=>{reset();const target=Object.freeze({assetId:'a4',name:'demo.service',guid:'demo-guid-user-002',domain:'alpha',version:3,eventId:'e2'});const input={id:'stable',kind:'response',domain:'alpha',role:'operator',epoch:1,scenario:'normal',target};const first=p.createTask(input,'响应演示');const again=p.createTask(input,'响应演示');assert.equal(first.id,again.id);assert.equal(p.state.tasks.length,1);assert.equal(first.target.eventId,'e2');assert.equal(first.target.assetId,'a4');assert.equal(first.safeReplay,false);});
test('Audit rows and export share domain filtering, admin has no bypass',()=>{reset();p.state.tasks.push({id:'beta-task',actor:'operator',domain:'beta'});p.audit('检测','beta-task');assert.equal(p.state.audits[0].domain,'beta');p.state.domain='alpha';assert.equal(p.visibleAudits().length,0);assert.equal(p.snapshotExport('audit','alpha').rows.length,0);p.state.role='platform';p.state.domain='all';assert.equal(p.visibleAudits().length,0);});
test('Old epoch unknown result cannot become succeeded after regrant',()=>{reset();p.state.tasks.push({id:'old',domain:'alpha',actor:'operator',epoch:1,state:'unknown'});p.state.epoch=3;p.reconcile('old');assert.equal(p.state.tasks[0].state,'unknown');assert(!p.taskActions(p.state.tasks[0]).includes('reconcile-task'));});
test('Single attempt and partial failure have no recovery action',()=>{reset();assert(!p.taskActions({id:'one',state:'failed',safeReplay:false}).includes('recover-task'));assert(!p.taskActions({id:'partial',state:'partial_failed',safeReplay:true}).includes('recover-task'));});
test('Download revocation is not reset by domain or scenario navigation',()=>{reset();p.state.downloadRevoked=true;p.switchContext('domain','beta');assert.equal(p.state.downloadRevoked,true);p.switchContext('domain','alpha');assert.equal(p.state.downloadRevoked,true);p.switchContext('scenario','stale');assert.equal(p.state.downloadRevoked,true);});
test('Partial failure is limited to frozen multi-object detection targets',()=>{reset();const t=p.createTask({id:'partial-one',kind:'response',domain:'alpha',role:'operator',epoch:1,scenario:'partial',target:{assetId:'a4',name:'demo.service',domain:'alpha',version:3,eventId:'e2'}},'单对象响应');t.state='running';t.created=Date.now()-8000;p.tick();assert.equal(t.state,'failed');assert(!t.objectResults);assert(t.events.at(-1).text.includes('demo.service / a4'));reset();const targets=[{id:'a1',name:'demo.alex'},{id:'a2',name:'DEMO-DC-01'},{id:'a3',name:'DEMO-Tier0'}];const d=p.createTask({id:'partial-many',kind:'detection',domain:'alpha',role:'operator',epoch:1,scenario:'partial',targets},'多对象检测');d.state='running';d.created=Date.now()-8000;p.tick();assert.equal(d.state,'partial_failed');assert.equal(d.objectResults.map(o=>o.id).join(','),'a1,a2,a3');});
test('Template identity and version are preserved on task input',()=>{reset();const template=Object.freeze({id:'permissions',name:'目录权限评估',version:'1.4.2'});const t=p.createTask({id:'template',kind:'detection',domain:'alpha',role:'operator',epoch:1,scenario:'normal',template},'目录权限评估');assert.equal(t.template.id,'permissions');assert.equal(t.template.version,'1.4.2');assert(source.includes("el.dataset.template||'baseline'"));});
test('Event and audit recovery retain export type, scope and frozen snapshot',()=>{for(const type of ['events','audit']){reset();p.audit('先前操作','DEMO-LOCAL');const snapshot=p.snapshotExport(type,'alpha');const t=p.createTask({id:'export-'+type,kind:'export',exportType:type,dataSnapshot:snapshot,domain:'alpha',role:'operator',epoch:1,scenario:'failed'},'合成'+type+'导出');t.state='failed';p.actions['recover-task']({dataset:{id:t.id}});context.document.querySelector('#dialog')._confirm();const child=p.state.tasks[0];assert.equal(child.parent,t.id);assert.equal(child.exportType,type);assert.equal(child.domain,'alpha');assert.equal(JSON.stringify(child.data),JSON.stringify(t.data));assert.equal(child.data.headers.join(','),type==='events'?'classification,id,event,domain,state':'classification,action,target,result');}});
test('Programmatic event navigation completes before immediate scene changes',()=>{reset();p.actions['event-response']({dataset:{id:'e2'}});assert.equal(p.state.route,'response');assert.equal(context.location.hash,'#/response');p.switchContext('scenario','partial');assert.equal(p.state.route,'response');assert.equal(p.state.responseTarget.assetId,'a4');assert(source.includes("e.target.dataset.filter!=='q'"));});
test('Skip link and update focus are explicitly preserved in source',()=>{assert(source.includes("e.target.closest('.skip-link')"));assert(source.includes("$('#main')?.focus()"));assert(source.includes('function render(){const savedFocus=captureFocus();'));assert(source.includes('restoreFocus(savedFocus)'));});
console.log(`PASS: ${passed} static/VM checks. No browser or production acceptance claimed.`);
