'use strict';
/* Isolated prototype QA. Reuses the repository-pinned Playwright, never the production app. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { once } = require('node:events');
const crypto = require('node:crypto');
const ROOT=__dirname,OUT=path.join(ROOT,'test-results');
fs.mkdirSync(OUT,{recursive:true});
let modulePath=process.env.PLAYWRIGHT_MODULE_PATH||null;
let chromium;
const results=[],errors=[],requests=[];
const contentTypes={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'};
const runtimeFiles=['index.html',...new Set([...fs.readFileSync(path.join(ROOT,'index.html'),'utf8').matchAll(/(?:src|href)=["']([^"']+)["']/g)].map(m=>m[1]).filter(f=>!f.startsWith('#')))];
for(const f of runtimeFiles)assert(/^[a-zA-Z0-9_.-]+\.(?:html|css|js)$/.test(f),'Only adjacent static runtime assets: '+f);
const allowedFiles=new Set(['/',...runtimeFiles.map(f=>'/'+f),'/favicon.ico']);
const server=http.createServer((req,res)=>{let name;try{name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400).end();return;}if(!allowedFiles.has(name)){res.writeHead(404).end();return;}if(name==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.join(ROOT,name==='/'?'index.html':name.slice(1));fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':contentTypes[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);});});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let browser,base;
async function waitFor(fn,timeout=11000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(100);}throw Error('Expected condition did not become true within '+timeout+'ms');}
async function test(name,fn,{mobile=false,file=false}={}){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});const page=await context.newPage();const pageErrors=[],pageRequests=[];page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>pageRequests.push(r.url()));const start=Date.now();try{await page.goto(file?'file://'+path.join(ROOT,'index.html'):base);await page.locator('h1').waitFor();await fn(page,context);assert.deepEqual(pageErrors,[],'No JavaScript page errors');for(const url of pageRequests){if(url.startsWith('file://')&&file)continue;if(!url.startsWith(base))throw Error('Non-local network request: '+url);const route=new URL(url).pathname;assert(allowedFiles.has(route),'Only app static resources requested: '+route);}results.push({name,status:'passed',durationMs:Date.now()-start,requests:pageRequests.length});console.log('PASS',name);}catch(e){results.push({name,status:'failed',durationMs:Date.now()-start,error:e.message});try{await page.screenshot({path:path.join(OUT,'failure-'+String(results.length).padStart(2,'0')+'.png'),fullPage:true});}catch{}console.error('FAIL',name,e.message);}finally{errors.push(...pageErrors);requests.push(...pageRequests);await context.close();}}
async function nav(p,page){await p.goto(base+'#/'+page);const [root,sub]=page.split('/');await waitFor(async()=>await p.locator('.nav-link[aria-current="page"]').getAttribute('href')==='#/'+root);if(sub&&!['asset','event','task','investigation'].includes(sub))await waitFor(async()=>await p.locator('.section-nav a[aria-current="page"]').getAttribute('href')==='#/'+page);else if(!sub)await waitFor(async()=>await p.locator('.section-nav a[aria-current="page"]').count()===0);await p.locator('h1').waitFor();}
async function deniedNav(p,route){await p.goto(base+'#/'+route);await waitFor(async()=>p.url().endsWith('#/'+route)&&(await p.locator('main').innerText()).includes('权限'));}
async function clickAction(p,action){await p.locator('[data-action="'+action+'"]').first().click();}
async function demoOption(p,id,value){if(!await p.locator('#'+id).isVisible())await clickAction(p,'demo-settings');await p.locator('#'+id).selectOption(value);if(await p.locator('#dialog[open]').count())await p.keyboard.press('Escape');}
async function scenario(p,value){await demoOption(p,'scenario',value);}
async function confirm(p){await p.locator('#dialog [data-action="confirm-intent"]').click();}
async function newDetection(p,mode='normal'){await nav(p,'detection');await scenario(p,mode);await clickAction(p,'new-detection');await confirm(p);await p.locator('[data-task-id]').first().waitFor();}
async function taskRow(p){return p.locator('[data-task-id]').first();}
async function stateText(p,value){await waitFor(async()=>((await (await taskRow(p)).innerText()).includes(value)));}
async function responseFromEvent(p,eventId){await nav(p,'threats');await p.locator(`[data-action="event-detail"][data-id="${eventId}"]`).first().click();await p.locator('.drawer [data-action="event-response"]').click();await waitFor(async()=>await p.locator('h1').innerText()==='响应处置');}
async function verifyResponse(p,name,id,event){await responseFromEvent(p,event);const body=await p.locator('main').innerText();assert(body.includes(name));assert(body.includes(event.toUpperCase()));await clickAction(p,'response-confirm');const text=await p.locator('#dialog').innerText();assert(text.includes(name+' / '+id));assert(text.includes(event));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await p.locator('[data-task-id]').first().waitFor();await p.locator('[data-action="task-detail"]').first().click();const detail=await p.locator('.drawer').innerText();assert(detail.includes(name+' / '+id));assert(detail.includes(event+' / v3'));}
(async()=>{try{modulePath=modulePath||require.resolve('playwright',{paths:[path.resolve(ROOT,'../../web')]});({chromium}=require(modulePath));server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{} )});
await test('Nine useful navigation pages and no runtime errors',async p=>{for(const page of ['overview','connections','assets','detection','threats','response','reports','work','admin']){await nav(p,page);assert((await p.locator('main').innerText()).length>160);assert.equal(await p.locator('.nav-link[aria-current="page"]').count(),1);}await nav(p,'overview');await p.screenshot({path:path.join(OUT,'01-overview.png'),fullPage:true});});
await test('Asset search, category, empty results, details and return',async p=>{await nav(p,'assets');await p.locator('[data-filter="q"]').fill('not-found');assert((await p.locator('main').innerText()).includes('没有符合筛选'));await p.locator('[data-filter="q"]').fill('');await p.locator('[data-filter="q"]').pressSequentially('demo.alex');assert.equal(await p.locator('[data-filter="q"]').inputValue(),'demo.alex');assert.equal(await p.locator('tbody tr').count(),2);await p.locator('#domain').selectOption('alpha');await p.locator('[data-filter="type"]').selectOption('用户');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert((await p.locator('.drawer').innerText()).includes('demo-guid-user-001'));await p.screenshot({path:path.join(OUT,'02-asset-detail.png'),fullPage:true});await p.keyboard.press('Escape');assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('[data-filter="type"]').inputValue(),'用户');});
await test('Event e2 preserves service identity through response and task',async p=>verifyResponse(p,'demo.service','a4','e2'));
await test('Event e3 preserves group target through response and task',async p=>verifyResponse(p,'DEMO-Tier0','a3','e3'));
await test('Response confirmation requires both checks and freezes exact object',async p=>{await responseFromEvent(p,'e2');await clickAction(p,'response-confirm');await confirm(p);assert((await p.locator('#confirm-error').innerText()).includes('请先'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();assert.equal(await p.locator('#confirm-error').innerText(),'');await p.screenshot({path:path.join(OUT,'03-response-confirm.png'),fullPage:true});await p.keyboard.press('Escape');assert.equal(await p.locator('#dialog[open]').count(),0);await nav(p,'work');assert.equal(await p.locator('[data-task-id]').count(),0);});
await test('Single-intent repeated click and Enter create only one task',async p=>{await nav(p,'detection');await clickAction(p,'new-detection');await p.locator('#dialog [data-action="confirm-intent"]').focus();await p.keyboard.press('Enter');await p.keyboard.press('Enter');await p.locator('[data-task-id]').first().waitFor();assert.equal(await p.locator('[data-task-id]').count(),1);await stateText(p,'已完成');});
await test('Queued cancellation uses zero execution attempts',async p=>{await newDetection(p);await p.locator('[data-action="cancel-task"]').first().click();const row=await (await taskRow(p)).innerText();assert(row.includes('已取消'));assert(row.includes('0 / 3'));});
await test('Running cancellation waits for executor confirmation',async p=>{await newDetection(p);await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();assert((await (await taskRow(p)).innerText()).includes('已请求取消'));await stateText(p,'已取消');});
await test('Cancel race retains success and records race event',async p=>{await newDetection(p,'cancel-race');await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();await stateText(p,'已完成');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('任务在取消请求生效前已完成'));assert(text.includes('已记录取消请求'));assert(text.includes('1 / 3'));assert.equal(await p.locator('[data-task-id]').count(),1);});
await test('Lost cancellation remains unconfirmed rather than cancelled',async p=>{await newDetection(p,'cancel-lost');await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();await stateText(p,'失败');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('执行停止尚未确认'));assert(text.includes('未收到执行端确认'));assert(!text.includes('已收到执行结束确认'));assert(!text.includes('取消完成。'));assert(!text.includes('已取消'));});
await test('Unknown result is reconciled without duplicate task',async p=>{await newDetection(p,'unknown');await stateText(p,'结果待核对');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);await p.locator('[data-action="reconcile-task"]').first().click();assert.equal(await p.locator('[data-task-id]').count(),1);assert((await (await taskRow(p)).innerText()).includes('已完成'));});
await test('Regrant cannot reconcile an old authorization epoch',async p=>{await newDetection(p,'unknown');await stateText(p,'结果待核对');await demoOption(p,'role','viewer');await demoOption(p,'role','operator');assert.equal(await p.locator('[data-action="reconcile-task"]').count(),0);assert((await (await taskRow(p)).innerText()).includes('结果待核对'));});
await test('Safe failed task recovery creates an authorized child',async p=>{await newDetection(p,'failed');await stateText(p,'失败');await p.locator('[data-action="recover-task"]').first().click();await confirm(p);assert.equal(await p.locator('[data-task-id]').count(),2);await stateText(p,'已完成');await p.locator('[data-action="task-detail"]').first().click();assert((await p.locator('.drawer').innerText()).includes('父任务'));});
await test('Single-attempt connection failure has no generic recover',async p=>{await nav(p,'connections');await scenario(p,'failed');await p.locator('[data-action="diagnose"][data-domain="alpha"]').click();await confirm(p);await stateText(p,'失败');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);});
await test('Partial failure preserves object outcomes and prohibits full recovery',async p=>{await newDetection(p,'partial');await stateText(p,'部分失败');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('demo.alex / a1：成功'));assert(text.includes('DEMO-DC-01 / a2：失败'));assert(text.includes('DEMO-Tier0 / a3：结果不确定'));assert(text.includes('不能整批重试'));});
await test('Single-object response never invents a partial-failure target set',async p=>{await responseFromEvent(p,'e2');await scenario(p,'partial');await clickAction(p,'response-confirm');assert((await p.locator('#dialog').innerText()).includes('demo.service / a4'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await stateText(p,'失败');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('demo.service / a4'));assert(text.includes('仅报告已确认对象'));assert(text.includes('e2 / v3'));assert(text.includes('1 / 1'));assert.equal(await p.locator('[data-action="recover-task"]').count(),0);assert(!text.includes('DEMO-OBJ'));assert(!text.includes('逐对象结果'));});
await test('Template card preselects and confirmation freezes chosen ID and version',async p=>{await nav(p,'detection');await p.locator('[data-template="identity"]').click();assert.equal(await p.locator('#detect-template').inputValue(),'identity');await p.locator('#detect-template').selectOption('permissions');await confirm(p);await p.locator('[data-task-id]').first().waitFor();await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('目录权限评估'));assert(text.includes('permissions / v1.4.2'));});
await test('Directory v2 needs both switches and independent grant',async p=>{await nav(p,'connections');await p.locator('[data-action="directory-auth"][data-domain="alpha"]').click();await p.locator('#directory-v2').check();await confirm(p);assert((await p.locator('#directory-error').innerText()).includes('三个条件'));await p.locator('#directory-master').check();await p.locator('#directory-grant').check();await confirm(p);await waitFor(async()=>await p.locator('h1').innerText()==='目录资产');assert.equal(await p.locator('h1').innerText(),'目录资产');assert.equal(await p.locator('#domain').inputValue(),'alpha');});
await test('Admin without domain has no private list, counts or audit objects',async p=>{await newDetection(p);await demoOption(p,'role','platform');await nav(p,'assets/asset/a1');assert((await p.locator('main').innerText()).includes('没有此功能权限'));assert.equal(await p.locator('[data-action="asset-detail"]').count(),0);assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('.nav-count').count(),0);await nav(p,'admin');await p.locator('[data-action="admin-tab"][data-tab="audit"]').click();assert(!(await p.locator('main').innerText()).includes('DEMO-TASK-'));});
await test('Forbidden scene stays fail closed through running timer and deep link',async p=>{await newDetection(p);const id=await p.locator('[data-task-id]').first().getAttribute('data-task-id');await scenario(p,'forbidden');await nav(p,'work/task/'+id);await sleep(2200);assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('.nav-count').count(),0);assert(!(await p.locator('main').innerText()).includes(id));});
await test('Unread count is scoped to visible domain messages',async p=>{await nav(p,'work');await p.locator('#domain').selectOption('alpha');await p.locator('[data-action="work-tab"][data-tab="messages"]').click();while(await p.locator('[data-action="mark-read"]:not(:disabled)').count()){await p.locator('[data-action="mark-read"]:not(:disabled)').first().click();}await p.locator('#domain').selectOption('beta');assert((await p.locator('main').innerText()).includes('4 条未读'));assert.equal(await p.locator('[data-action="mark-read"]:not(:disabled)').count(),4);await p.locator('#domain').selectOption('alpha');assert.equal(await p.locator('[data-action="mark-read"]:not(:disabled)').count(),0);});
await test('Export CSV is synthetic and download revocation survives navigation',async p=>{await nav(p,'assets');await p.locator('#domain').selectOption('alpha');await clickAction(p,'export-assets');await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const download=await promise;const file=await download.path();const csv=fs.readFileSync(file,'utf8');assert(csv.includes('SYNTHETIC'));assert(!csv.includes('beta.example.test'));assert(download.suggestedFilename().startsWith('ADTR_SYNTHETIC_'));await clickAction(p,'revoke-download');await p.locator('#domain').selectOption('beta');await p.locator('#domain').selectOption('alpha');let triggered=false;const listener=()=>{triggered=true;};p.on('download',listener);await p.locator('[data-action="download-task"]').first().click();await sleep(500);assert(!triggered,'Revocation must persist');assert((await p.locator('#toast').innerText()).includes('失效'));p.off('download',listener);});
for(const [kind,header]of [['events','classification,id,event,domain,state'],['audit','classification,action,target,result']]){await test('Failed '+kind+' export recovery preserves original CSV schema',async p=>{await nav(p,'reports');await p.locator('#domain').selectOption('alpha');await scenario(p,'failed');await clickAction(p,'export-'+kind);await confirm(p);await stateText(p,'失败');await p.locator('[data-action="recover-task"]').first().click();await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const d=await promise;const csv=fs.readFileSync(await d.path(),'utf8').replace(/^\uFEFF/,'');assert.equal(csv.split('\r\n')[0],header);assert(!csv.includes('demo-guid'));assert(!csv.includes('beta.example.test'));});}
await test('Permission form denies write without read and records explicit confirmation',async p=>{await nav(p,'admin');await p.locator('#grant-read').uncheck();await p.locator('#grant-write').check();await clickAction(p,'save-grants');assert.equal(await p.locator('#dialog[open]').count(),0);assert((await p.locator('#toast').innerText()).includes('依赖'));await p.locator('#grant-read').check();await clickAction(p,'save-grants');await confirm(p);assert((await p.locator('#grant-error').innerText()).includes('请确认'));await p.locator('#grant-proof').check();await confirm(p);assert(await p.locator('#grant-write').isChecked());});
await test('History, modal dismissal and skip link never replay actions or navigate away',async p=>{await nav(p,'assets');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();await p.goBack();assert.equal(await p.locator('.drawer').count(),0);await p.goForward();await p.locator('.drawer').waitFor();await p.locator('[data-action="close-drawer"]').first().click();await p.locator('.skip-link').focus();await p.keyboard.press('Enter');assert(p.url().endsWith('#/assets'));assert.equal(await p.evaluate(()=>document.activeElement.id),'main');await nav(p,'detection');await clickAction(p,'new-detection');await p.keyboard.press('Escape');await nav(p,'work');assert.equal(await p.locator('[data-task-id]').count(),0);});
await test('Task updates preserve keyboard focus in table and drawer',async p=>{await newDetection(p);await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().focus();await sleep(700);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'cancel-task');await p.locator('[data-action="task-detail"]').first().click();await p.locator('.drawer [aria-label="关闭详情"]').focus();await sleep(700);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'关闭详情');await p.keyboard.press('Escape');assert.equal(await p.locator('.drawer').count(),0);});
await test('Report export updates preserve focused controls',async p=>{await nav(p,'reports');await clickAction(p,'export-assets');await confirm(p);await stateText(p,'运行中');await p.locator('[data-action="revoke-download"]').focus();await sleep(800);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'revoke-download');});
await test('Cross-domain audit export contains no foreign scoped records',async p=>{await nav(p,'detection');await p.locator('#domain').selectOption('beta');await clickAction(p,'new-detection');await confirm(p);await p.locator('[data-task-id]').first().waitFor();const betaId=await p.locator('[data-task-id]').first().getAttribute('data-task-id');await p.locator('#domain').selectOption('alpha');await nav(p,'admin');await p.locator('[data-action="admin-tab"][data-tab="audit"]').click();assert(!(await p.locator('main').innerText()).includes(betaId));await nav(p,'reports');await clickAction(p,'export-audit');await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const d=await promise;const csv=fs.readFileSync(await d.path(),'utf8');assert(!csv.includes(betaId));assert(!csv.includes('beta.example.test'));});
await test('Drawer keyboard focus remains contained',async p=>{await nav(p,'assets');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();await p.locator('.drawer').waitFor();assert(await p.locator('.shell').evaluate(el=>el.inert));await waitFor(()=>p.evaluate(()=>!!document.activeElement.closest('.drawer')));for(const key of ['Tab','Shift+Tab'])for(let i=0;i<18;i++){await p.keyboard.press(key);assert(await p.evaluate(()=>!!document.activeElement.closest('.drawer')));}await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.dataset.id),'a1');});
await test('Empty, read-error, forbidden and stale views are distinguishable',async p=>{await nav(p,'assets');await scenario(p,'empty');assert((await p.locator('main').innerText()).includes('暂无记录'));await scenario(p,'error');assert((await p.locator('main').innerText()).includes('暂时无法读取'));await clickAction(p,'retry-page');assert((await p.locator('main').innerText()).includes('已观测目录对象'));await scenario(p,'forbidden');assert((await p.locator('main').innerText()).includes('没有业务访问权限'));await scenario(p,'stale');assert((await p.locator('.state-banner').innerText()).includes('数据观测已过期'));assert((await p.locator('.state-banner').innerText()).includes('不代表当前在线'));});
await test('390px layout has accessible navigation and no page-level horizontal overflow',async p=>{await p.screenshot({path:path.join(OUT,'04-mobile.png'),fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})).slice(0,12)}))));await clickAction(p,'mobile-menu');await p.locator('.sidebar [href="#/assets"]').click();await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})).slice(0,12)}))));await p.locator('.drawer [aria-label="关闭详情"]').click();await clickAction(p,'mobile-menu');await p.locator('.sidebar [href="#/response"]').click();await clickAction(p,'response-confirm');assert(await p.locator('#dialog [data-action="confirm-intent"]').isVisible());},{mobile:true});
await test('Direct file opening works without modules, fetch or a server',async p=>{assert.equal(await p.locator('h1').innerText(),'安全工作台');await p.locator('.nav-link[href="#/assets"]').click();await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert((await p.locator('.drawer').innerText()).includes('demo.alex'));},{file:true});
const businessRoutes={connections:['sources','accounts','deployment','collectors','collection','protection','remote','sync'],assets:['sync','permissions','sensitive','relations','risk','trust'],detection:['baseline','vulnerabilities','behavior','passwords','rules','learning','templates','allowlists'],threats:['paths','behavior','search','honeypots'],response:['policies','allowlist','history'],reports:['templates','library'],work:['schedules','notifications','recipients','health'],admin:['profile','accounts','mfa','users','roles','resources','audit','integrations','system','license','settings','services','diagnostics','install']};
const internalCopy=/AD-F-\d{3}|产品验收|覆盖说明|规划说明|固定夹具|后续验收|safeReplay|demo-epoch|未实现|实现说明|独立验收|原型没有|本原型|夹具|synthetic_|demonstration-only|EXTERNAL_EFFECT|真实外部副作用|通用recover/;
for(const [section,pages] of Object.entries(businessRoutes))await test('Discoverable '+section+' business pages without development commentary',async p=>{await nav(p,section);for(const sub of pages){const route=section+'/'+sub;const entry=p.locator(`a[href="#/${route}"]`).first();assert(await entry.count(),'Missing discoverable sub-navigation: '+route);await entry.click();await waitFor(async()=>await p.locator('.section-nav a[aria-current="page"]').getAttribute('href')==='#/'+route);const body=await p.locator('main').innerText();assert(!internalCopy.test(body),'Development commentary on '+route+': '+body.match(internalCopy));assert(!/敬请期待|功能建设中|即将上线/.test(body),'Placeholder on '+route);assert((await p.locator('main table,main form,main dl,main .chart,main input,main select').count())>0,'No business content on '+route);await nav(p,section);}});
await test('All main product pages omit review and implementation commentary',async p=>{for(const section of ['overview',...Object.keys(businessRoutes)]){await nav(p,section);const body=await p.locator('main').innerText();assert(!internalCopy.test(body),'Development commentary on '+section+': '+body.match(internalCopy));}});
await test('Narrow-screen business navigation and key domains remain within viewport',async p=>{for(const route of ['connections/collectors','detection/rules','threats/paths','work/notifications','admin/users','admin/license']){await nav(p,route);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page overflow: '+route);}await nav(p,'detection/rules');await p.screenshot({path:path.join(OUT,'05-mobile-rules.png'),fullPage:true});},{mobile:true});
async function biz(p,route,verb,id='',intent=null){const selector=`[data-action="biz-action"][data-page="${route}"][data-verb="${verb}"][data-id="${id}"]${intent?`[data-intent="${intent}"]`:''}`;await p.locator(selector).first().click();}
async function bizConfirm(p){await p.locator('#biz-confirm-check').check();await confirm(p);}
async function cleanDialog(p){assert(!internalCopy.test(await p.locator('#dialog').innerText()),'Development commentary in business dialog');}
await test('Rule condition editor invalidates test, denies premature publish, then publishes tested version',async p=>{await nav(p,'detection/rules');await biz(p,'detection/rules','edit','rule2');await cleanDialog(p);await p.locator('#biz-field-value').fill('9999');await p.locator('#biz-field-threshold').fill('2');assert((await p.locator('#rule-preview').innerText()).includes('9999'));await clickAction(p,'biz-save');await biz(p,'detection/rules','test','rule2');assert((await p.locator('[data-record-id="rule2"]').innerText()).includes('测试失败'));await biz(p,'detection/rules','activate','rule2');assert.equal(await p.locator('#dialog[open]').count(),0);await biz(p,'detection/rules','edit','rule2');await p.locator('#biz-field-value').fill('4624');await p.locator('#biz-field-threshold').fill('2');await clickAction(p,'biz-save');await biz(p,'detection/rules','test','rule2');assert((await p.locator('[data-record-id="rule2"]').innerText()).includes('测试失败'));await biz(p,'detection/rules','edit','rule2');await p.locator('#biz-field-threshold').fill('1');await clickAction(p,'biz-save');await biz(p,'detection/rules','test','rule2');assert((await p.locator('[data-record-id="rule2"]').innerText()).includes('测试通过'));await biz(p,'detection/rules','activate','rule2');await bizConfirm(p);assert((await p.locator('[data-record-id="rule2"]').innerText()).includes('已发布'));await p.screenshot({path:path.join(OUT,'06-rules.png'),fullPage:true});});
await test('Recipient form validation, save, cancelled edit and scoped persistence',async p=>{await nav(p,'work/recipients');await biz(p,'work/recipients','create');await p.locator('#biz-field-name').fill('演示审计员');await p.locator('#biz-field-address').fill('invalid');await clickAction(p,'biz-save');assert((await p.locator('#biz-error').innerText()).includes('example.test'));await p.locator('#biz-field-address').fill('reviewer@example.test');await clickAction(p,'biz-save');const row=p.locator('[data-record-id]').filter({hasText:'演示审计员'});const id=await row.getAttribute('data-record-id');await biz(p,'work/recipients','edit',id);await p.locator('#biz-field-name').fill('不应保存');await p.keyboard.press('Escape');assert.equal(await p.locator('[data-record-id]').filter({hasText:'不应保存'}).count(),0);await nav(p,'overview');await nav(p,'work/recipients');assert((await p.locator('[data-record-id="'+id+'"]').innerText()).includes('reviewer@example.test'));await p.locator('#domain').selectOption('beta');assert.equal(await p.locator('[data-record-id="'+id+'"]').count(),0);});
await test('Collector ignored alarm retains unhealthy observation',async p=>{await nav(p,'connections/collectors');await biz(p,'connections/collectors','alert','collector2');assert((await p.locator('[data-record-id="collector2"]').innerText()).includes('心跳异常'));await biz(p,'connections/collectors','inspect','collector2');await cleanDialog(p);assert((await p.locator('#dialog').innerText()).includes('忽略'));assert((await p.locator('#dialog').innerText()).includes('心跳异常'));await p.keyboard.press('Escape');await p.screenshot({path:path.join(OUT,'07-collectors.png'),fullPage:true});});
await test('Advanced query values change real result rows and preserve domain boundaries',async p=>{await nav(p,'threats/search');await p.locator('#query-value').fill('4662');await clickAction(p,'biz-search');assert((await p.locator('#dialog').innerText()).includes('目录对象访问'));await cleanDialog(p);await p.keyboard.press('Escape');await p.locator('#query-value').fill('9999');await clickAction(p,'biz-search');assert((await p.locator('#dialog').innerText()).includes('没有匹配'));await p.keyboard.press('Escape');await p.locator('#domain').selectOption('alpha');await p.locator('#query-value').fill('4625');await clickAction(p,'biz-search');assert(!(await p.locator('#dialog').innerText()).includes('DEMO-BETA-DC'));});
await test('Report generation creates immutable typed instance and actual report download',async p=>{await nav(p,'reports/templates');await biz(p,'reports/templates','generate','rpttpl2');await bizConfirm(p);await nav(p,'reports/library');const row=p.locator('[data-record-id]').filter({hasText:'威胁事件复盘'});const id=await row.getAttribute('data-record-id');assert(id);await biz(p,'reports/library','inspect',id);await cleanDialog(p);const body=await p.locator('#dialog').innerText();assert(body.includes('威胁事件复盘'));assert(body.includes('证据'));assert(await p.locator('#dialog-title').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'Report opens at its title, not scrolled to footer');assert(await p.locator('#dialog [aria-label="关闭弹窗"]').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'Report close control remains in viewport');await p.screenshot({path:path.join(OUT,'08-report-preview.png'),fullPage:true});await p.keyboard.press('Escape');const download=p.waitForEvent('download');await biz(p,'reports/library','download',id);const d=await download;assert(d.suggestedFilename().endsWith('.html'));const text=fs.readFileSync(await d.path(),'utf8');assert(text.includes('威胁事件复盘'));assert(text.includes('证据'));assert(!text.includes('beta.example.test'));});
await test('Schedule modification creates separate paused identity without mutating original definition',async p=>{await nav(p,'work/schedules');const before=await p.locator('[data-record-id="sched1"]').innerText();await biz(p,'work/schedules','clone','sched1');await p.locator('#biz-field-name').fill('新健康巡检');await p.locator('#biz-field-interval').selectOption('每小时');await clickAction(p,'biz-save');assert.equal(await p.locator('[data-record-id="sched1"]').innerText(),before);const row=p.locator('[data-record-id]').filter({hasText:'新健康巡检'});assert((await row.innerText()).includes('暂停'));assert((await row.innerText()).includes('每小时'));const id=await row.getAttribute('data-record-id');assert.notEqual(id,'sched1');await biz(p,'work/schedules','toggle',id);assert((await p.locator('[data-record-id="'+id+'"]').innerText()).includes('启用'));});
await test('Business writes are disabled for readonly viewer and foreign-domain records disappear',async p=>{await nav(p,'connections/collectors');await demoOption(p,'role','viewer');assert.equal(await p.locator('[data-record-id="collector2"]').count(),0);for(const el of await p.locator('[data-action="biz-action"][data-verb="upgrade"]').all())assert(await el.isDisabled());await nav(p,'work/recipients');assert(await p.locator('[data-action="biz-action"][data-verb="create"]').isDisabled());await demoOption(p,'role','platform');await deniedNav(p,'connections/collectors');assert.equal(await p.locator('[data-record-id]').count(),0);assert(!(await p.locator('main').innerText()).includes('DEMO-DC-01'));});

await test('Bulk collector upgrade requires explicit selection rather than all visible records',async p=>{await nav(p,'connections/collectors');const button=p.locator('[data-action="biz-action"][data-page="connections/collectors"][data-verb="upgrade"][data-id=""]');if(!await button.isDisabled()){await button.click();assert.equal(await p.locator('#dialog[open]').count(),0,'Empty selection cannot open mass confirmation');}assert((await p.locator('[data-record-id="collector2"]').innerText()).includes('心跳异常'));await p.locator('[data-biz-select="connections/collectors"][data-id="collector1"]').check();await button.click();const text=await p.locator('#dialog').innerText();assert(text.includes('总部采集器'));assert(!text.includes('分部采集器'));await p.keyboard.press('Escape');assert((await p.locator('[data-record-id="collector1"]').innerText()).includes('在线'));});
await test('Readonly investigator cannot deep-link platform user or role records',async p=>{await demoOption(p,'role','viewer');for(const route of ['admin/users','admin/roles','admin/resources','admin/integrations','admin/license']){await deniedNav(p,route);assert.equal(await p.locator('[data-record-id]').count(),0,'Management records leaked through '+route);assert((await p.locator('main').innerText()).includes('权限'),'Missing access denial on '+route);}});

await test('Rule testing evaluates non-event field values rather than unconditional success',async p=>{await nav(p,'detection/rules');await biz(p,'detection/rules','edit','rule2');await p.locator('#biz-field-field').selectOption('account_name');await p.locator('#biz-field-operator').selectOption('等于');await p.locator('#biz-field-value').fill('no-such-demo-identity');await p.locator('#biz-field-threshold').fill('1');await clickAction(p,'biz-save');await biz(p,'detection/rules','test','rule2');assert((await p.locator('[data-record-id="rule2"]').innerText()).includes('测试失败'));await biz(p,'detection/rules','activate','rule2');assert.equal(await p.locator('#dialog[open]').count(),0);});
await test('MFA enrollment cannot skip verification or recovery acknowledgment',async p=>{await nav(p,'admin/mfa');await biz(p,'admin/mfa','toggle','mfa-new','mfa_toggle');await cleanDialog(p);await confirm(p);await confirm(p);assert((await p.locator('#admin-error').innerText()).includes('验证'));assert(await p.locator('#admin-mfa-proof').count());await p.locator('#admin-mfa-proof').check();await confirm(p);await confirm(p);assert((await p.locator('#admin-error').innerText()).includes('恢复'));await p.locator('#admin-mfa-recovery').check();await confirm(p);assert((await p.locator('[data-record-id="mfa-new"]').innerText()).includes('已启用'));});
await test('License preview is read-only and mismatched device cannot activate',async p=>{await nav(p,'admin/license');const before=await p.locator('[data-record-id="license-renewal"]').innerText();await biz(p,'admin/license','inspect','license-renewal','license_preview');await cleanDialog(p);assert((await p.locator('#dialog').innerText()).includes('授权预览'));await p.keyboard.press('Escape');assert.equal(await p.locator('[data-record-id="license-renewal"]').innerText(),before);await biz(p,'admin/license','activate','license-mismatch','license_activate');const text=await p.locator('body').innerText();assert(text.includes('不匹配'));assert(!(await p.locator('[data-record-id="license-mismatch"]').innerText()).includes('已激活'));await p.screenshot({path:path.join(OUT,'09-license-check.png'),fullPage:true});});
await test('Platform installation requires current precheck and separate impact confirmation',async p=>{await nav(p,'admin/install');await biz(p,'admin/install','activate','installation-new','installation_start');assert((await p.locator('#dialog').innerText()).includes('条件未满足'));await p.keyboard.press('Escape');await biz(p,'admin/install','test','installation-new','installation_precheck');for(let i=0;i<3;i++)await confirm(p);assert((await p.locator('#dialog').innerText()).includes('检查通过'));await confirm(p);await biz(p,'admin/install','activate','installation-new','installation_start');assert((await p.locator('#dialog').innerText()).includes('确认安装范围'));await confirm(p);assert((await p.locator('#admin-error').innerText()).includes('确认'));await p.locator('#biz-confirm-check').check();await confirm(p);await waitFor(async()=>(await p.locator('[data-record-id="installation-new"]').innerText()).includes('已完成'));await biz(p,'admin/install','inspect','installation-new','installation_steps');assert((await p.locator('#dialog').innerText()).includes('运行'));await cleanDialog(p);await p.screenshot({path:path.join(OUT,'10-installation.png'),fullPage:true});});
await test('Current user cannot delete or disable their own identity',async p=>{await nav(p,'admin/users');for(const [verb,intent]of [['delete','delete_user'],['toggle','user_toggle']]){await biz(p,'admin/users',verb,'user-operator',intent);assert((await p.locator('body').innerText()).includes('当前'));assert.equal(await p.locator('#biz-confirm-check').count(),0);if(await p.locator('#dialog[open]').count())await p.keyboard.press('Escape');assert((await p.locator('[data-record-id="user-operator"]').innerText()).includes('启用'));}});

await test('Personal account and MFA selectors reveal only authorized identities',async p=>{await demoOption(p,'role','viewer');for(const [route,intent]of [['admin/accounts','select_account'],['admin/mfa','select_mfa_account']]){await nav(p,route);await biz(p,route,'create','',intent);const text=await p.locator('#dialog').innerText();assert(!text.includes('demo.operator'));assert(!text.includes('demo.maintainer'));assert(!text.includes('demo.new'));await p.keyboard.press('Escape');}});

await test('Completed directory synchronization can run again with a new batch and task',async p=>{await nav(p,'assets/sync');await biz(p,'assets/sync','sync','sync1');await bizConfirm(p);await p.locator('[data-action="biz-action"][data-page="assets/sync"][data-verb="sync"][data-id="sync1"]').focus();await sleep(2400);assert.equal(await p.evaluate(()=>document.activeElement.dataset.verb),'sync','Background business update must preserve exact action focus');await waitFor(async()=>(await p.locator('[data-record-id="sync1"]').innerText()).includes('已完成'));const first=await p.locator('[data-record-id="sync1"]').innerText();await biz(p,'assets/sync','sync','sync1');await bizConfirm(p);await waitFor(async()=>(await p.locator('[data-record-id="sync1"]').innerText()).includes('排队中'));await waitFor(async()=>(await p.locator('[data-record-id="sync1"]').innerText()).includes('已完成'));assert.notEqual(await p.locator('[data-record-id="sync1"]').innerText(),first);await nav(p,'work');assert.equal(await p.locator('[data-task-id]').count(),2);});
await test('Response restoration keeps its terminal result across later executor ticks',async p=>{await responseFromEvent(p,'e2');await clickAction(p,'response-confirm');await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await stateText(p,'已完成');await nav(p,'response/history');const row=p.locator('[data-record-id]').filter({hasText:'demo.service'});const id=await row.getAttribute('data-record-id');assert(id);await biz(p,'response/history','restore',id);await bizConfirm(p);await waitFor(async()=>(await p.locator('[data-record-id="'+id+'"]').innerText()).includes('已恢复'));await sleep(1000);assert((await p.locator('[data-record-id="'+id+'"]').innerText()).includes('已恢复'));await nav(p,'overview');await nav(p,'response/history');assert((await p.locator('[data-record-id="'+id+'"]').innerText()).includes('已恢复'));});

await test('Event evidence drawers contain product evidence without implementation annotations',async p=>{await nav(p,'threats');await p.locator('[data-action="soc-status"][data-value="all"]').click();for(const id of ['e1','e2','e3','e4','e5']){await p.locator('[data-action="event-detail"][data-id="'+id+'"]').first().click();const text=await p.locator('.drawer').innerText();assert(!internalCopy.test(text),id+': '+text.match(internalCopy));await p.keyboard.press('Escape');}});
for(const mode of ['normal','failed','unknown'])await test('Task '+mode+' detail omits development annotations while retaining result',async p=>{await newDetection(p,mode);await stateText(p,mode==='normal'?'已完成':mode==='failed'?'失败':'结果待核对');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(!internalCopy.test(text),mode+': '+text.match(internalCopy));assert(text.includes('执行时间线'));});

await test('First-login flow binds the selected identity instead of inheriting administrator access',async p=>{await nav(p,'admin/accounts');await biz(p,'admin/accounts','toggle','account-new','session_toggle');await confirm(p);await confirm(p);await confirm(p);assert((await p.locator('#admin-error').innerText()).includes('验证'));await p.locator('#admin-login-proof').check();await confirm(p);await confirm(p);assert((await p.locator('.profile-label').innerText()).includes('新用户'));await deniedNav(p,'assets');assert.equal(await p.locator('[data-action="asset-detail"]').count(),0);});
await test('Logout and browser back stay locked until the same login verification finishes',async p=>{await nav(p,'assets');await nav(p,'admin/accounts');await biz(p,'admin/accounts','toggle','account-operator','session_toggle');await bizConfirm(p);assert((await p.locator('main').innerText()).includes('已锁定'));await p.goBack();assert((await p.locator('main').innerText()).includes('已锁定'));assert.equal(await p.locator('[data-action="asset-detail"]').count(),0);await clickAction(p,'resume-session');await confirm(p);await confirm(p);assert((await p.locator('#admin-error').innerText()).includes('验证'));assert((await p.locator('main').innerText()).includes('已锁定'));await p.locator('#admin-login-proof').check();await confirm(p);await confirm(p);assert(!(await p.locator('main').innerText()).includes('已锁定'));assert((await p.locator('.profile-label').innerText()).includes('安全负责人'));});

await test('Policy edit binds stable asset identity, action and policy through response task',async p=>{await nav(p,'response/policies');const disabledPolicy=p.locator('[data-action="biz-action"][data-page="response/policies"][data-verb="respond"][data-id="policy2"]');if(!await disabledPolicy.isDisabled())await disabledPolicy.click();assert(p.url().endsWith('#/response/policies'),'Disabled policy must not enter execution');await biz(p,'response/policies','edit','policy1');await p.locator('#biz-field-assetId').selectOption('a2');await p.locator('#biz-field-effect').selectOption('限制设备访问');await clickAction(p,'biz-save');await biz(p,'response/policies','respond','policy1');await waitFor(async()=>await p.locator('h1').innerText()==='响应处置');await clickAction(p,'response-confirm');const body=await p.locator('#dialog').innerText();assert(body.includes('DEMO-DC-01'));assert(body.includes('限制设备访问'));assert(body.includes('policy1'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await stateText(p,'已完成');await p.locator('[data-action="task-detail"]').first().click();const detail=await p.locator('.drawer').innerText();assert(detail.includes('a2'));assert(detail.includes('限制设备访问'));assert(detail.includes('policy1'));});

await test('SOC workbench puts a real actionable queue in the first viewport',async p=>{await p.setViewportSize({width:1440,height:900});await nav(p,'overview');const row=p.locator('[data-soc-event]').first();const rect=await row.boundingBox();assert(rect&&rect.y+rect.height<900,'First actionable alert must be above fold');await p.locator('[data-action="soc-preset"][data-value="high-open"]').click();await waitFor(async()=>p.url().endsWith('#/threats'));for(const row of await p.locator('[data-soc-event]').all()){const text=await row.innerText();assert(text.includes('高危'));assert(text.includes('待调查'));}await nav(p,'overview');await clickAction(p,'soc-reset');await p.screenshot({path:path.join(OUT,'11-soc-workbench.png'),fullPage:true});});
await test('SOC queue search and sorting survive investigation return with row focus',async p=>{await nav(p,'threats');await p.locator('#soc-query').fill('服务身份从新设备发起认证');await p.locator('[data-soc-filter="sort"]').selectOption('oldest');assert.equal(await p.locator('[data-soc-event]').count(),1);await p.locator('[data-action="event-detail"][data-id="e2"]').click();await clickAction(p,'soc-open');await waitFor(async()=>p.url().endsWith('/investigation/e2'));await clickAction(p,'soc-return');await waitFor(async()=>p.url().endsWith('#/threats'));assert.equal(await p.locator('#soc-query').inputValue(),'服务身份从新设备发起认证');assert.equal(await p.locator('[data-soc-filter="sort"]').inputValue(),'oldest');assert.equal(await p.evaluate(()=>document.activeElement.dataset.id),'e2');await clickAction(p,'soc-reset');assert((await p.locator('[data-soc-event]').count())>1);});
await test('SOC investigation preserves identity and links entity relationships to evidence',async p=>{await nav(p,'threats/investigation/e2');assert((await p.locator('.soc-case-header').innerText()).includes('E2'));await p.locator('[data-action="soc-edge"]').first().click();assert.equal(await p.locator('.soc-evidence-panel tbody tr').count(),1);assert((await p.locator('.soc-entity-detail').innerText()).includes('demo.service'));await clickAction(p,'soc-asset');assert((await p.locator('.drawer').innerText()).includes('demo.service'));await p.keyboard.press('Escape');assert(p.url().endsWith('/investigation/e2'));await clickAction(p,'soc-clear-edge');assert((await p.locator('.soc-evidence-panel tbody tr').count())>1);await p.screenshot({path:path.join(OUT,'12-soc-investigation.png'),fullPage:true});await p.reload();await p.locator('.soc-case-header').waitFor();assert((await p.locator('.soc-case-header').innerText()).includes('E2'));});
await test('SOC different evidence topology and missing attribution are explicit',async p=>{await nav(p,'threats/investigation/e1');assert((await p.locator('.soc-edge-list').innerText()).includes('成员关系'));await nav(p,'threats/investigation/e3');assert((await p.locator('main').innerText()).includes('变更发起身份未采集'));assert.equal(await p.locator('[data-action="soc-edge"]').count(),0);assert((await p.locator('main').innerText()).includes('未采集到'));});
for(const mode of ['normal','unknown'])await test('SOC investigation keeps '+mode+' response outcome inside its case',async p=>{await nav(p,'threats/investigation/e2');await scenario(p,mode);await clickAction(p,'soc-response');const text=await p.locator('#dialog').innerText();assert(text.includes('demo.service'));assert(text.includes('e2'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await waitFor(async()=>p.url().endsWith('/investigation/e2'));await p.locator('[data-action="soc-case-tab"][data-tab="activity"]').click();await waitFor(async()=>(await p.locator('.soc-response-results').innerText()).includes(mode==='normal'?'已完成':'结果待核对'));assert.equal(await p.locator('.soc-response-task').count(),1);if(mode==='unknown'){assert(!(await p.locator('.soc-response-results').innerText()).includes('已完成'));await clickAction(p,'soc-response');assert.equal(await p.locator('#dialog[open] #confirm-impact').count(),0,'Unresolved response must not permit a new intent');assert.equal(await p.locator('.soc-response-task').count(),1);}});
await test('SOC close requires a classification and written conclusion',async p=>{await nav(p,'threats/investigation/e2');await clickAction(p,'event-close');await confirm(p);assert.equal(await p.locator('#dialog[open]').count(),1);await p.locator('#close-classification').selectOption({index:1});await p.locator('#close-reason').fill('已核对维护窗口与认证来源，关闭当前调查。');await confirm(p);assert.equal(await p.locator('#dialog[open]').count(),0);assert((await p.locator('.soc-case-header').innerText()).includes('已关闭'));await p.locator('[data-action="soc-case-tab"][data-tab="activity"]').click();assert((await p.locator('main').innerText()).includes('已核对维护窗口'));});
await test('SOC mobile investigation has usable text relationships without page overflow',async p=>{await nav(p,'threats/investigation/e2');await clickAction(p,'soc-graph-view');assert(await p.locator('.soc-graph-main.text-mode').count());const size=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert(size.scroll<=size.width+1,JSON.stringify(size));const geometry=await p.evaluate(()=>({scrollY,activeAction:document.activeElement.dataset.action,activeClass:document.activeElement.className,topbar:document.querySelector('.topbar').getBoundingClientRect().toJSON(),skip:document.querySelector('.skip-link').getBoundingClientRect().toJSON()}));fs.writeFileSync(path.join(OUT,'mobile-investigation-geometry.json'),JSON.stringify(geometry,null,2));assert.equal(geometry.activeAction,'soc-graph-view','View toggle retains its action focus');assert(geometry.skip.bottom<=0,'Unfocused skip link stays above viewport');assert(geometry.topbar.top>=-1&&geometry.topbar.top<=1,'Mobile navigation remains pinned to viewport top');await p.screenshot({path:path.join(OUT,'14-soc-mobile-scrolled.png')});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:path.join(OUT,'13-soc-mobile-investigation.png'),fullPage:true});},{mobile:true});


await test('Mobile can discover the deepest management page through the actual sidebar',async p=>{await clickAction(p,'mobile-menu');await p.locator('.nav-management summary').click();await p.locator('.nav-link[href="#/admin"]').click();await waitFor(async()=>p.url().endsWith('#/admin'));await clickAction(p,'mobile-menu');const item=p.locator('.section-nav a[href="#/admin/install"]');await item.scrollIntoViewIfNeeded();assert(await item.isVisible());await item.click();await waitFor(async()=>p.url().endsWith('#/admin/install')&&(await p.locator('h1').innerText())==='安装与部署');assert((await p.locator('main').innerText()).includes('安装'));assert((await p.locator('[data-record-id]').count())>0);assert.equal(await p.locator('.sidebar.open').count(),0);await p.screenshot({path:path.join(OUT,'15-mobile-installation.png'),fullPage:true});},{mobile:true});

}catch(e){results.push({name:'browser infrastructure',status:'blocked',error:e.stack});console.error(e);}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));const files=runtimeFiles;const report={time:new Date().toISOString(),baseline:'5ca5ea513933d673ef87613fd0a863500a50b92a',scope:'isolated synthetic prototype; not production or AD acceptance',browserModule:modulePath,githubSha:process.env.GITHUB_SHA||null,githubHeadSha:process.env.GITHUB_HEAD_SHA||null,sourceHashes:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex')])),results,summary:{passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,blocked:results.filter(r=>r.status==='blocked').length},pageErrors:errors,requestedURLs:[...new Set(requests)]};fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary));if(report.summary.failed||report.summary.blocked)process.exitCode=1;}})();
