'use strict';
/* Isolated prototype QA. Reuses the repository-pinned Playwright, never the production app. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { once } = require('node:events');
const crypto = require('node:crypto');
const ROOT=__dirname,OUT=path.join(ROOT,'test-results');
fs.mkdirSync(OUT,{recursive:true});
let modulePath=process.env.PLAYWRIGHT_MODULE_PATH||null;
let chromium;
const results=[],errors=[],requests=[];
const contentTypes={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'};
const allowedFiles=new Set(['/','/index.html','/styles.css','/app.js','/coverage.js','/favicon.ico']);
const server=http.createServer((req,res)=>{let name;try{name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400).end();return;}if(!allowedFiles.has(name)){res.writeHead(404).end();return;}if(name==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.join(ROOT,name==='/'?'index.html':name.slice(1));fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':contentTypes[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);});});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let browser,base;
async function waitFor(fn,timeout=11000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(100);}throw Error('Expected condition did not become true within '+timeout+'ms');}
async function test(name,fn,{mobile=false,file=false}={}){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});const page=await context.newPage();const pageErrors=[],pageRequests=[];page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>pageRequests.push(r.url()));const start=Date.now();try{await page.goto(file?'file://'+path.join(ROOT,'index.html'):base);await page.locator('h1').waitFor();await fn(page,context);assert.deepEqual(pageErrors,[],'No JavaScript page errors');for(const url of pageRequests){if(url.startsWith('file://')&&file)continue;if(!url.startsWith(base))throw Error('Non-local network request: '+url);const route=new URL(url).pathname;assert(allowedFiles.has(route),'Only app static resources requested: '+route);}results.push({name,status:'passed',durationMs:Date.now()-start,requests:pageRequests.length});console.log('PASS',name);}catch(e){results.push({name,status:'failed',durationMs:Date.now()-start,error:e.message});try{await page.screenshot({path:path.join(OUT,'failure-'+String(results.length).padStart(2,'0')+'.png'),fullPage:true});}catch{}console.error('FAIL',name,e.message);}finally{errors.push(...pageErrors);requests.push(...pageRequests);await context.close();}}
async function nav(p,page){await p.goto(base+'#/'+page);const root=page.split('/')[0];await waitFor(async()=>await p.locator('.nav-link[aria-current="page"]').getAttribute('href')==='#/'+root);await p.locator('h1').waitFor();}
async function clickAction(p,action){await p.locator('[data-action="'+action+'"]').first().click();}
async function scenario(p,value){await p.locator('#scenario').selectOption(value);}
async function confirm(p){await p.locator('#dialog [data-action="confirm-intent"]').click();}
async function newDetection(p,mode='normal'){await nav(p,'detection');await scenario(p,mode);await clickAction(p,'new-detection');await confirm(p);await p.locator('[data-task-id]').first().waitFor();}
async function taskRow(p){return p.locator('[data-task-id]').first();}
async function stateText(p,value){await waitFor(async()=>((await (await taskRow(p)).innerText()).includes(value)));}
async function responseFromEvent(p,eventId){await nav(p,'threats');await p.locator(`[data-action="event-detail"][data-id="${eventId}"]`).first().click();await p.locator('.drawer [data-action="event-response"]').click();await waitFor(async()=>await p.locator('h1').innerText()==='响应处置');}
async function verifyResponse(p,name,id,event){await responseFromEvent(p,event);const body=await p.locator('main').innerText();assert(body.includes(name));assert(body.includes(event.toUpperCase()));await clickAction(p,'response-confirm');const text=await p.locator('#dialog').innerText();assert(text.includes(name+' / '+id));assert(text.includes(event));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await p.locator('[data-task-id]').first().waitFor();await p.locator('[data-action="task-detail"]').first().click();const detail=await p.locator('.drawer').innerText();assert(detail.includes(name+' / '+id));assert(detail.includes(event+' / v3'));}
(async()=>{try{modulePath=modulePath||require.resolve('playwright',{paths:[path.resolve(ROOT,'../../web')]});({chromium}=require(modulePath));server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{} )});
await test('Nine useful navigation pages and no runtime errors',async p=>{for(const page of ['overview','connections','assets','detection','threats','response','reports','work','admin']){await nav(p,page);assert((await p.locator('main').innerText()).length>160);assert.equal(await p.locator('.nav-link[aria-current="page"]').count(),1);}await nav(p,'overview');await p.screenshot({path:path.join(OUT,'01-overview.png'),fullPage:true});});
await test('Asset search, category, empty results, details and return',async p=>{await nav(p,'assets');await p.locator('[data-filter="q"]').fill('not-found');assert((await p.locator('main').innerText()).includes('没有符合筛选'));await p.locator('[data-filter="q"]').fill('');await p.locator('[data-filter="q"]').pressSequentially('demo.alex');assert.equal(await p.locator('[data-filter="q"]').inputValue(),'demo.alex');assert.equal(await p.locator('tbody tr').count(),2);await p.locator('#domain').selectOption('alpha');await p.locator('[data-filter="type"]').selectOption('用户');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert((await p.locator('.drawer').innerText()).includes('demo-guid-user-001'));await p.screenshot({path:path.join(OUT,'02-asset-detail.png'),fullPage:true});await p.keyboard.press('Escape');assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('[data-filter="type"]').inputValue(),'用户');});
await test('Event e2 preserves service identity through response and task',async p=>verifyResponse(p,'demo.service','a4','e2'));
await test('Event e3 preserves group target through response and task',async p=>verifyResponse(p,'DEMO-Tier0','a3','e3'));
await test('Response confirmation requires both checks and freezes exact object',async p=>{await responseFromEvent(p,'e2');await clickAction(p,'response-confirm');await confirm(p);assert((await p.locator('#confirm-error').innerText()).includes('请先'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();assert.equal(await p.locator('#confirm-error').innerText(),'');await p.screenshot({path:path.join(OUT,'03-response-confirm.png'),fullPage:true});await p.keyboard.press('Escape');assert.equal(await p.locator('#dialog[open]').count(),0);await nav(p,'work');assert.equal(await p.locator('[data-task-id]').count(),0);});
await test('Single-intent repeated click and Enter create only one task',async p=>{await nav(p,'detection');await clickAction(p,'new-detection');await p.locator('#dialog [data-action="confirm-intent"]').focus();await p.keyboard.press('Enter');await p.keyboard.press('Enter');await p.locator('[data-task-id]').first().waitFor();assert.equal(await p.locator('[data-task-id]').count(),1);await stateText(p,'已完成');});
await test('Queued cancellation uses zero execution attempts',async p=>{await newDetection(p);await p.locator('[data-action="cancel-task"]').first().click();const row=await (await taskRow(p)).innerText();assert(row.includes('已取消'));assert(row.includes('0 / 3'));});
await test('Running cancellation waits for executor confirmation',async p=>{await newDetection(p);await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();assert((await (await taskRow(p)).innerText()).includes('已请求取消'));await stateText(p,'已取消');});
await test('Cancel race retains success and records race event',async p=>{await newDetection(p,'cancel-race');await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();await stateText(p,'已完成');await p.locator('[data-action="task-detail"]').first().click();assert((await p.locator('.drawer').innerText()).includes('completed-with-cancel-race'));});
await test('Lost cancellation remains unconfirmed rather than cancelled',async p=>{await newDetection(p,'cancel-lost');await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().click();await stateText(p,'失败');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('cancellation_unconfirmed'));assert(!text.includes('取消完成。'));});
await test('Unknown result is reconciled without duplicate task',async p=>{await newDetection(p,'unknown');await stateText(p,'结果待核对');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);await p.locator('[data-action="reconcile-task"]').first().click();assert.equal(await p.locator('[data-task-id]').count(),1);assert((await (await taskRow(p)).innerText()).includes('已完成'));});
await test('Regrant cannot reconcile an old authorization epoch',async p=>{await newDetection(p,'unknown');await stateText(p,'结果待核对');await p.locator('#role').selectOption('viewer');await p.locator('#role').selectOption('operator');assert.equal(await p.locator('[data-action="reconcile-task"]').count(),0);assert((await (await taskRow(p)).innerText()).includes('结果待核对'));});
await test('Safe failed task recovery creates an authorized child',async p=>{await newDetection(p,'failed');await stateText(p,'失败');await p.locator('[data-action="recover-task"]').first().click();await confirm(p);assert.equal(await p.locator('[data-task-id]').count(),2);await stateText(p,'已完成');await p.locator('[data-action="task-detail"]').first().click();assert((await p.locator('.drawer').innerText()).includes('父任务'));});
await test('Single-attempt connection failure has no generic recover',async p=>{await nav(p,'connections');await scenario(p,'failed');await p.locator('[data-action="diagnose"][data-domain="alpha"]').click();await confirm(p);await stateText(p,'失败');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);});
await test('Partial failure preserves object outcomes and prohibits full recovery',async p=>{await newDetection(p,'partial');await stateText(p,'部分失败');assert.equal(await p.locator('[data-action="recover-task"]').count(),0);await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('DEMO-Tier0 / a3'));assert(text.includes('不能整批恢复'));});
await test('Single-object response never invents a partial-failure target set',async p=>{await responseFromEvent(p,'e2');await scenario(p,'partial');await clickAction(p,'response-confirm');assert((await p.locator('#dialog').innerText()).includes('demo.service / a4'));await p.locator('#confirm-impact').check();await p.locator('#confirm-demo').check();await confirm(p);await stateText(p,'失败');await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('demo.service / a4'));assert(text.includes('没有其他响应对象'));assert(!text.includes('DEMO-OBJ'));assert(!text.includes('逐对象合成结果'));});
await test('Template card preselects and confirmation freezes chosen ID and version',async p=>{await nav(p,'detection');await p.locator('[data-template="identity"]').click();assert.equal(await p.locator('#detect-template').inputValue(),'identity');await p.locator('#detect-template').selectOption('permissions');await confirm(p);await p.locator('[data-task-id]').first().waitFor();await p.locator('[data-action="task-detail"]').first().click();const text=await p.locator('.drawer').innerText();assert(text.includes('目录权限评估'));assert(text.includes('permissions / v1.4.2'));});
await test('Directory v2 needs both switches and independent grant',async p=>{await nav(p,'connections');await p.locator('[data-action="directory-auth"][data-domain="alpha"]').click();await p.locator('#directory-v2').check();await confirm(p);assert((await p.locator('#directory-error').innerText()).includes('三个条件'));await p.locator('#directory-master').check();await p.locator('#directory-grant').check();await confirm(p);await waitFor(async()=>await p.locator('h1').innerText()==='目录资产');assert.equal(await p.locator('h1').innerText(),'目录资产');assert.equal(await p.locator('#domain').inputValue(),'alpha');});
await test('Admin without domain has no private list, counts or audit objects',async p=>{await newDetection(p);await p.locator('#role').selectOption('platform');await nav(p,'assets/asset/a1');assert((await p.locator('main').innerText()).includes('没有业务访问权限'));assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('.nav-count').count(),0);await nav(p,'admin');await p.locator('[data-action="admin-tab"][data-tab="audit"]').click();assert(!(await p.locator('main').innerText()).includes('DEMO-TASK-'));});
await test('Forbidden scene stays fail closed through running timer and deep link',async p=>{await newDetection(p);const id=await p.locator('[data-task-id]').first().getAttribute('data-task-id');await scenario(p,'forbidden');await nav(p,'work/task/'+id);await sleep(2200);assert.equal(await p.locator('.drawer').count(),0);assert.equal(await p.locator('.nav-count').count(),0);assert(!(await p.locator('main').innerText()).includes(id));});
await test('Unread count is scoped to visible domain messages',async p=>{await nav(p,'work');await p.locator('#domain').selectOption('alpha');await p.locator('[data-action="work-tab"][data-tab="messages"]').click();while(await p.locator('[data-action="mark-read"]:not(:disabled)').count()){await p.locator('[data-action="mark-read"]:not(:disabled)').first().click();}await p.locator('#domain').selectOption('beta');assert((await p.locator('main').innerText()).includes('2 条未读'));});
await test('Export CSV is synthetic and download revocation survives navigation',async p=>{await nav(p,'assets');await p.locator('#domain').selectOption('alpha');await clickAction(p,'export-assets');await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const download=await promise;const file=await download.path();const csv=fs.readFileSync(file,'utf8');assert(csv.includes('SYNTHETIC'));assert(!csv.includes('beta.example.test'));assert(download.suggestedFilename().startsWith('ADTR_SYNTHETIC_'));await clickAction(p,'revoke-download');await p.locator('#domain').selectOption('beta');await p.locator('#domain').selectOption('alpha');let triggered=false;const listener=()=>{triggered=true;};p.on('download',listener);await p.locator('[data-action="download-task"]').first().click();await sleep(500);assert(!triggered,'Revocation must persist');assert((await p.locator('#toast').innerText()).includes('失效'));p.off('download',listener);});
for(const [kind,header]of [['events','classification,id,event,domain,state'],['audit','classification,action,target,result']]){await test('Failed '+kind+' export recovery preserves original CSV schema',async p=>{await nav(p,'reports');await p.locator('#domain').selectOption('alpha');await scenario(p,'failed');await clickAction(p,'export-'+kind);await confirm(p);await stateText(p,'失败');await p.locator('[data-action="recover-task"]').first().click();await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const d=await promise;const csv=fs.readFileSync(await d.path(),'utf8').replace(/^\uFEFF/,'');assert.equal(csv.split('\r\n')[0],header);assert(!csv.includes('demo-guid'));assert(!csv.includes('beta.example.test'));});}
await test('Permission form denies write without read and records explicit confirmation',async p=>{await nav(p,'admin');await p.locator('#grant-read').uncheck();await p.locator('#grant-write').check();await clickAction(p,'save-grants');assert.equal(await p.locator('#dialog[open]').count(),0);assert((await p.locator('#toast').innerText()).includes('依赖'));await p.locator('#grant-read').check();await clickAction(p,'save-grants');await confirm(p);assert((await p.locator('#grant-error').innerText()).includes('请确认'));await p.locator('#grant-proof').check();await confirm(p);assert(await p.locator('#grant-write').isChecked());});
await test('History, modal dismissal and skip link never replay actions or navigate away',async p=>{await nav(p,'assets');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();await p.goBack();assert.equal(await p.locator('.drawer').count(),0);await p.goForward();await p.locator('.drawer').waitFor();await p.locator('[data-action="close-drawer"]').first().click();await p.locator('.skip-link').focus();await p.keyboard.press('Enter');assert(p.url().endsWith('#/assets'));assert.equal(await p.evaluate(()=>document.activeElement.id),'main');await nav(p,'detection');await clickAction(p,'new-detection');await p.keyboard.press('Escape');await nav(p,'work');assert.equal(await p.locator('[data-task-id]').count(),0);});
await test('Task updates preserve keyboard focus in table and drawer',async p=>{await newDetection(p);await stateText(p,'运行中');await p.locator('[data-action="cancel-task"]').first().focus();await sleep(700);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'cancel-task');await p.locator('[data-action="task-detail"]').first().click();await p.locator('.drawer [aria-label="关闭详情"]').focus();await sleep(700);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'关闭详情');await p.keyboard.press('Escape');assert.equal(await p.locator('.drawer').count(),0);});
await test('Report export updates preserve focused controls',async p=>{await nav(p,'reports');await clickAction(p,'export-assets');await confirm(p);await stateText(p,'运行中');await p.locator('[data-action="revoke-download"]').focus();await sleep(800);assert.equal(await p.evaluate(()=>document.activeElement.dataset.action),'revoke-download');});
await test('Cross-domain audit export contains no foreign scoped records',async p=>{await nav(p,'detection');await p.locator('#domain').selectOption('beta');await clickAction(p,'new-detection');await confirm(p);await p.locator('[data-task-id]').first().waitFor();const betaId=await p.locator('[data-task-id]').first().getAttribute('data-task-id');await p.locator('#domain').selectOption('alpha');await nav(p,'admin');await p.locator('[data-action="admin-tab"][data-tab="audit"]').click();assert(!(await p.locator('main').innerText()).includes(betaId));await nav(p,'reports');await clickAction(p,'export-audit');await confirm(p);await stateText(p,'已完成');const promise=p.waitForEvent('download');await p.locator('[data-action="download-task"]').first().click();const d=await promise;const csv=fs.readFileSync(await d.path(),'utf8');assert(!csv.includes(betaId));assert(!csv.includes('beta.example.test'));});
await test('Drawer keyboard focus remains contained',async p=>{await nav(p,'assets');await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();await p.locator('.drawer').waitFor();assert(await p.locator('.shell').evaluate(el=>el.inert));await waitFor(()=>p.evaluate(()=>!!document.activeElement.closest('.drawer')));for(const key of ['Tab','Shift+Tab'])for(let i=0;i<18;i++){await p.keyboard.press(key);assert(await p.evaluate(()=>!!document.activeElement.closest('.drawer')));}await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.dataset.id),'a1');});
await test('Empty, read-error, forbidden and stale views are distinguishable',async p=>{await nav(p,'assets');await scenario(p,'empty');assert((await p.locator('main').innerText()).includes('暂无演示记录'));await scenario(p,'error');assert((await p.locator('main').innerText()).includes('暂时无法读取'));await clickAction(p,'retry-page');assert((await p.locator('main').innerText()).includes('已观测目录对象'));await scenario(p,'forbidden');assert((await p.locator('main').innerText()).includes('没有业务访问权限'));await scenario(p,'stale');assert((await p.locator('main').innerText()).includes('陈旧观测'));});
await test('390px layout has accessible navigation and no page-level horizontal overflow',async p=>{await p.screenshot({path:path.join(OUT,'04-mobile.png'),fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})).slice(0,12)}))));await clickAction(p,'mobile-menu');await p.locator('.sidebar [href="#/assets"]').click();await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})).slice(0,12)}))));await p.locator('.drawer [aria-label="关闭详情"]').click();await clickAction(p,'mobile-menu');await p.locator('.sidebar [href="#/response"]').click();await clickAction(p,'response-confirm');assert(await p.locator('#dialog [data-action="confirm-intent"]').isVisible());},{mobile:true});
await test('Direct file opening works without modules, fetch or a server',async p=>{assert.equal(await p.locator('h1').innerText(),'安全态势总览');await p.locator('.nav-link[href="#/assets"]').click();await p.locator('[data-action="asset-detail"][data-id="a1"]').first().click();assert((await p.locator('.drawer').innerText()).includes('demo.alex'));},{file:true});
}catch(e){results.push({name:'browser infrastructure',status:'blocked',error:e.stack});console.error(e);}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));const files=['index.html','styles.css','app.js','coverage.js'];const report={time:new Date().toISOString(),baseline:'5ca5ea513933d673ef87613fd0a863500a50b92a',scope:'isolated synthetic prototype; not production or AD acceptance',browserModule:modulePath,githubSha:process.env.GITHUB_SHA||null,githubHeadSha:process.env.GITHUB_HEAD_SHA||null,sourceHashes:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex')])),results,summary:{passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,blocked:results.filter(r=>r.status==='blocked').length},pageErrors:errors,requestedURLs:[...new Set(requests)]};fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary));if(report.summary.failed||report.summary.blocked)process.exitCode=1;}})();
