/* Business page rendering and local interactions. No external execution. */
window.ADTR_WORKBENCH = function (api) {
  'use strict';
  const { state, escape: esc, icon, tag, btn, link, toast, role, canWrite, domainAllowed, selectedDomain, openDialog, closeDialog, render, audit } = api;
  const pages = [...window.ADTR_BUSINESS_PAGES, ...(window.ADTR_ADMIN_PAGES || [])];
  const byId = Object.fromEntries(pages.map(p => [p.id,p]));
  const memory = Object.fromEntries(pages.map(p => [p.id, structuredClone(p.rows || [])]));
  pages.forEach(p=>{if(p.scope==='platform'&&!['profile','account-security','mfa'].includes(p.special))p.restricted=true;memory[p.id].forEach(r=>{r.version=r.version||1;});});
  const searches = {};
  const archiveViews={};
  const pendingJobs=[];const responseSeen=new Set();
  const selected = {};
  const actionNames = {create:'保存',edit:'保存变更',delete:'删除',toggle:'切换状态',test:'检查',download:'下载',reset:'重置',activate:'发布',restart:'重启',inspect:'详情',initialize:'初始化',install:'安装',sync:'同步',restore:'恢复',execute:'执行',upgrade:'升级',generate:'生成报告',archive:'归档',cleanup:'归档过期记录'};
  let seq=100, draft=null;
  function current() { return byId[[state.route,state.view].filter(Boolean).join('/')]; }
  const pageRead={connections:'systemView',assets:'assetView',detection:'detectionView',threats:'investigationView',response:'responseView',reports:'reportView',work:null};
  const adminRead={'admin/audit':'auditView','admin/system':'systemView','admin/users':'userManage','admin/roles':'roleManage','admin/resources':'resourceManage','admin/license':'systemView','admin/settings':'systemManage','admin/services':'serviceOperate','admin/diagnostics':'systemView','admin/install':'systemManage','admin/integrations':'systemManage'};
  const adminWrite={'admin/users':'userManage','admin/roles':'roleManage','admin/resources':'resourceManage','admin/license':'systemManage','admin/settings':'systemManage','admin/services':'serviceOperate','admin/diagnostics':'systemManage','admin/install':'systemManage','admin/integrations':'systemManage','admin/system':'systemManage'};
  function allowed(p) { if(state.signedOut||state.scenario==='forbidden')return false;const access=state.adminAccessOverrides?.[state.role];if(access?.enabled===false)return false;if(['profile','account-security','mfa'].includes(p.special))return true;const key=adminRead[p.id]||pageRead[p.section];return key?api.permission(key):(p.scope==='platform'?false:true); }
  function writable(p) { if(!allowed(p))return false;if(['profile','account-security','mfa'].includes(p.special))return true;if(p.id==='admin/audit')return api.permission('auditExport')||api.permission('systemManage');const key=adminWrite[p.id]||({connections:'systemManage',assets:'detectionRun',detection:p.kind==='rules'||p.id==='detection/allowlists'?'ruleManage':'detectionRun',threats:'ruleManage',response:'responseExecute',reports:'reportExport',work:'taskManage'})[p.section];return !!key&&api.permission(key); }
  function canAction(p,a){if(!allowed(p))return false;const intent=a.intent||a.verb;if(['inspect','query','audit_filter','sessions','role_members','license_preview','authorization_preview','diagnostic_result','service_recovery','installation_steps'].includes(intent))return true;if(intent==='audit_export')return api.permission('auditExport');if(intent==='audit_archive')return api.permission('auditView')&&api.permission('systemManage');if(a.verb==='download'&&p.section==='assets')return api.permission('assetExport');if(a.verb==='download'&&['detection','threats','reports'].includes(p.section))return api.permission('reportExport');return writable(p);}
  function visible(p) { return allowed(p) && state.scenario!=='empty' ? memory[p.id].filter(r=>domainAllowed(r.domain||'platform')).filter(r=>!r.ownerRole||r.ownerRole===state.role).filter(r=>!p.filterRecord||p.filterRecord(r)).filter(r=>(p.special==='audit'||archiveViews[p.id])?true:r.status!=='已归档') : []; }
  function get(p,id) { return visible(p).find(r=>r.id===id); }
  const engine=window.ADTR_ADMIN_ENGINE?window.ADTR_ADMIN_ENGINE({api,pages:byId,memory,visible,get,record,download,edit,detail,confirm,render,allowed,writable,canAction}):null;
  function schemaActions(p) { return [...(p.rowActions||[]),...(p.toolbarActions||[]),...(p.secondary||[]),...(p.batch||[]),...(p.bulkActions||[]),...(p.sessionActions||[]),...(p.primary?[p.primary]:[])]; }
  function aButton(p,a,r=null,cls='subtle') { const writing=!['inspect'].includes(a.verb);const applicable=(!a.appliesTo||a.appliesTo.includes?.(r?.id)||r?.kind===a.appliesTo)&&(!a.excludeIds||!a.excludeIds.includes(r?.id));if(r&&!applicable)return ''; return btn(esc(a.label),'biz-action',cls,`data-page="${p.id}" data-id="${r?.id||''}" data-verb="${a.verb}" data-intent="${esc(a.intent||a.verb)}" data-batch="${a.batch?'true':'false'}" ${!canAction(p,a)?'disabled':''}`); }
  function subnav(section) { const own=pages.filter(p=>p.section===section&&allowed(p)); if(!own.length)return '';return `<nav class="section-nav" aria-label="${esc(api.titles[section][1])}功能"><a class="${!state.view?'active':''}" href="#/${section}">${({connections:'域连接',assets:'资产目录',detection:'检测工作台',threats:'威胁事件',response:'响应工作台',reports:'导出任务',work:'任务与消息',admin:'权限工作台'})[section]||'概览'}</a>${own.map(p=>`<a href="#/${p.id}" ${current()?.id===p.id?'aria-current="page"':''} class="${current()?.id===p.id?'active':''}">${esc(p.navTitle||p.title)}</a>`).join('')}</nav>`; }
  function fieldLabel(p,key) { return (p.fields||[]).find(f=>f.key===key)?.label || (p.columns||[]).find(c=>c.key===key)?.label || ({status:'状态',domain:'范围',version:'记录版本',created:'创建时间',updated:'更新时间',history:'操作历史',device:'设备',before:'变更前',after:'变更后',memory:'内存',alert:'提醒',source:'来源',reason:'原因',testResult:'测试结果',lastTask:'关联任务',lastResult:'最近结果',batch:'观测批次',changes:'批次变化',resultVersion:'结果版本',evidenceVersion:'证据版本',recoveryTask:'恢复任务'})[key] || null; }
  function pretty(v) { return v===null||v===undefined||v===''?'未设置':typeof v==='boolean'?(v?'启用':'停用'):Array.isArray(v)?v.join('、'):String(v); }
  function scope(r) { return r.domain==='platform'?'平台':api.domains[r.domain]||r.domain; }
  function stats(p, rows) { if(p.scope==='domain')return `<div class="business-summary"><div><strong>${rows.length}</strong><span>${esc(p.title)}</span></div><div><strong>${new Set(rows.map(r=>r.domain)).size}</strong><span>可见域</span></div><div><strong>${rows.filter(r=>/异常|未通过|待|不足|风险/.test(r.status||'')).length}</strong><span>需要关注</span></div><span class="summary-time">${icon('clock')}最后更新 10-10 00:10 UTC</span></div>`;return p.stats?`<div class="business-summary">${p.stats.map(s=>`<div><strong>${esc(s.value)}</strong><span>${esc(s.label)}</span></div>`).join('')}</div>`:''; }
  function specialPanel(p, rows) {
    const adminPanel=engine?.panel?.(p,rows);if(adminPanel)return adminPanel;
    const first=rows[0];
    if(!first)return '';
    if(p.kind==='paths') return `<section class="panel business-feature"><div class="panel-head"><div><h2>可达路径视图</h2><p class="panel-subtitle">选中路径后查看逐边证据和检测规则</p></div>${tag('权限与行为关联','blue')}</div><div class="path-canvas">${[first.source,'DEMO-Helpdesk',first.target].map((n,i)=>`<div class="path-node ${i===2?'critical':''}">${icon(i===2?'response':i===0?'user':'group')}<strong>${esc(n)}</strong><span>${['初始身份','可修改组成员','关键目标'][i]}</span></div>${i<2?'<div class="path-edge"><span>WriteMembers</span>→</div>':''}`).join('')}</div><div class="panel-body"><p class="subtitle">路径可达性需要结合时间、授权和配置状态判断。下方列表提供完整文字视图。</p></div></section>`;
    if(p.kind==='rules')return `<section class="panel business-feature"><div class="panel-head"><div><h2>从条件到已发布规则</h2><p class="panel-subtitle">创建规则 → 配置条件 → 样本测试 → 审阅发布</p></div>${tag('版本管理','blue')}</div><div class="pipeline"><span>1 条件构建</span><b>→</b><span>2 正反样本</span><b>→</b><span>3 不可变版本</span><b>→</b><span>4 检测引用</span></div></section>`;
    if(p.kind==='deployment')return `<section class="panel business-feature"><div class="panel-head"><div><h2>部署准备</h2><p class="panel-subtitle">检查环境和组件，确认维护窗口后分步安装</p></div>${tag('Windows / x64','outline')}</div><div class="pipeline"><span>1 环境选择</span><b>→</b><span>2 范围与配置</span><b>→</b><span>3 前置检查</span><b>→</b><span>4 安装结果</span></div><div class="panel-body"><div class="readiness-grid"><div>${icon('server')}Windows Server 2019 / 2022</div><div>${icon('lock')}证书校验与最小权限</div><div>${icon('clock')}维护窗口与回退点</div></div></div></section>`;
    if(p.kind==='risk')return `<section class="panel business-feature"><div class="panel-head"><div><h2>风险变化与事件分布</h2><p class="panel-subtitle">本次评分与上次观测对比</p></div></div><div class="risk-comparison">${rows.map(r=>`<div><span>${esc(r.name)}</span><meter min="0" max="100" value="${Number(r.score)||0}" aria-label="${esc(r.name)}风险评分"></meter><strong>${esc(r.score)}</strong><small>上次 ${esc(r.previous)}</small></div>`).join('')}</div></section>`;
    if(p.kind==='relationships')return `<section class="panel business-feature"><div class="panel-head"><h2>关系视图</h2>${tag('当前观测','outline')}</div><div class="path-canvas"><div class="path-node">${icon('user')}<strong>${esc(first.principal||first.name)}</strong><span>身份</span></div><div class="path-edge"><span>${esc(first.permission||first.relation)}</span>→</div><div class="path-node">${icon('server')}<strong>${esc(first.device||first.name)}</strong><span>${esc(first.service||first.inheritance)}</span></div></div></section>`;
    if(p.kind==='search')return `<section class="panel business-feature"><div class="panel-head"><div><h2>行为查询</h2><p class="panel-subtitle">字段筛选支持等于匹配，时间范围与保留期限同时生效</p></div></div><div class="panel-body query-builder"><label class="form-field"><span>字段</span><select id="query-field"><option value="event_id">事件 ID</option><option value="account_name">身份</option><option value="device">设备</option></select></label><label class="form-field"><span>等于</span><input id="query-value" value="4662" aria-label="查询值"></label><label class="form-field"><span>时间范围</span><select id="query-window"><option>最近 24 小时</option><option>最近 7 天</option><option>最近 30 天</option></select></label>${btn('运行查询','biz-search','primary',`data-page="${p.id}"`)}</div></section>`;
    if(p.special==='mfa')return `<section class="panel business-feature"><div class="panel-head"><div><h2>多因素认证</h2><p class="panel-subtitle">保护当前账户，查看绑定状态和恢复方式</p></div>${tag(first.status||'未绑定','blue')}</div><div class="mfa-steps"><div class="security-shield">${icon('lock')}</div><div><h3>为登录添加第二道验证</h3><p class="subtitle">使用演示验证器完成绑定流程。不会显示真实密钥、二维码或恢复码。</p><ol><li>选择绑定方式</li><li>完成演示验证</li><li>确认恢复方式与会话影响</li></ol></div></div></section>`;
    if(p.special==='account-security')return `<section class="panel business-feature"><div class="panel-head"><h2>账户安全状态</h2>${tag('demo-tenant-a','outline')}</div><div class="readiness-grid panel-body"><div>${icon('user')}当前账户：demo.operator</div><div>${icon('clock')}密码策略：90 天有效期</div><div>${icon('lock')}敏感操作需再次验证</div></div></section>`;
    if(p.special==='profile')return `<section class="panel business-feature"><div class="profile-banner"><div class="profile-avatar">SO</div><div><h2>${esc(first.name)}</h2><p class="subtitle">${esc(first.email||'operator@example.test')}</p><span class="tag outline">demo-tenant-a</span></div></div></section>`;
    if(p.permissionMatrix)return `<section class="panel business-feature"><div class="panel-head"><h2>功能权限</h2><p class="panel-subtitle">默认拒绝；数据范围独立配置</p></div><div class="table-scroll"><table><thead><tr><th>功能</th><th>读取</th><th>管理</th></tr></thead><tbody>${p.permissionMatrix.map(m=>`<tr><td>${esc(m.label||m.name||m.feature)}</td><td>${tag(m.read?'允许':'拒绝',m.read?'green':'outline')}</td><td>${tag(m.write?'允许':'拒绝',m.write?'amber':'outline')}</td></tr>`).join('')}</tbody></table></div></section>`;
    if(p.kind==='reports')return `<div class="report-shelf">${rows.map(r=>`<button class="report-cover" data-action="biz-action" data-page="${p.id}" data-id="${r.id}" data-verb="inspect" data-intent="inspect"><span class="report-cover-top">ADTR / SECURITY</span><span class="report-cover-icon">${icon('report')}</span><strong>${esc(r.name)}</strong><span>${esc(r.period)} · ${esc(scope(r))}</span><i>阅读报告 ${icon('arrow')}</i></button>`).join('')}</div>`;
    if(p.kind==='report-templates')return `<div class="grid-3">${rows.map(r=>`<section class="panel template-card"><div class="type-icon">${icon('report')}</div><h2>${esc(r.category)}</h2><p>${esc(r.sections)}</p><div class="template-meta"><span>${esc(r.period)}</span><span>${esc(scope(r))}</span></div>${aButton(p,{label:'生成报告',verb:'generate'},r,'primary')}</section>`).join('')}</div>`;
    if(p.kind==='health'||p.kind==='telemetry')return `<section class="panel business-feature"><div class="panel-head"><h2>${p.kind==='health'?'监控时间线':'采集运行概览'}</h2>${tag('10-10 00:10 UTC','outline')}</div><div class="health-strip">${rows.map(r=>`<div><span class="health-dot ${/异常|停用/.test(r.status)?'warning':''}"></span><strong>${esc(r.name)}</strong><span>${esc(r.heartbeat||r.observed||r.lag)}</span>${tag(r.status,/异常|停用/.test(r.status)?'amber':'green')}</div>`).join('')}</div></section>`;
    return '';
  }
  function renderPage(p) {
    if(!allowed(p))return api.empty('没有此功能的访问权限','请联系管理员为当前角色分配所需功能权限。','','lock');
    const all=visible(p),query=searches[p.id]||'', rows=all.filter(r=>Object.values(r).some(v=>typeof v!=='object'&&String(v).toLowerCase().includes(query.toLowerCase())));
    const primary=p.primary?aButton(p,p.primary,null,'primary'):'';
    const secondary=[...(p.secondary||[]),...(p.toolbarActions||[])].map(a=>aButton(p,a,null,'')).join('');
    const exportButton=p.export?aButton(p,{label:'导出当前结果',verb:'download'},null,''):'';
    return `<div class="page-header"><div><div class="eyebrow">${esc(p.section.toUpperCase())}</div><h1 id="page-title" tabindex="-1">${esc(p.title)}</h1><p class="subtitle">${esc(p.subtitle)}</p></div><div class="header-actions">${exportButton}${secondary}${primary}</div></div>${stats(p,all)}${specialPanel(p,all)}${p.sections?`<div class="settings-sections">${p.sections.map(s=>`<section class="panel"><div class="panel-head"><h2>${esc(s.title)}</h2></div><div class="panel-body"><p class="subtitle">${esc(s.body||'')}</p>${(s.items||[]).map(i=>`<div class="info-row"><span>${esc(i.label)}</span><strong>${esc(i.value)}</strong></div>`).join('')}</div></section>`).join('')}</div>`:''}<section class="panel business-table"><div class="panel-head"><h2>${esc(p.listTitle||p.title)}</h2>${tag(all.length+' 条','outline')}</div><div class="toolbar"><label class="search">${icon('search')}<input type="search" data-biz-filter="${p.id}" aria-label="搜索${esc(p.title)}" placeholder="搜索名称、属性或状态…" value="${esc(query)}"></label>${[...(p.batch||[]),...(p.bulkActions||[])].map(a=>aButton(p,{...a,batch:true},null,'')).join('')}${memory[p.id].some(r=>r.status==='已归档')&&p.special!=='audit'?btn(archiveViews[p.id]?'隐藏归档':'查看归档','biz-archives','',`data-page="${p.id}"`):''}<span class="toolbar-end">${p.scope==='platform'?'平台工作空间':'仅当前授权范围'}</span></div>${rows.length?`<div class="table-scroll" role="region" aria-label="${esc(p.title)}表" tabindex="0"><table><thead><tr>${p.batch||p.bulkActions?'<th>选择</th>':''}${p.columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}<th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr data-record-id="${r.id}">${p.batch||p.bulkActions?`<td><input type="checkbox" data-biz-select="${p.id}" data-id="${r.id}" aria-label="选择 ${esc(r.name)}" ${(selected[p.id]||new Set()).has(r.id)?'checked':''}></td>`:''}${p.columns.map((c,i)=>`<td>${i===0?`<button class="row-link" data-action="biz-action" data-page="${p.id}" data-id="${r.id}" data-verb="inspect" data-intent="inspect">${esc(pretty(r[c.key]))}</button><span class="row-sub">${esc(scope(r))}</span>`:c.key==='status'?tag(pretty(r[c.key]),/失败|不足|异常|未通过/.test(r[c.key])?'amber':/启用|成功|通过|已/.test(r[c.key])?'green':'outline'):esc(pretty(r[c.key]))}</td>`).join('')}<td><div class="row-actions">${r.status==='已归档'&&p.special!=='audit'?aButton(p,{label:'恢复记录',verb:'restore',confirm:true},r):(p.rowActions||[]).map(a=>aButton(p,a,r)).join('')}</div></td></tr>`).join('')}</tbody></table></div>`:api.empty(query?'没有匹配结果':'尚无记录',query?'调整搜索条件后重试。':'使用页面操作添加第一条记录。')}${api.footer(rows.length)}</section>${p.related?`<div class="related-links"><span>相关工作</span>${p.related.map(([name,path])=>link(esc(name)+' '+icon('arrow'),path)).join('')}</div>`:''}${p.help?`<p class="page-note">${esc(p.help)}</p>`:''}`;
  }
  function detail(p,r) {
    let body=`<div class="inline">${tag(r.status||'已配置','blue')}${tag(scope(r),'outline')}</div><dl class="detail-grid">${Object.entries(r).filter(([k,v])=>fieldLabel(p,k)&&typeof v!=='object').map(([k,v])=>`<div><dt>${esc(fieldLabel(p,k))}</dt><dd>${esc(k==='domain'?scope(r):pretty(v))}</dd></div>`).join('')}</dl>`;
    if(p.kind==='paths')body+=specialPanel(p,[r])+`<h3>路径证据</h3><ol class="evidence-list"><li>${esc(r.source)} 属于 DEMO-Helpdesk：成员快照 23:55 UTC</li><li>DEMO-Helpdesk 对目标拥有 WriteMembers：权限快照 23:57 UTC</li><li>到达 ${esc(r.target)}：规则 ${esc(r.rule)}</li></ol><p class="subtitle">证据来自同一授权域的观测窗口，需核实当前有效性。</p>`;
    if(p.kind==='relationships')body+=`<h3>前后快照</h3><div class="snapshot-diff"><div><small>变更前</small><p>${esc(r.before||'尚无此访问关系')}</p></div><div><small>变更后</small><p>${esc(r.after||[r.name,r.device,r.service].filter(Boolean).join(' → '))}</p></div></div>`;
    if(r.recoveryHistory?.length)body+=`<h3>恢复记录</h3>${r.recoveryHistory.map(h=>`<p>${esc(h.task)} · ${esc(h.result)} · ${esc(h.time)}</p>`).join('')}`;
    if(p.kind==='risk')body+=`<h3>评分记录</h3><div class="timeline"><div class="timeline-item"><small>10-09 23:00 UTC</small><p>上次评分 ${esc(r.previous)} · 已观测</p></div><div class="timeline-item"><small>10-10 00:00 UTC</small><p>当前评分 ${esc(r.score)} · ${esc(r.reason)}</p></div></div>`;
    if(p.kind==='rules')body+=`<h3>检测条件</h3><pre class="evidence">${esc(r.condition)}</pre><h3>版本记录</h3><p class="subtitle">当前 ${esc(r.ruleVersion)} · ${esc(r.testResult)}</p>${(r.versions||[]).map(v=>`<p class="subtitle">${esc(v.ruleVersion)} · 已发布 · ${esc(v.condition)}</p>`).join('')}`;
    if(r.testCases)body+=`<h3>测试样本</h3>${r.testCases.map(t=>`<div class="info-row"><span>${esc(t.name)} · ${esc(t.observed)}</span>${tag(t.result,t.result==='通过'?'green':'red')}</div>`).join('')}`;
    if(p.kind==='reports')body+=reportBody(r);
    if(p.kind==='findings')body+=`<h3>修复建议</h3><p class="subtitle">${esc(r.remediation||r.expected)}。完成变更后执行单项复查，核对新的观测结果。</p>`;
    if(p.id==='work/notifications'){const recipients=memory['work/recipients'].filter(x=>x.domain===r.domain&&x.team===r.recipients&&x.status!=='已归档');body+=`<h3>关联接收人</h3><p>${recipients.map(x=>esc(x.name)+' / '+esc(x.address)).join('<br>')||'此范围的接收组尚无接收人'}</p>${r.lastTest?`<h3>最近发送测试</h3><p>${esc(r.lastTest.result)} · ${esc(r.lastTest.channel)} · ${esc(r.lastTest.time)}</p><p>${r.lastTest.recipients.map(esc).join('、')}</p>`:''}`;}
    if(p.kind==='behavior')body+=`<h3>原始事件字段</h3><pre class="evidence">EventID: ${esc(r.eventId)}\nAccount: ${esc(r.identity)}\nDevice: ${esc(r.device)}\nAuthentication: ${esc(r.auth)}\nObserved: 2026-10-09 ${esc(r.time)}</pre>`;
    if(r.history?.length)body+=`<h3>操作记录</h3><div class="timeline">${r.history.map(h=>`<div class="timeline-item"><small>${esc(h.time)}</small><p>${esc(h.text)}</p></div>`).join('')}</div>`;
    openDialog(r.name||p.title,body,(p.rowActions||[]).filter(a=>a.verb!=='inspect').map(a=>aButton(p,a,r,'')).join(''));
  }
  function fieldMarkup(f,r={}) {
    const val=r[f.key]??f.value??f.default??(f.type==='select'?f.options?.[0]:'');
    return `<label class="form-field"><span>${esc(f.label)}${f.required?' *':''}</span>${f.type==='select'?`<select id="biz-field-${f.key}">${(f.options||[]).map(o=>typeof o==='object'?`<option value="${esc(o.value)}" ${val===o.value?'selected':''}>${esc(o.label)}</option>`:`<option ${val===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`:f.type==='checkbox'?`<input type="checkbox" id="biz-field-${f.key}" ${val?'checked':''}>`:f.type==='textarea'?`<textarea id="biz-field-${f.key}" rows="4" maxlength="800">${esc(val)}</textarea>`:`<input id="biz-field-${f.key}" type="${f.type==='number'?'number':'text'}" value="${esc(val)}" maxlength="200" ${f.required?'required':''}>`}${f.help?`<small>${esc(f.help)}</small>`:''}</label>`;
  }
  function edit(p,r,clone=false,seed=null) {
    let fs=(p.fields||[]).filter(f=>!r?.fieldKeys||r.fieldKeys.includes(f.key));if(p.id==='response/policies'){const targetDomain=r?.domain||selectedDomain();fs=fs.filter(f=>f.key!=='target');fs.push({key:'assetId',label:'目标资产',type:'select',required:true,options:api.visibleAssets().filter(a=>a.domain===targetDomain&&['用户','计算机'].includes(a.type)).map(a=>({value:a.id,label:a.name+' / '+api.domains[a.domain]}))});}
    draft={p:p.id,id:r?.id||null,epoch:state.epoch,role:state.role,domain:r?.domain||(p.scope==='platform'?'platform':selectedDomain()),version:r?.version,used:false,clone,fields:fs};
    const source=r?structuredClone(r):(seed||{});if(seed?.domain)draft.domain=seed.domain;
    if(!r && p.id==='work/recipients')source.address='new.recipient@example.test';
    if(clone)source.name=(source.name||p.title)+' · 新计划';
    const custom=p.kind==='rules'?'<div class="form-intro"><strong>条件构建器</strong><p>所有条件同时满足时触发，保存后运行样本测试。</p></div>':p.special==='profile'?'<div class="avatar-choices"><span class="profile-avatar small">SO</span><span class="profile-avatar small alternate">AD</span><span>头像样式随个人资料保存</span></div>':'';
    openDialog((r?(clone?'创建新计划':'编辑'):'新增')+' · '+p.title,`${custom}<div class="form-grid">${fs.map(f=>fieldMarkup(f,source)).join('')}</div>${p.kind==='rules'?'<div class="evidence" id="rule-preview" aria-live="polite">保存后生成条件表达式</div>':''}<div id="biz-error" class="error-inline" role="alert"></div>`,btn('保存','biz-save','primary',`data-page="${p.id}"`));
  }
  function validDraft(d) { const p=byId[d.p];return !d.used&&d.epoch===state.epoch&&d.role===state.role&&domainAllowed(d.domain)&&writable(p)&&(!d.id||get(p,d.id)?.version===d.version); }
  function record(p,r,text) { r.version=(r.version||0)+1;r.updated='10-10 00:10 UTC';(r.history||(r.history=[])).push({time:'10-10 00:10 UTC',text});audit(text,r.name,'成功',r.domain); }
  function save() {
    if(!draft)return;const d=draft,p=byId[d.p];
    if(!validDraft(d)){closeDialog();toast('对象或权限已变化，请重新打开表单。');return;}
    const values={};for(const f of d.fields){const el=document.getElementById('biz-field-'+f.key);const v=f.type==='checkbox'?el.checked:el.value.trim();if(f.required&&!v){document.getElementById('biz-error').textContent='请填写'+f.label;el.focus();return;}values[f.key]=v;}
    if(p.id==='work/recipients'&&!/^[a-z0-9._+-]+@example\.test$/i.test(values.address||'')){document.getElementById('biz-error').textContent='请输入 example.test 演示邮箱。';return;}
    if(p.kind==='rules'&&(!/^\d+$/.test(values.threshold)||Number(values.threshold)<1)){document.getElementById('biz-error').textContent='触发次数必须为正整数。';return;}
    if(p.id==='connections/accounts'&&!/^DEMO[-\\]/i.test(values.identity||'')){document.getElementById('biz-error').textContent='请选择 DEMO 开头的合成身份引用。';return;}
    if(visible(p).some(r=>r.id!==d.id&&r.domain===d.domain&&r.name===values.name)){document.getElementById('biz-error').textContent='当前范围已有同名记录。';return;}
    if(p.id==='response/policies'){const target=api.visibleAssets().find(a=>a.id===values.assetId&&a.domain===d.domain);if(!target){document.getElementById('biz-error').textContent='请选择当前域内的明确资产。';return;}if((target.type==='计算机'&&values.effect!=='限制设备访问')||(target.type==='用户'&&values.effect!=='限制账户访问')){document.getElementById('biz-error').textContent='响应动作需与目标对象类型一致。';return;}values.target=target.name;values.targetGuid=target.guid;}
    d.used=true;let r=d.id&&!d.clone?get(p,d.id):null;
    if(!r){r={id:'local-'+(++seq),domain:d.domain,version:0,status:p.kind==='rules'?'草稿':p.id==='work/schedules'?'暂停':'启用'};memory[p.id].unshift(r);}
    if(p.kind==='rules'&&r.status==='已发布'){(r.versions||(r.versions=[])).push({ruleVersion:r.ruleVersion,condition:r.condition});}
    Object.assign(r,values);
    if(p.kind==='rules'){r.status='草稿';r.testResult='待测试';r.testVersion=null;r.ruleVersion='1.'+(r.version||0)+'.0-draft';r.condition=`${r.field} ${r.operator} "${r.value}" / ${r.window} / 次数 ≥ ${r.threshold}`;}
    engine?.saved?.(p,r,values);record(p,r,d.clone?'从原计划创建新计划':d.id?'更新'+p.title:'新增'+p.title);closeDialog();render();toast('已保存'+r.name+'。');
  }
  function reportBody(r) {
    const assets=r.snapshot?.assets||api.visibleAssets().filter(a=>a.domain===r.domain),events=r.snapshot?.events||api.visibleEvents().filter(e=>e.domain===r.domain);
    let chapters='';
    if(r.category==='事件调查')chapters=`<h3>01 事件摘要</h3><p>本窗口关联 ${events.length} 条事件，${events.filter(e=>e.state==='待调查').length} 条待调查。</p><h3>02 调查证据</h3>${events.map(e=>`<section><h4>${esc(e.title)}</h4><p>${esc(e.evidence)}</p><p>规则 ${esc(e.rule)} · ${esc(e.state)} · ${esc(e.time)} UTC</p></section>`).join('')}<h3>03 处置与结论</h3><p>关闭事件与响应执行分别记录。请核对每个对象的确认结果后完成事件复盘。</p>`;
    else if(r.category==='日常巡检')chapters=`<h3>01 接入与采集</h3>${(r.snapshot?.health||memory['work/health'].filter(x=>x.domain===r.domain)).map(x=>`<p>${esc(x.name)} · ${esc(x.status)} · ${esc(x.message)}</p>`).join('')}<h3>02 任务与同步</h3>${(r.snapshot?.sync||memory['assets/sync'].filter(x=>x.domain===r.domain)).map(x=>`<p>${esc(x.name)} · ${esc(x.status)} · 游标 ${esc(x.cursor)}</p>`).join('')}<h3>03 需要处理的异常</h3><p>优先核对陈旧观测和心跳异常；未知状态不计为正常。</p>`;
    else if(r.category==='加固建议')chapters=`<h3>01 需要加固的检查项</h3>${(r.snapshot?.baseline||memory['detection/baseline'].filter(x=>x.domain===r.domain)).filter(x=>x.status!=='通过').map(x=>`<p>${esc(x.name)}：${esc(x.observed)} → 建议 ${esc(x.expected)}</p>`).join('')}<h3>02 变更顺序</h3><ol><li>核对专用管理身份和最小权限。</li><li>在维护窗口应用审计与配置变更。</li><li>执行单项复查并保留前后证据。</li></ol><h3>03 复核记录</h3><p>未通过与未检查分开跟踪，不能将缺失观测视为合规。</p>`;
    else chapters=`<h3>01 资产与风险概览</h3><p>本报告包含 ${assets.length} 项目录资产、${events.length} 条威胁事件。</p><h3>02 关键发现</h3><ul>${events.slice(0,3).map(e=>`<li>${esc(e.title)} · ${esc(e.level)} · ${esc(e.state)}</li>`).join('')||'<li>当前窗口没有关联威胁事件。</li>'}</ul><h3>03 安全加固建议</h3><ol><li>核对特权组成员及服务身份的最小访问范围。</li><li>优先处理高风险发现，变更后执行单项复查。</li><li>确认采集时间与缺失字段，再评估风险变化。</li></ol>`;
    return `<article class="report-preview"><div class="report-kicker">ADTR / SECURITY REPORT</div><h2>${esc(r.name)}</h2><p>${esc(r.category)} · ${esc(scope(r))} · ${esc(r.period)}</p>${chapters}<h3>数据来源</h3><p>目录批次 DEMO-BATCH-001，观测时间 2026-10-10 00:00 UTC。报告保留生成时的范围和数据快照。</p><small>演示数据</small></article>`;
  }
  function download(p,records) {
    const valid=records.every(r=>get(p,r.id)&&domainAllowed(r.domain));if(!valid||!canAction(p,{verb:'download'})||state.downloadRevoked){toast('当前下载权限已失效。');return;}
    let text,type,name;
    if(p.kind==='reports'&&records.length===1){text='<!doctype html><meta charset="utf-8"><title>ADTR 演示报告</title>'+reportBody(records[0]);type='text/html;charset=utf-8';name='ADTR_DEMO_REPORT.html';}
    else {const cs=p.columns;text='\uFEFF'+cs.map(c=>c.label).join(',')+'\r\n'+records.map(r=>cs.map(c=>'"'+pretty(r[c.key]).replace(/"/g,'""')+'"').join(',')).join('\r\n');type='text/csv;charset=utf-8';name='ADTR_DEMO_'+p.id.replace('/','_')+'.csv';}
    const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);audit('下载'+p.title,p.title,'成功',records[0]?.domain||'platform');toast('文件已生成。');
  }
  function query(p,r) {
    const field=r?.query?.split('=')[0]?.trim()||document.getElementById('query-field')?.value||'event_id';const val=r?.query?.split('=')[1]?.trim()||document.getElementById('query-value')?.value||'';
    const windowName=r?.window||document.getElementById('query-window')?.value||'最近 24 小时',days=windowName.includes('7')?7:windowName.includes('30')?30:1;const cutoff=Date.parse('2026-10-10T00:10:00Z')-days*86400000;const data=visible(byId['threats/behavior']).filter(b=>String(b[({event_id:'eventId',account_name:'identity',device:'device'})[field]])===val&&Date.parse(b.observedAt||'2026-10-09T23:00:00Z')>=cutoff);
    openDialog('查询结果',`<p>${esc(field)} = ${esc(val)} · ${esc(windowName)} · ${data.length} 条</p>${data.length?`<div class="timeline">${data.map(b=>`<div class="timeline-item"><small>${esc(b.time)} / ${esc(scope(b))}</small><p>${esc(b.name)} · ${esc(b.identity)} · ${esc(b.device)}</p></div>`).join('')}</div>`:'<p>当前范围内没有匹配事件，请调整条件。</p>'}`);
  }
  function walkthrough(p,r,verb) {
    const epoch=state.epoch,who=state.role,version=r.version;let step=0,used=false;
    function draw(){const steps=['环境与目标','配置与范围','前置检查','安装结果'];openDialog(steps[step],`<div class="wizard-steps">${steps.map((s,i)=>`<span class="${i===step?'current':''}">${i+1} ${s}</span>`).join('')}</div><div class="response-target"><strong>${esc(r.name)}</strong><p>${esc(scope(r))} · ${esc(r.system||r.target||'Windows Server 2022')}</p></div>${step===0?'<p>目标环境：Windows Server x64。已选择对应安装组件与维护窗口。</p>':step===1?'<p>范围包括已确认的目标节点。将保留原配置快照，不自动扩大到其他域控。</p><label class="check-label"><input id="wizard-impact" type="checkbox">确认维护窗口和回退点</label>':step===2?'<div class="check-row">✓ 目标与授权匹配</div><div class="check-row">✓ 证书策略保持验证</div><div class="check-row">✓ 组件版本兼容</div>':'<div class="state-banner info">安装流程已完成。可在实例列表和执行记录中查看状态。</div>'}<div id="wizard-error" role="alert" class="error-inline"></div>`,step<3?btn(step===2?'开始安装':'下一步','confirm-intent','primary'):btn('完成','close-dialog','primary'),()=>{if(used||epoch!==state.epoch||who!==state.role||!get(p,r.id)||r.version!==version||!writable(p)){closeDialog();toast('环境或目标已变化，请重新开始。');return;}if(step===1&&!document.getElementById('wizard-impact').checked){document.getElementById('wizard-error').textContent='请确认维护窗口和回退点。';return;}if(step===2){used=true;r.status='已安装';record(p,r,'完成安装');const collectors=byId['connections/collectors'];if(p.section==='connections'&&!memory[collectors.id].some(c=>c.domain===r.domain&&c.host===r.name))memory[collectors.id].push({id:'local-'+(++seq),domain:r.domain,name:r.name+' / 采集器',host:r.name,agentVersion:'2.4.1',heartbeat:'刚刚',cpu:'未观测',status:'已注册',version:1});}step++;draw();});}
    draw();
  }
  function confirm(p,records,a,apply) {
    const context={epoch:state.epoch,role:state.role,scope:state.domain,targets:records.map(r=>({id:r.id,version:r.version,domain:r.domain})),used:false};
    openDialog(a.label,`<div class="response-target"><strong>${esc(a.label)}</strong>${records.map(r=>`<p>${esc(r.name)} · ${esc(scope(r))} · v${r.version||1}</p>`).join('')}</div><p>${/delete|archive|cleanup/.test(a.verb)?'记录将移至归档，可从原页面恢复；关联历史仍然保留。':/restart|stop|execute|restore|initialize|deploy/.test(a.verb)?'此操作可能影响所选服务或对象。请先确认维护窗口、业务影响和恢复条件。':'此变更仅应用于上列已确认对象，其他范围保持不变。'}</p>${a.verb==='reset'?'<label class="form-field"><span>操作原因</span><input id="biz-reason" maxlength="200" placeholder="填写核对依据"></label>':''}<label class="check-label"><input id="biz-confirm-check" type="checkbox">我已核对目标、范围与影响</label><div id="biz-error" class="error-inline" role="alert"></div>`,btn('确认'+a.label,'confirm-intent','primary'),()=>{if(context.used)return;if(context.epoch!==state.epoch||context.role!==state.role||context.scope!==state.domain||!canAction(p,a)||context.targets.some(t=>!get(p,t.id)||get(p,t.id).version!==t.version||!domainAllowed(t.domain))){closeDialog();toast('对象或权限已变化，请重新确认。');return;}if(!document.getElementById('biz-confirm-check').checked){document.getElementById('biz-error').textContent='请先核对影响。';return;}if(a.verb==='reset'&&!document.getElementById('biz-reason').value.trim()){document.getElementById('biz-error').textContent='请填写操作原因。';return;}const reason=document.getElementById('biz-reason')?.value.trim();context.used=true;apply(reason);closeDialog();render();});
  }
  function applyAction(p,records,a,reason) {
    const v=a.verb, intent=a.intent||v;let queued=0;
    for(const r of records){
      if(['sync','collect','detect','recheck','execute','initialize','deploy-policy','deploy-object','upgrade'].includes(v)){if(startJob(p,r,a))queued++;continue;}
      if(v==='restore'&&p.id==='response/history'){if(/待核对/.test(r.status)){toast('请先核对原执行结果。');continue;}if(startJob(p,r,a))queued++;continue;}
      if(v==='delete'||v==='archive'){r.previousStatus=r.status;r.status='已归档';}
      else if(v==='toggle'){if(p.id==='work/schedules')r.status=r.status==='启用'?'暂停':'启用';else if(p.kind==='rules'){if(!r.testVersion){toast('请先完成当前规则测试。');continue;}r.status=r.status==='已发布'?'已停用':'已发布';}else r.status=/启用|在线|运行|已发布|已激活/.test(r.status)?'停用':'启用';}
      else if(v==='alert'){r.alert=r.alert==='忽略'?'启用':'忽略';}
      else if(v==='select'){memory[p.id].forEach(other=>{if(other.domain===r.domain)other.preferred=false;});r.preferred=true;r.status='首选源';}
      else if(v==='upgrade'){r.agentVersion='2.4.1';r.status='升级完成';}
      else if(v==='test'){
        if(p.kind==='rules'){const field=({event_id:'eventId',account_name:'identity',source_device:'device'})[r.field];const samples=memory['threats/behavior'].filter(b=>b.domain===r.domain);const match=v=>r.operator==='包含'?String(v).includes(r.value):r.operator==='不等于'?String(v)!==r.value:String(v)===r.value;const hits=field?samples.filter(b=>match(b[field])).length:0;const pass=!!r.value&&Number(r.threshold)>0&&hits>=Number(r.threshold);r.testCases=[{name:'目标样本命中',observed:hits,expected:'至少 '+r.threshold,result:pass?'通过':'失败'},{name:'条件配置检查',observed:r.field+' / '+r.operator,expected:'已登记字段与操作符',result:field?'通过':'失败'}];r.testResult=pass?'2 / 2 通过':(field?'1 / 2 通过':'0 / 2 通过');r.testVersion=pass?(r.version||0)+1:null;r.status=pass?'测试通过':'测试失败';}
        else if(p.id==='work/notifications'){const recipients=memory['work/recipients'].filter(x=>x.domain===r.domain&&x.team===r.recipients&&x.status!=='已归档');r.lastTest={time:'10-10 00:10 UTC',channel:r.channel,recipients:recipients.map(x=>x.name+' / '+x.address),result:!recipients.length?'无可用接收人':r.delivery==='立即发送'?'站内测试已完成':'测试通知已排程'};r.lastResult=r.lastTest.result;}
        else if(p.id==='detection/learning'){r.status=Number(String(r.samples).replace(',',''))>=Number(r.minimum)?'样本就绪':'样本不足';}
        else {r.status=state.scenario==='failed'?'检查失败':'检查通过';r.lastResult=state.scenario==='failed'?'未收到确认，请检查配置':'已完成检查';}
      }
      else if(v==='activate'){r.status='已发布';if(p.kind==='rules'){r.ruleVersion=r.ruleVersion.replace('-draft','');(r.versions||(r.versions=[])).push({ruleVersion:r.ruleVersion,condition:r.condition});}}
      else if(v==='reset'){r.reason=reason;if(p.kind==='risk'){r.previous=r.score;r.score='0';r.status='待重新评估';}else if(p.kind==='learning'){r.samples='0';r.status='学习中';}else{r.status='待验证';}}
      else if(v==='evaluate'){r.previous=r.score;r.score=String(api.visibleAssets().find(x=>x.name===r.name&&x.domain===r.domain)?.risk||r.score);r.status='已评估';r.reason='检测结果重新评估';}
      else if(v==='restore'){r.status=r.previousStatus||'已恢复';}
      else if(v==='reconcile'){r.status='结果已核对';}
      else if(['sync','collect','detect','recheck','execute','initialize','deploy-policy','deploy-object','restart'].includes(v)){r.status=state.scenario==='unknown'?'结果待核对':state.scenario==='failed'?'执行失败':'已完成';if(v==='recheck')r.status='需复核';if(v==='sync')r.updated='刚刚';}
      else if(v==='generate'){
        const report={id:'report-'+(++seq),name:r.name+' · 10-10',domain:r.domain,category:r.category,period:r.period,author:role().name,generated:'10-10 00:10 UTC',status:'已生成',version:1,snapshot:{assets:structuredClone(api.visibleAssets().filter(x=>x.domain===r.domain)),events:structuredClone(api.visibleEvents().filter(x=>x.domain===r.domain)),health:structuredClone(memory['work/health'].filter(x=>x.domain===r.domain)),sync:structuredClone(memory['assets/sync'].filter(x=>x.domain===r.domain)),baseline:structuredClone(memory['detection/baseline'].filter(x=>x.domain===r.domain))}};memory['reports/library'].unshift(report);r.status='已生成报告';
      } else {r.status='已完成';}
      applySpecial(p,r,intent);record(p,r,a.label+(reason?'：'+reason:''));
    }
    const asyncAction=['sync','collect','detect','recheck','execute','initialize','deploy-policy','deploy-object','upgrade'].includes(v)||(v==='restore'&&p.id==='response/history');toast(asyncAction?(queued?'已创建 '+queued+' 条任务，可在任务中心查看。':'未创建新任务，请核对当前执行状态。'):v==='generate'?'报告已生成，可在报告库阅读。':a.label+'已完成。');
  }
  function applySpecial(p,r,intent) {
    if(intent==='sign-in'||intent==='login'){r.status='已登录';r.session='有效';}
    if(intent==='sign-out'||intent==='logout'){r.status='已退出';r.session='已撤销';}
    if(/mfa.*bind|bind.*mfa/.test(intent)){r.status='已绑定';r.method='演示验证器';}
    if(/mfa.*unbind|unbind.*mfa/.test(intent)){r.status='未绑定';}
    if(/password|expire|first-login/.test(intent)){r.status='待更新';}
    if(/license.*activate|activate.*license/.test(intent)){r.status='已激活';}
    if(/license.*bind|device.*bind/.test(intent)){r.status='设备已绑定';}
    if(/stop/.test(intent)){r.status='已停止';}
    if(/start/.test(intent)&&!/restart/.test(intent)){r.status='运行中';}
    if(/archive/.test(intent)){r.previousStatus=r.status;r.status='已归档';}
  }
  function action(el) {
    const p=byId[el.dataset.page];if(!p||!allowed(p))return;const verb=el.dataset.verb,intent=el.dataset.intent||verb,r=el.dataset.id?get(p,el.dataset.id):null;
    if(el.dataset.id&&!r){toast('当前对象不可用。');return;}
    const a=schemaActions(p).find(x=>x.verb===verb&&(x.intent||x.verb)===intent)||{label:actionNames[verb]||verb,verb,intent};
    if(el.dataset.batch==='true'&&!selected[p.id]?.size){toast('请先勾选要操作的对象。');return;}
    if(!canAction(p,a)){toast('当前角色没有执行权限。');return;}
    const chosen=r?[r]:(selected[p.id]?.size?visible(p).filter(x=>selected[p.id].has(x.id)):visible(p));if(engine?.action?.(p,r,a,chosen))return;
    if(verb==='inspect'){detail(p,r);return;}
    if(verb==='query'){query(p,r);return;}
    if(!canAction(p,a)){toast('当前角色没有执行权限。');return;}
    if(verb==='create'||verb==='edit'||verb==='clone'){edit(p,r,verb==='clone');return;}
    const records=r?[r]:(selected[p.id]?.size?visible(p).filter(x=>selected[p.id].has(x.id)):visible(p));
    if(verb==='download'){download(p,records);return;}
    if(verb==='cleanup'){const epoch=state.epoch;openDialog('清理过期任务与消息',`<p>将归档当前范围内已完成的任务和已读消息，保留操作审计。未完成和待核对任务不会被归档。</p>`,btn('确认归档','confirm-intent','primary'),()=>{if(epoch!==state.epoch||!writable(p)){closeDialog();return;}let count=0;for(const t of state.tasks){if(t.actor===state.role&&domainAllowed(t.domain)&&['succeeded','cancelled','failed'].includes(t.state)){t.archived=true;count++;}}state.archivedMessages=state.archivedMessages||new Set();api.visibleEvents().filter(e=>state.messagesRead.has(e.id)).forEach(e=>state.archivedMessages.add(e.id));audit('归档任务与消息',String(count)+' 条任务','成功',selectedDomain()||'platform');closeDialog();render();toast('已归档 '+count+' 条终态任务。');});return;}
    if(verb==='template'){const sample={id:'template',name:'DEMO-ACCOUNT',domain:selectedDomain(),checkType:'弱口令',collected:'待采集',evidence:'仅标记',status:'待检查'};const blob=new Blob(['合成账户,所属域,检查类型\r\nDEMO-ACCOUNT,'+api.domains[selectedDomain()]+',弱口令'],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='ADTR_DEMO_CHECK_TEMPLATE.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('检查模板已生成。');return;}
    if(verb==='import'){const domain=selectedDomain();memory[p.id].unshift({id:'local-'+(++seq),name:'维护例外 · 示例导入',domain,scope:'指定规则',rule:'身份异常',match:'demo.maintenance',expiry:'2026-10-15',source:'示例文件',status:'待审核',version:1});render();toast('已导入 1 条待审核记录。');return;}
    if(verb==='install'){walkthrough(p,r||records[0],verb);return;}
    if(verb==='reconcile'&&p.id==='response/history'&&r.sourceTask){api.reconcile(r.sourceTask);tick();return;}
    if(verb==='respond'){if(r.status!=='启用'){toast('此策略未启用，不能发起响应。');return;}const asset=api.visibleAssets().find(x=>x.id===r.assetId&&x.domain===r.domain);if(!asset||asset.name!==r.target){toast('策略目标已变化，请重新选择并保存。');return;}if(!r.assetId){toast('请在策略中选择明确的资产对象。');return;}api.responseTarget(r.assetId,r.domain,Object.freeze({policyId:r.id,policyName:r.name,policyVersion:r.version,effect:r.effect}));return;}
    if(verb==='activate'&&p.kind==='rules'&&(!r.testVersion||r.testVersion!==r.version||r.testResult!=='2 / 2 通过')){toast('请先完成当前草稿的样本测试。');return;}
    if(!records.length){toast('请先选择记录。');return;}
    if(a.confirm||['delete','reset','restore','activate','upgrade','generate','execute','restart','cleanup','initialize','deploy-policy','deploy-object','sync','collect','detect','recheck'].includes(verb)){confirm(p,records,a,reason=>applyAction(p,records,a,reason));}
    else {applyAction(p,records,a);closeDialog();render();}
  }
  function startJob(p,r,a){
    if(pendingJobs.some(j=>j.p===p.id&&j.id===r.id&&!j.applied)){toast('此对象已有运行或待核对任务，请查看原任务。');return false;}
    const scenario=a.verb==='upgrade'&&r.status==='心跳异常'?'failed':state.scenario;
    const task=api.createTask({id:'business-'+(++seq),kind:p.id==='detection/templates'&&a.verb==='detect'?'detection':'business-'+a.verb,template:p.id==='detection/templates'?Object.freeze({id:r.id,name:r.name,version:String(r.version),checks:r.checks,targetDefinition:r.targets}):null,targets:p.id==='detection/templates'?Object.freeze(api.visibleAssets().filter(x=>x.domain===r.domain).map(x=>Object.freeze({id:x.id,name:x.name,guid:x.guid,domain:x.domain}))):null,domain:r.domain,role:state.role,epoch:state.epoch,scenario,target:{name:r.name,assetId:r.assetId||r.id,guid:r.targetGuid||null,domain:r.domain,version:r.targetVersion||r.version}},a.label+' · '+r.name);
    r.lastTask=task.id;if(a.verb==='restore'){r.recoveryTask=task.id;r.recoveryState='恢复中';}r.previousStatus=r.status;r.status='排队中';record(p,r,'提交'+a.label);pendingJobs.push({p:p.id,id:r.id,taskId:task.id,verb:a.verb,actor:state.role,epoch:state.epoch,applied:false});return true;
  }
  function tick(){
    let changed=false;
    for(const j of pendingJobs){if(j.applied)continue;const t=state.tasks.find(t=>t.id===j.taskId),p=byId[j.p],r=memory[j.p].find(r=>r.id===j.id);if(!t||!r)continue;
      if(['queued','running','cancel_requested'].includes(t.state)){const next=api.taskLabel?api.taskLabel(t):({queued:'排队中',running:'运行中',cancel_requested:'已请求取消'})[t.state];if(r.status!==next){r.status=next;changed=true;}continue;}
      j.applied=t.state!=='unknown';if(t.state!=='succeeded'||j.epoch!==state.epoch||j.actor!==state.role){r.status=({cancelled:'已取消',unknown:'结果待核对',failed:'执行失败',partial_failed:'部分失败'})[t.state]||'待核对';if(j.verb==='restore'){r.recoveryState='恢复'+r.status;r.status=r.recoveryState;}r.lastResult=t.error||r.status;changed=true;continue;}
      r.status='已完成';r.lastResult='目标 '+r.name+' 执行完成';
      if(j.verb==='restore'){r.recoveryTask=t.id;r.recoveryState='已恢复';r.status='已恢复';(r.recoveryHistory||(r.recoveryHistory=[])).push({task:t.id,result:'已恢复',time:'10-10 00:10 UTC'});}
      if(j.verb==='upgrade'){r.agentVersion='2.4.1';r.status='在线';r.heartbeat='刚刚';}
      if(j.verb==='sync'){r.cursor='change-'+(++seq);r.batch='BATCH-'+seq;r.objects=String(api.visibleAssets().filter(x=>x.domain===r.domain).length||r.objects||0);r.updated='10-10 00:10 UTC';r.changes=r.mode==='全量目录'?'全量快照已生成':r.mode==='设备名称与地址'?'设备名称与地址已更新':'新增 1 / 更新 1 / 删除待核验 0';}
      if(j.verb==='collect'){r.collected='10-10 00:10 UTC';r.status='数据已就绪';}
      if(j.verb==='detect'||j.verb==='recheck'){r.resultVersion=(r.resultVersion||0)+1;r.status=r.observed==='未采集'?'未检查':r.severity==='高'?'未通过':'待复核';r.evidenceVersion='OBS-'+seq;r.lastResult=r.status+' · 观测版本 '+r.evidenceVersion;}
      if(j.verb==='deploy-policy')r.policyStatus='审计策略已部署';if(j.verb==='deploy-object')r.objectAuditStatus='对象审计已部署';
      record(p,r,'完成'+t.title);changed=true;
    }
    for(const t of state.tasks.filter(t=>t.kind==='response'&&t.target)){let r=memory['response/history'].find(x=>x.sourceTask===t.id);if(!r){r={id:'execution-'+t.id,sourceTask:t.id,domain:t.domain,name:t.target.name,assetId:t.target.assetId,targetGuid:t.target.guid,targetVersion:t.target.version,effect:t.target.effect||'限制账户访问',policy:t.target.policyId?`${t.target.policyName} / ${t.target.policyId} / v${t.target.policyVersion}`:t.target.eventId?'事件 '+t.target.eventId:'人工响应',time:'10-10 00:10 UTC',version:1,status:api.taskLabel(t),ownerRole:t.actor};memory['response/history'].unshift(r);}r.executionState=api.taskLabel(t);if(!r.recoveryState&&r.status!==r.executionState){r.status=r.executionState;changed=true;}}
    if(changed&&current()&&!document.getElementById('dialog').open)render();
  }
  function clearContext(){draft=null;Object.keys(selected).forEach(k=>delete selected[k]);Object.keys(searches).forEach(k=>delete searches[k]);}
  function onInput(el){if(el.dataset.bizFilter){const pos=el.selectionStart;searches[el.dataset.bizFilter]=el.value;render();const next=document.querySelector('[data-biz-filter="'+el.dataset.bizFilter+'"]');next?.focus();if(pos!==null)next?.setSelectionRange(pos,pos);return true;}if(el.id?.startsWith('biz-field-')&&draft&&byId[draft.p].kind==='rules'){const preview=document.getElementById('rule-preview');if(preview)preview.textContent=['field','operator','value','window','threshold'].map(k=>document.getElementById('biz-field-'+k)?.value||'').join(' · ');}return false;}
  function onChange(el){if(el.dataset.bizSelect){(selected[el.dataset.bizSelect]||(selected[el.dataset.bizSelect]=new Set()))[el.checked?'add':'delete'](el.dataset.id);return true;}return false;}
  return {pages,current,subnav,renderPage,resumeSession:()=>engine?.resumeSession?.(),clearContext,onInput,onChange,tick,overviewData:()=>visible(byId['detection/baseline']),policyValid:t=>!t?.policyId||memory['response/policies'].some(r=>r.id===t.policyId&&r.version===t.policyVersion&&r.assetId===t.assetId&&r.domain===t.domain&&r.effect===t.effect&&r.status==='启用'&&domainAllowed(r.domain)),isBlocked:asset=>memory['response/allowlist'].some(r=>r.domain===asset.domain&&r.name===asset.name&&r.status!=='已归档'),fromEvent:e=>edit(byId['detection/allowlists'],null,false,{name:e.title+' · 例外',domain:e.domain,scope:'指定规则',rule:e.rule,match:api.visibleAssets().find(a=>a.id===e.asset)?.name||'',expiry:'2026-10-17',reason:'事件审核'}),actions:{'biz-action':action,'biz-save':save,'biz-archives':el=>{archiveViews[el.dataset.page]=!archiveViews[el.dataset.page];render();},'biz-search':el=>query(byId[el.dataset.page],null)}};
};
